AdfUIComponents.createComponentClass("AdfRichPanelBox",{componentType:"oracle.adf.RichPanelBox",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},"disclosureListener",{name:"disclosed",type:"Boolean","default":!0},{name:"immediate",type:"Boolean","default":!1},{name:"persist",type:"Array"},{name:"dontPersist",type:"Array"},{name:"showDisclosure",
type:"Boolean","default":!0},{name:"maximized",type:"Boolean","default":!1},{name:"showMaximize",type:"String","default":"auto"},"maximizeListener",{name:"contentDelivery",type:"String","default":"lazyUncached"},{name:"helpTopicId",type:"String"},{name:"text",type:"String"},{name:"type",type:"String","default":"default"},{name:"showHeader",type:"String","default":"ifNeeded"},{name:"ramp",type:"String","default":"core"},{name:"background",type:"String","default":"default"},{name:"icon",type:"String"},
{name:"contentStyle",type:"String"},{name:"titleHalign",type:"String","default":"start"}],eventNames:["disclosure"],superclass:AdfUIPanel});

AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelBoxPeer",!1);AdfDhtmlPanelBoxPeer.DISCLOSURE_SUB_ID="_afrDscl";AdfDhtmlPanelBoxPeer._INNER_SD_PEER=AdfRichUIPeer.createInnerPeerClassWithSubId(AdfDhtmlShowDisclosurePeer,"InnerPBShowDetailPeer",AdfDhtmlPanelBoxPeer.DISCLOSURE_SUB_ID);InnerPBShowDetailPeer.InitSubclass=function(){AdfDhtmlTogglePeer.Config(this,{toggledStyleClass:"af|panelBox::disclosed-icon-style",untoggledStyleClass:"af|panelBox::undisclosed-icon-style"})};
InnerPBShowDetailPeer.prototype.HandleClientSideToggle=function(a){if(this.outerThis.GetContentDomElement()&&InnerPBShowDetailPeer.superclass.HandleClientSideToggle.call(this,a))return this.outerThis.__handleClientSideDisclosure(a),!0;return!1};AdfDhtmlPanelBoxPeer.MAXIMIZE_SUB_ID="_afrMax";AdfDhtmlPanelBoxPeer._INNER_MAXIMIZE_PEER=AdfRichUIPeer.createInnerPeerClassWithSubId(AdfDhtmlMaximizePeer,"InnerPBMaximizePeer",AdfDhtmlPanelBoxPeer.MAXIMIZE_SUB_ID);
InnerPBMaximizePeer.InitSubclass=function(){AdfDhtmlTogglePeer.Config(this,{toggledStyleClass:"af|panelBox::maximized-icon-style",untoggledStyleClass:"af|panelBox::unmaximized-icon-style"})};InnerPBMaximizePeer.prototype.HandleClientSideToggle=function(a){var b=this.outerThis,c=b.GetContentDomElement();if(c&&InnerPBMaximizePeer.superclass.HandleClientSideToggle.call(this,a))return b.__handleClientSideMaximize(b.getDomElement(),c,a),!0;return!1};
InnerPBMaximizePeer.prototype.ComponentMaximizedChanged=function(a,b,c,d){b=InnerPBMaximizePeer.superclass.ComponentMaximizedChanged.call(this,a,b,c,d);c&&a.setDisclosed(!0);return b};InnerPBMaximizePeer.prototype.EventPropagatesToServer=function(){return!this.outerThis.GetContentDomElement()};
AdfDhtmlPanelBoxPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfRichPanelBox);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichPanelBox.DISCLOSED,AdfRichPanelBox.MAXIMIZED);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfDisclosureEvent.EVENT_TYPE,AdfMaximizeEvent.EVENT_TYPE);this._DRAG_RECOGNIZER=new AdfPanelBoxDragRecognizer};
AdfDhtmlPanelBoxPeer.prototype.Init=function(a){AdfDhtmlPanelBoxPeer.superclass.Init.call(this,a);var b=a.getClientId(),c=AdfRichUIPeer.CreateSubId(b,AdfDhtmlPanelBoxPeer.DISCLOSURE_SUB_ID);if(AdfAgent.AGENT.getElementById(c))this._disclosurePeer=this.CreateDisclosurePeer(a);b=AdfRichUIPeer.CreateSubId(b,AdfDhtmlPanelBoxPeer.MAXIMIZE_SUB_ID);if(AdfAgent.AGENT.getElementById(b))this._maximizePeer=this.CreateMaximizePeer(a)};
AdfDhtmlPanelBoxPeer.prototype.CreateDisclosurePeer=function(a){return new AdfDhtmlPanelBoxPeer._INNER_SD_PEER(a,this)};AdfDhtmlPanelBoxPeer.prototype.CreateMaximizePeer=function(a){return new AdfDhtmlPanelBoxPeer._INNER_MAXIMIZE_PEER(a,this)};AdfDhtmlPanelBoxPeer.prototype.initialize=function(a){var b=this._disclosurePeer;b&&b.initialize(a);(b=this._maximizePeer)&&b.initialize(a);AdfDhtmlPanelBoxPeer.superclass.initialize.call(this,a)};
AdfDhtmlPanelBoxPeer.prototype.InitDomElement=function(a,b){AdfDhtmlPanelBoxPeer.superclass.InitDomElement.call(this,a,b);var c=this.GetContentDomElement(b);c&&(this._checkAnimateDisclosure(a,c),this._maximizePeer&&this.__handleClientSideMaximize(b,c,a.getMaximized()))};AdfDhtmlPanelBoxPeer.prototype.GetContentDomElement=function(a){a||(a=this.getDomElement());a=AdfRichUIPeer.CreateSubId(a.id,"content");return AdfAgent.AGENT.getElementById(a)};
AdfDhtmlPanelBoxPeer.prototype._checkAnimateDisclosure=function(a,b){if(b&&b.style.visibility=="hidden"){var c=b.style.height,c=c?parseInt(c):b.offsetHeight,d=b.ownerDocument.createElement("div");d.style.overflow="hidden";d.style.height="1px";b.parentNode.replaceChild(d,b);d.appendChild(b);b.style.visibility="visible";var e=this._getAnimationDuration();AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_CONSTANT_SPEED,e,[{element:d,properties:{height:c}}],null,AdfDhtmlPanelBoxPeer._handleAfterDiscloseAnimate,
[d,b],a)}};AdfDhtmlPanelBoxPeer._handleAfterDiscloseAnimate=function(a){var b=a[0],c=b.parentNode;if(c)a=a[1],a.style.height=b.style.height,c.replaceChild(a,b)};AdfDhtmlPanelBoxPeer.prototype._getAnimationDuration=function(){return parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelBox-tr-animation-duration"))};
AdfDhtmlPanelBoxPeer.prototype._animateUndisclosure=function(a){var b=this.GetContentDomElement(),c=b.style.height;b.style.overflow="hidden";var d=this._getAnimationDuration(),e=this.getComponent();AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_CONSTANT_SPEED,d,[{element:b,properties:{height:0}}],null,AdfDhtmlPanelBoxPeer._handleAfterUndiscloseAnimateStub,[e,a,c],e)};
AdfDhtmlPanelBoxPeer._handleAfterUndiscloseAnimateStub=function(a){var b=a[0],c=b.getPeer();c&&(c.bind(b),c._handleAfterUndiscloseAnimate(a[1],a[2]))};AdfDhtmlPanelBoxPeer.prototype._handleAfterUndiscloseAnimate=function(a,b){var c=this.getComponent();if(!c.isDead()){var d=this.GetContentDomElement();if(d)d.style.visibility="hidden";c.HandleEvent.call(c,a);AdfAssert.assert(!c.getDisclosed());this.__handleClientSideDisclosure(!1);if(d)c=d.style,c.display="none",c.height=b?b:""}};
AdfDhtmlPanelBoxPeer.prototype.DispatchUncanceledComponentEvent=function(a){return AdfPage.PAGE.isAnimationEnabled()&&a.getType()==AdfDisclosureEvent.EVENT_TYPE&&!a.isExpanded()?(this._animateUndisclosure(a),!0):!1};AdfDhtmlPanelBoxPeer.prototype.HandleComponentClick=function(a){var b=this._disclosurePeer;b&&b.HandleComponentClick(a);(b=this._maximizePeer)&&b.HandleComponentClick(a)};
AdfDhtmlPanelBoxPeer.prototype.HandleComponentKeyUp=function(a){var b=this._disclosurePeer;b&&b.HandleComponentKeyUp(a);(b=this._maximizePeer)&&b.HandleComponentKeyUp(a)};AdfDhtmlPanelBoxPeer.prototype.HandleComponentDisclosure=function(a){var b=this._disclosurePeer;b&&b.HandleComponentDisclosure(a)};AdfDhtmlPanelBoxPeer.prototype.HandleComponentMaximize=function(a){var b=this._maximizePeer;b&&b.HandleComponentMaximize(a)};
AdfDhtmlPanelBoxPeer.prototype.ComponentDisclosedChanged=function(a,b,c,d){var e=this._disclosurePeer;return e?e.ComponentDisclosedChanged(a,b,c,d):!1};AdfDhtmlPanelBoxPeer.prototype.ComponentMaximizedChanged=function(a,b,c,d){var e=this._maximizePeer;return e?e.ComponentMaximizedChanged(a,b,c,d):!1};AdfDhtmlPanelBoxPeer.prototype.__isEventForHeaderControls=function(a){var b=!1,c=this._disclosurePeer;c&&(b|=c.isEventForButton(a));(c=this._maximizePeer)&&(b|=c.isEventForButton(a));return b};
AdfDhtmlPanelBoxPeer.prototype.getDefaultDragRecognizer=function(){return AdfDhtmlPanelBoxPeer._DRAG_RECOGNIZER};
AdfDhtmlPanelBoxPeer.prototype.__handleClientSideDisclosure=function(a){var b=this.GetContentDomElement(),c=b.parentNode,d=b.style,e=AdfPage.PAGE.isAnimationEnabled();if(a){if(e)d.visibility="hidden";d.display="";c.style.display=""}else if(!e)c.style.display="none",d.display="none";c=this.getDomElement();d=c.lastChild;e=AdfAgent.AGENT.getNodeName(d)=="DIV";if(a){if(e)d.style.top="";this._checkAnimateDisclosure(this.getComponent(),b)}else if(e)d.style.top=c.firstChild.clientHeight+"px"};
AdfDhtmlPanelBoxPeer.prototype.__handleClientSideMaximize=function(a,b,c){AdfAssert.assertDomElement(a);AdfAssert.assertDomElement(b);AdfAssert.assertBoolean(c);this._maximizePeer.__updateClientMaximize(a,b,c);if(a=this._disclosurePeer)if(a=a.GetButtonElement())a.style.display=c?"none":"block"};function AdfPanelBoxDragRecognizer(){this.Init()}AdfObject.createSubclass(AdfPanelBoxDragRecognizer,AdfDragRecognizer);
AdfPanelBoxDragRecognizer.prototype.prepDrag=function(a,b,c){AdfAssert.assertPrototype(b,AdfDragSource);AdfAssert.assertPrototype(c,AdfUIInputEvent);if(AdfAgent.AGENT.isDragPrepEvent(c)){var d=b.getComponent();AdfAssert.assertObject(d,"Unexpected null component.");var e=d.getPeer(),f=c.getNativeEvent();if(!e.__isEventForHeaderControls(f)&&(AdfAssert.assert(e,"Unexpected null peer."),e.bind(d),d=e.getDomElement(),d=AdfDomUtils.getFirstChildElement(d)))if(e=AdfAgent.AGENT.getNodeName(d),"TABLE"!=e&&
(d=AdfDomUtils.getFirstChildElement(d),e=AdfAgent.AGENT.getNodeName(d)),"TABLE"==e&&(e=c.getNativeEventTarget(),AdfDomUtils.isAncestorOrSelf(d,e)))return AdfPanelBoxDragRecognizer.superclass.prepDrag.apply(this,arguments)}return null};