AdfUIComponents.createComponentClass("AdfUIIterator",{componentType:"org.apache.myfaces.trinidad.Iterator",propertyKeys:["value",{name:"rows",type:"Number","default":25},{name:"first",type:"Number","default":0}],superclass:AdfUICollection});
AdfUIComponents.createComponentClass("AdfUITable",{componentType:"org.apache.myfaces.trinidad.Table",propertyKeys:[{name:"rowDisclosureListener",type:"Object",secured:!0},"disclosedRowKeys",{name:"selectionListener",type:"Object",secured:!0},"selectedRowKeys",{name:"immediate",type:"Boolean","default":!1,secured:!0},{name:"sortListener",type:"Object",secured:!0},{name:"rangeChangeListener",type:"Object",secured:!0},{name:"showAll",type:"Boolean","default":!1,secured:!0}],eventNames:["rowDisclosure",
"selection","rangeChange","sort"],superclass:AdfUIIterator});
AdfUITable.SELECTION_LISTENER_KEY="afrSelListener";AdfUITable.prototype.findComponent=function(a,b){if(b!=void 0)return a=this.getClientId()+":"+b+":"+a,AdfPage.PAGE.findComponent(a);return AdfUITable.superclass.findComponent.call(this,a)};AdfUITable.prototype.Init=function(a,b,c,d,f){AdfUITable.superclass.Init.call(this,a,b,c,d,f)};
AdfUITable.prototype.GetChanges=function(){var a=AdfUITable.superclass.GetChanges.call(this),b=a[AdfUITable.DISCLOSED_ROW_KEYS];if(b){var c=[],d=0,f;for(f in b)c[d++]=f;a[AdfUITable.DISCLOSED_ROW_KEYS]=c.join("$afr$")}if(b=a[AdfUITable.SELECTED_ROW_KEYS]){var c=[],g;for(g in b)c.push(g);a[AdfUITable.SELECTED_ROW_KEYS]=c.join("$afr$")}return a};
AdfUITable.prototype.DeliverDerivedPropertyEvents=function(a,b,c){if(a==AdfUITable.SELECTED_ROW_KEYS&&(a=this.getPeer())&&a.canDeliverSelectionEvent&&a.canDeliverSelectionEvent())(b=AdfRowKeySetChangeEvent.createRowKeySetChangeEvent(this,AdfSelectionEvent.SELECTION_EVENT_TYPE,b,c))&&b.queue()};
AdfUITable.prototype.setDisclosedRowKey=function(a,b){AdfAssert.assertString(a);AdfAssert.assertBoolean(b);if(b==this.isDisclosed(a))return!1;var c=this.getPeer();if(c&&c.isDisclosureFetchPending())return!1;var d=this.getDisclosedRowKeys(),c={};AdfCollections.copyInto(c,d);b?c[a]=!0:delete c[a];(d=AdfRowKeySetChangeEvent.createRowKeySetChangeEvent(this,AdfRowDisclosureEvent.ROW_DISCLOSURE_EVENT_TYPE,d,c))&&d.queue();if(d.isCanceled())return!1;this.setDisclosedRowKeys(c);return!0};
AdfUITable.prototype.isDisclosed=function(a){var b=this.getDisclosedRowKeys();if(b)return b[a];return!1};AdfUITable.prototype.getSelectedColumns=function(){var a=[],b=this.getPeer();if(b)for(var b=b.__getSelectedColumns(),c=0;c<b.length;c++)a.push(b[c].getClientId());return a};
AdfUIComponents.createComponentClass("AdfUITable2",{componentType:"oracle.adf.Table",propertyKeys:[{name:"filterModel",type:"Object",secured:!0}],eventNames:["query"],superclass:AdfUITable});
function AdfTableUtils(){this.Init()}AdfObject.createSubclass(AdfTableUtils);AdfTableUtils.InitClass=function(){};AdfTableUtils.prototype.Init=function(){AdfTableUtils.superclass.Init.call()};AdfTableUtils.queueColumnSelectionEvent=function(a,b,c){var b=AdfTableUtils.processColumnSelectionEventChangedSets(b,c),c=[],d=[],e=0,f;for(f in b[0])c[e++]=f;e=0;for(f in b[1])d[e++]=f;AdfColumnSelectionEvent.queue(a,c,d)};
AdfTableUtils.processColumnSelectionEventChangedSets=function(a,b){var c=null,d=null;if(b)if(a)for(var e in b)a[e]||(c||(c={}),c[e]=!0);else c={},AdfCollections.copyInto(c,b);if(a)if(b)for(e in a)b[e]||(d||(d={}),d[e]=!0);else d={},AdfCollections.copyInto(d,a);return[d==null?{}:d,c==null?{}:c]};
AdfTableUtils.queueSortEvent=function(a,b,c){a.setProperty("scrollTopRowKey",null,!0,AdfUIComponent.PROPAGATE_ALWAYS);var d=a.getPeer();d&&(d=d.GetAssociatedComponent(),d!=null&&d.setProperty("scrollTopRowKey",null,!0,AdfUIComponent.PROPAGATE_ALWAYS));(new AdfSortEvent(a,b,c)).queue()};
AdfUIComponents.createComponentClass("AdfUIColumn",{componentType:"org.apache.myfaces.trinidad.Column",propertyKeys:[{name:"sortProperty",type:"String",secured:!0},{name:"sortStrength",type:"String","default":"Identical",secured:!0}]});
AdfUIComponents.createComponentClass("AdfRichColumn",{componentType:"oracle.adf.RichColumn",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"persist",type:"Array"},{name:"dontPersist",type:"Array"},{name:"align",type:"String"},{name:"headerClass",type:"String"},{name:"footerClass",type:"String"},{name:"width",type:"String","default":"100"},{name:"minimumWidth",type:"String","default":"12"},{name:"headerText",type:"String"},
{name:"noWrap",type:"Boolean","default":!0},{name:"headerNoWrap",type:"Boolean","default":!1},{name:"sortable",type:"Boolean","default":!1},{name:"filterable",type:"Boolean","default":!1},{name:"separateRows",type:"Boolean","default":!1},{name:"rowHeader",type:"String","default":"false"},{name:"selected",type:"Boolean","default":!1},{name:"displayIndex",type:"Number","default":-1},{name:"frozen",type:"Boolean","default":!1},{name:"helpTopicId",type:"String"},{name:"showRequired",type:"Boolean","default":!1},
{name:"visible",type:"Boolean","default":!0},{name:"colSpan",type:"String","default":"1"}],superclass:AdfUIColumn});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlColumnPeer",!1);AdfDhtmlColumnPeer.InitSubclass=function(){AdfRichUIPeer.addSuppressedPPRAttributes(this,AdfRichColumn.WIDTH,AdfRichColumn.MINIMUM_WIDTH,AdfRichColumn.SELECTED);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichColumn.WIDTH,AdfRichColumn.SHOW_REQUIRED);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichColumn.DISPLAY_INDEX)};
AdfDhtmlColumnPeer.prototype.Init=function(a,b){AdfDhtmlColumnPeer.superclass.Init.call(this,a,b);typeof window.AdfColumnDragSource!="undefined"&&(a.setDragSource(new AdfColumnDragSource),a.setDropTarget(new AdfColumnDropTarget))};AdfDhtmlColumnPeer.prototype.GetComponentDisplayIndex=function(a,b){return AdfAgent.AGENT.getIntAttribute(b,"_d_index",-1)};
AdfDhtmlColumnPeer.prototype.ComponentWidthChanged=function(a,b,c,d){for(b=a.getParent();b&&!(b instanceof AdfUICollection);)b=b.getParent();b!=null&&b.getPeer().resizeColumn(a,c,d)};AdfDhtmlColumnPeer.prototype.ScrollIntoView=function(a,b,c){for(a=a.getParent();a&&!(a instanceof AdfUICollection);)a=a.getParent();a!=null&&a.getPeer().scrollColumnIntoView(null,this.getDomElement());c!=null&&AdfLogger.LOGGER.warning("subTargetId not supported for column ScrollIntoView");b&&AdfLogger.LOGGER.warning("Focus not supported for column ScrollIntoView")};
AdfDhtmlColumnPeer.prototype.ComponentShowRequiredChanged=AdfDhtmlOutputLabelPeer.__componentShowRequiredChanged;
function AdfStampedDragSource(a,b,c){arguments.length&&this.Init(a,b,c)}AdfObject.createSubclass(AdfStampedDragSource,AdfDragSource);AdfStampedDragSource.prototype.Init=function(a,b,c){AdfStampedDragSource.superclass.Init.call(this,a,b);this._modelName=c};AdfStampedDragSource.prototype.getModelName=function(){return this._modelName};
AdfStampedDragSource.prototype.isAvailable=function(a,b){AdfAssert.assertPrototype(a,AdfDnDContext);AdfAssert.assertPrototype(b,AdfUIInputEvent);AdfAssert.DEBUG&&AdfDnDContext.assertUserAction(a.getUserAction());this.getComponent().getPeer();return this.AreDraggedRowKeysAvailable(b)?!0:AdfStampedDragSource.superclass.GetDragTransferable.call(this,b)!=null};AdfStampedDragSource.prototype.getRowKeyDataFlavor=function(){if(this.getComponent()){var a=this._modelName;if(a)return AdfDataFlavor.getRowKeyDataFlavor(a)}return null};
AdfStampedDragSource.prototype.GetDragTransferable=function(a){var b=AdfStampedDragSource.superclass.GetDragTransferable.call(this,a);this.getComponent();var c=this._modelName;if(c&&c.length&&(a=this._getRowKeys(a),AdfAssert.assertArrayOrNull(a),a)){var d=[],e=[];if(b!=null)for(var f=b.getTransferDataFlavors(),g=f.length,h=0;h<g;h++){var k=f[h];d.push(k);e.push(b.getTransferData(k))}b=AdfDataFlavor.getRowKeyDataFlavor(c);e.push(a);d.push(b);return new AdfObjectTransferable(e,d)}return b};
AdfStampedDragSource.prototype.GetDragOffset=function(a){var b=this._getRowKeys(a);return b?this.GetDragOffsetForRowKeys(a,b):{x:a.getOffsetX(),y:a.getOffsetY()}};AdfStampedDragSource.prototype.GetDragOffsetForRowKeys=function(a,b){AdfAssert.assertArray(b);return this.getComponent().getPeer().getDragOffsetForRowKeys(a,b)};
AdfStampedDragSource.prototype.GetDragOverFeedback=function(a){AdfAssert.assertPrototype(a,AdfUIInputEvent);var b=this._getRowKeys(a);return b?this.GetDragOverFeedbackForRowKeys(b):AdfStampedDragSource.superclass.GetDragOverFeedback.call(this,a)};AdfStampedDragSource.prototype.applyDragReadyState=function(a){AdfAssert.assertPrototype(a,AdfUIInputEvent);var b=this._getRowKeys(a);return b?this.ApplyDragReadyStateForRowKeys(a,b):AdfStampedDragSource.superclass.applyDragReadyState.call(this,a)};
AdfStampedDragSource.prototype.ApplyDragReadyStateForRowKeys=function(a,b){AdfAssert.assertArray(b);var c=this.getComponent(),d=c.getPeer();return d.applyDragReadyStateForRowKeys?d.applyDragReadyStateForRowKeys(c,a,b):AdfStampedDragSource.superclass.applyDragReadyState.call(this,a)};
AdfStampedDragSource.prototype.applyDragSourceState=function(a){AdfAssert.assertPrototype(a,AdfDomUIInputEvent);var b=this._getRowKeys(a);return b?this.ApplyDragSourceStateForRowKeys(a,b):AdfStampedDragSource.superclass.applyDragSourceState.call(this,a)};
AdfStampedDragSource.prototype.ApplyDragSourceStateForRowKeys=function(a,b){AdfAssert.assertArray(b);var c=this.getComponent(),d=c.getPeer();return d.applyDragSourceStateForRowKeys?d.applyDragSourceStateForRowKeys(c,a,b):AdfStampedDragSource.superclass.applyDragSourceState.call(this,a)};AdfStampedDragSource.prototype.GetDragOverFeedbackForRowKeys=function(a){AdfAssert.assertArray(a);return this.getComponent().getPeer().getDragNodeForRowKeys(a)};
AdfStampedDragSource.prototype.GetDraggedRowKeys=function(a){AdfAssert.assert(a);return[a]};AdfStampedDragSource.prototype.AreDraggedRowKeysAvailable=function(a){return this._getRowKeys(a)!=null};AdfStampedDragSource.prototype._getRowKeys=function(a){return(a=this.getComponent().getPeer().getRowKeyForEvent(a))?this.GetDraggedRowKeys(a):null};
function AdfTableDragSource(a,b,c){arguments.length&&this.Init(a,b,c)}AdfObject.createSubclass(AdfTableDragSource,AdfStampedDragSource);AdfTableDragSource.prototype.GetDraggedRowKeys=function(a){AdfAssert.assert(a);var b=this.getComponent().getSelectedRowKeys();if(b!=null&&b.afrSelectAll==null&&b[a]!=null){var a=[],c;for(c in b)a.push(c);return a}else return[a]};AdfTableDragSource.prototype.AreDraggedRowKeysAvailable=function(a){return this.getComponent().getPeer().getRowKeyForEvent(a)!=null};