AdfUserActivityInfo.PREVIOUS="pr0";AdfUserActivityInfo.PRIMARY="prm";AdfUserActivityInfo.SECONDARY="sec";AdfUserActivityInfo._PREVIOUS_PREFIX="pr";function AdfUserActivityInfo(){this.Init()}AdfObject.createSubclass(AdfUserActivityInfo);AdfUserActivityInfo.getInstance=function(a){AdfAssert.assertString(a);var b=AdfUserActivityInfo._instanceMap;if(!b)b={},AdfUserActivityInfo._instanceMap=b;var c=null;a&&(c=b[a],c||(c=new AdfUserActivityInfo,b[a]=c));return c};
AdfUserActivityInfo.removeFromSessionStorageByType=function(a){AdfAssert.assertNonEmptyString(a);AdfUserActivityInfo._removeSessionStorageProperty(a)};
AdfUserActivityInfo.restoreFromSessionStorage=function(){var a=AdfUserActivityInfo.PRIMARY,b=AdfUserActivityInfo.PREVIOUS,c=AdfUserActivityInfo._getSessionStorageProperty(a);c?(AdfUserActivityInfo._getAsObject(String(c),b),c=AdfUserActivityInfo.getInstance(b),c.getClientStartTime()||c.setClientStartTime(c._getCurrentTime()),AdfUserActivityInfo._removeSessionStorageProperty(a)):(a=AdfUserActivityInfo.getInstance(b),a.getClientStartTime()||a.setClientStartTime(a._getCurrentTime()));if(a=AdfUserActivityInfo._getSessionStorageProperty(b))AdfUserActivityInfo._getAsObject(String(a),
AdfUserActivityInfo._getPreviousKeyInSequence(1)),AdfUserActivityInfo._removeSessionStorageProperty(b);b=AdfUserActivityInfo.SECONDARY;if(a=AdfUserActivityInfo._getSessionStorageProperty(b))AdfUserActivityInfo._getAsObject(String(a),b),AdfUserActivityInfo._removeSessionStorageProperty(b)};
AdfUserActivityInfo.saveToSessionStorage=function(){if(AdfUserActivityInfo._instanceMap!=null){AdfUserActivityInfo.restoreFromSessionStorage();var a=AdfUserActivityInfo.getInstance(AdfUserActivityInfo.PREVIOUS),b=a._getCurrentTime();a.setClientEndTime(b);AdfUserActivityInfo.saveToSessionStorageByType(AdfUserActivityInfo.PREVIOUS);AdfUserActivityInfo.getInstance(AdfUserActivityInfo.PRIMARY).setClientStartTime(b);AdfUserActivityInfo.saveToSessionStorageByType(AdfUserActivityInfo.PRIMARY);AdfUserActivityInfo.cleanInstanceMap()}};
AdfUserActivityInfo.saveToSessionStorageByType=function(a){var b=AdfUserActivityInfo.getInstance(a);b&&(userActInfoValue=AdfUserActivityInfo._getAsString(b),AdfUserActivityInfo._setSessionStorageProperty(a,userActInfoValue))};AdfUserActivityInfo.prototype.Init=function(){AdfUserActivityInfo.superclass.Init.call(this);this.rrt=this.ppr=this.eif=this.cet=this.cst=this.cid=null};
AdfUserActivityInfo.getMarshaledObject=function(){var a=AdfAgent.AGENT,b=a.createXmlDocument(),c=b.createElement("TEMP");a.getPlatform()==AdfAgent.IE_PLATFORM?b.documentElement=c:b.appendChild(c);b=AdfMarshalingService.getDefault().marshal(c,AdfUserActivityInfo._instanceMap,null);AdfUserActivityInfo.cleanInstanceMap();return a.getNodeXml(b)};AdfUserActivityInfo.setRequestSentTime=function(a){var b=null;if(!a)a=AdfUserActivityInfo.PRIMARY;b=AdfUserActivityInfo.getInstance(a);b.rst=b._getCurrentTime()};
AdfUserActivityInfo.setResponseReceivedTime=function(a){var b=null;if(!a)a=AdfUserActivityInfo.PREVIOUS;b=AdfUserActivityInfo.getInstance(a);b.rrt=b._getCurrentTime()};AdfUserActivityInfo.prototype.getContextId=function(){return this.cid};AdfUserActivityInfo.prototype.getParentContextId=function(){return this.pid};AdfUserActivityInfo.prototype.getClientStartTime=function(){return this.cst};AdfUserActivityInfo.prototype.getClientEndTime=function(){return this.cet};
AdfUserActivityInfo.prototype.getResponseTime=function(){return this.rrt};AdfUserActivityInfo.prototype.getEventInfo=function(){return this.eif};AdfUserActivityInfo.prototype.getPprTargets=function(){return this.ppr};AdfUserActivityInfo.prototype.setContextId=function(a){this.cid=a};AdfUserActivityInfo.prototype.setParentContextId=function(a){if(a)this.pid=a};AdfUserActivityInfo.prototype.setClientStartTime=function(a){this.cst=a};
AdfUserActivityInfo.prototype.setClientEndTime=function(a){this.cet=a};AdfUserActivityInfo.prototype.setEventInfo=function(a,b,c,d){if(!this.eif)this.eif={};a&&(this.eif.ety=a);b&&(this.eif.cld=b);c&&(this.eif.cty=c);d&&(this.eif.cdn=d);c=AdfPage.PAGE.findComponent(b);if(c!=null){for(b=a=null;c!=null;){if(c.getComponentType()=="oracle.adf.RichRegion"){a=c.getProperty("viewId");b=c.getProperty("viewName");break}c=c.getParent()}if(a)this.eif.rvd=a,b&&(this.eif.rvn=b)}};
AdfUserActivityInfo.prototype.setPprTargets=function(a){if(a)this.ppr=a};AdfUserActivityInfo.prototype.setResponseTime=function(a){this.rrt=a};AdfUserActivityInfo.prototype.cleanup=function(){this.ppr=this.pid=this.eif=this.cet=this.cst=this.cid=null};AdfUserActivityInfo.cleanInstanceMap=function(){var a=AdfUserActivityInfo._instanceMap;if(a){for(var b in a)a[b].cleanup();AdfUserActivityInfo._instanceMap=null}};
AdfUserActivityInfo._getAsObject=function(a,b){var c=AdfUserActivityInfo.getInstance(b),d=eval("("+a+")");if(d!=null){if(c.getClientStartTime()==null){var e=d.cst;e!=null&&c.setClientStartTime(e)}if(c.getContextId()==null)e=d.cid,e!=null&&c.setContextId(e);if(c.getParentContextId()==null)e=d.pid,e!=null&&e!="undefined"&&c.setParentContextId(e);c.setClientEndTime(d.cet);if(c.getResponseTime()==null)(d=d.rrt)&&d!=="null"&&c.setResponseTime(d)}};
AdfUserActivityInfo._getAsString=function(a){return"{'cid':'"+a.getContextId()+"','pid':'"+a.getParentContextId()+"','cst':'"+a.getClientStartTime()+"','cet':'"+a.getClientEndTime()+"','rrt':'"+a.getResponseTime()+"'}"};AdfUserActivityInfo.prototype._getCurrentTime=function(){return(new Date).getTime().toString()};AdfUserActivityInfo._getPreviousKeyInSequence=function(a){if(a&&(AdfAssert.assertNumber(a),a>0))return AdfUserActivityInfo._PREVIOUS_PREFIX+a.toString();return AdfUserActivityInfo.PREVIOUS};
AdfUserActivityInfo._getSessionStorageProperty=function(a){var b=AdfAgent.AGENT,c=null;try{c=b.getSessionStorageProperty(a)}catch(d){AdfLogger.LOGGER.fine("User activity information may be inaccurate as a failure occurred when attempting to retrieve property from sessionStorage - "+a)}return c};
AdfUserActivityInfo._removeSessionStorageProperty=function(a){var b=AdfAgent.AGENT,c=!0;try{b.removeSessionStorageProperty(a)}catch(d){AdfLogger.LOGGER.fine("User activity information may be inaccurate as a failure occurred when attempting to remove property from sessionStorage - "+a),c=!1}return c};
AdfUserActivityInfo._setSessionStorageProperty=function(a,b){var c=AdfAgent.AGENT,d=!0;try{c.setSessionStorageProperty(a,b)}catch(e){AdfLogger.LOGGER.fine("User activity information may be inaccurate as a failure occurred when attempting to save property-value to sessionStorage "+a+", "+b),d=!1}return d};