AdfUIComponents.createComponentClass("AdfRichPanelFormLayout",{componentType:"oracle.adf.RichPanelFormLayout",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"fieldWidth",type:"String"},{name:"labelWidth",type:"String"},{name:"maxColumns",type:"Number"},{name:"rows",type:"Number","default":2147483647},{name:"labelAlignment",type:"String"}],
superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelFormLayoutPeer");
AdfUIComponents.createComponentClass("AdfRichPanelLabelAndMessage",{componentType:"oracle.adf.RichPanelLabelAndMessage",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"showRequired",type:"Boolean","default":!1},{name:"label",type:"String"},{name:"labelStyle",
type:"String"},{name:"accessKey",type:"String"},{name:"for",type:"String"},{name:"helpTopicId",type:"String"}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelLabelAndMessagePeer");AdfDhtmlPanelLabelAndMessagePeer.InitSubclass=function(){this._CONTENT_ID="content";AdfDhtmlPanelLabelAndMessagePeer._FOCUSABLE_ELEMENTS={INPUT:!0,SELECT:!0,TEXTAREA:!0};AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichPanelLabelAndMessage.LABEL);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichPanelLabelAndMessage.LABEL,AdfRichPanelLabelAndMessage.SHOW_REQUIRED)};
AdfDhtmlPanelLabelAndMessagePeer.prototype.InitDomElement=function(a,b){AdfDhtmlPanelLabelAndMessagePeer.superclass.InitDomElement.call(this,a,b);this._checkForValueChange(a,b)};AdfDhtmlPanelLabelAndMessagePeer.prototype.ComponentLabelChanged=AdfDhtmlEditableValuePeer.__componentLabelChanged;AdfDhtmlPanelLabelAndMessagePeer.prototype.ComponentShowRequiredChanged=AdfDhtmlOutputLabelPeer.__componentShowRequiredChanged;AdfDhtmlPanelLabelAndMessagePeer.prototype.GetInlineEditor=function(){return AdfDhtmlSimpleLabelEditor.getInlineEditor()};
AdfDhtmlPanelLabelAndMessagePeer.prototype.GetComponentLabel=function(a,b){var c=this._getLabelElement(a,b);return c!=null?AdfAgent.AGENT.getTextContent(c):null};AdfDhtmlPanelLabelAndMessagePeer.prototype._getLabelElement=function(a,b){var c=a.getFor(),d=null;c&&(c=AdfRichUIPeer.CreateSubId(c,AdfDhtmlPanelLabelAndMessagePeer._CONTENT_ID),d=AdfDomUtils.getChildElementByAttributeValue(b,"for",c,"LABEL"));return d};
AdfDhtmlPanelLabelAndMessagePeer.prototype._isFocusable=function(a){if(AdfDhtmlPanelLabelAndMessagePeer._FOCUSABLE_ELEMENTS[a.tagName])return!0;return!1};AdfDhtmlPanelLabelAndMessagePeer.prototype._modifyForValue=function(a,b){a.htmlFor=b};
AdfDhtmlPanelLabelAndMessagePeer.prototype._checkForValueChange=function(a,b){var c=this._getLabelElement(a,b);if(c!=null){var d=c.htmlFor;if(d&&(forObject=AdfAgent.AGENT.getElementById(d),forObject==null||!this._isFocusable(forObject))){var e=d.length-9;if(e>0&&(d=d.substring(0,e),e=AdfAgent.AGENT.getElementById(d),e!=null))if(this._isFocusable(e))this._modifyForValue(c,d);else{d=e.childNodes;for(i=0;i<d.length;i++)if(this._isFocusable(d[i])){this._modifyForValue(c,d[i].id);break}}}}};