AdfUIComponents.createComponentClass("AdfRichMenuBar",{componentType:"oracle.adf.RichMenuBar",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"flex",type:"Number","default":0},{name:"stretchId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlMenuBarPeer",!1);AdfDhtmlMenuBarPeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_PRESS_EVENT_TYPE)};
AdfDhtmlMenuBarPeer.prototype.InitDomElement=function(a,b){AdfDhtmlMenuBarPeer.superclass.InitDomElement.call(this,a,b);var c=a.getClientId(),d=AdfRichUIPeer.CreateSubId(c,"eoc"),e=AdfAgent.AGENT;this._isOverflowSupported=(this._overflowContainer=e.getElementById(d))?!0:!1;if(this._isOverflowSupported==!0)d=AdfRichUIPeer.CreateSubId(c,"eoi"),this._overflowIndicator=e.getElementById(d);AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a);c=b.getElementsByTagName("table")[0];this._childContainers=
e.getTableRowCells(e.getTableRow(c,0))};AdfDhtmlMenuBarPeer.prototype.needsChildVisibilityChanges=function(){return!0};AdfDhtmlMenuBarPeer.prototype.needsResizeNotify=function(){return!0};AdfDhtmlMenuBarPeer.prototype.getDescendantComponents=function(a,b){b||(b=[]);AdfDhtmlMenuBarPeer.superclass.getDescendantComponents.call(this,a,b);this._isOverflowSupported==!0&&AdfOverflowSupport.getOverflowChildComponents(a,b);return b};AdfDhtmlMenuBarPeer.prototype.updateScrollIconsState=function(){};
AdfDhtmlMenuBarPeer.prototype.ResizeNotify=function(){var a=this.getDomElement(),b=this.getComponent(),c=b.getClientId();if(this._isOverflowSupported!=!1||b.getStretchId()){this._unStretch();if(this._isOverflowSupported==!0){if(!this._overflowSupport){this._overflowSupport=new AdfOverflowSupport(c,this,"end");a=a.getElementsByTagName("table")[0];b=AdfAgent.AGENT;a=b.getTableRowCells(b.getTableRow(a,0));b=0;for(c=a[0];c;){this._overflowSupport.createStep();this._overflowSupport.addElement(c);if(c=
AdfDomUtils.getFirstChildElement(c)){var d=AdfPage.PAGE.findComponent(c.id);(window.AdfRichSpacer==void 0||!(d instanceof AdfRichSpacer))&&this._overflowSupport.addOverflowElement(this._createOverflowElement(c))}b++;c=a[b]}}this._overflowSupport.handleResize()}this._reStretch()}};AdfDhtmlMenuBarPeer.prototype.ChildVisibilityChanged=function(){AdfPage.PAGE.addPartialTargets(this.getComponent());return!1};
AdfDhtmlMenuBarPeer.prototype.GetPreferredWidth=function(){if(!this._preferredWidth){var a=this.getDomElement().firstChild;this._unStretch();this._overflowSupport&&this._overflowSupport.removeAllItemsFromOverflow();this._preferredWidth=a.offsetWidth;this._reStretch()}return this._preferredWidth};
AdfDhtmlMenuBarPeer.prototype.GetMinimumWidth=function(){if(!this._minimumWidth)if(this._isOverflowSupported==!1)this._minimumWidth=this.GetPreferredWidth();else if(this._childContainers&&this._childContainers.length>0){var a=this._overflowIndicator.style.display;this._overflowIndicator.style.display="block";this._minimumWidth=this._overflowIndicator.offsetWidth;this._overflowIndicator.style.display=a;a=this.GetPreferredWidth();if(this._minimumWidth>a)this._minimumWidth=a}else this._minimumWidth=
0;return this._minimumWidth};AdfDhtmlMenuBarPeer.prototype.HandleComponentKeyDown=function(a){a.isCanceled()||AdfAgent.AGENT.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_DOWN_EVENT_TYPE&&this._handleArrowKeys(a.getKeyCode(),a)};AdfDhtmlMenuBarPeer.prototype.HandleComponentKeyPress=function(a){a.isCanceled()||AdfAgent.AGENT.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_PRESS_EVENT_TYPE&&this._handleArrowKeys(a.getKeyCode(),a)};
AdfDhtmlMenuBarPeer.prototype.HandleComponentKeyUp=function(a){var b=this.getComponent();!a.isCanceled()&&!b.getDisabled()&&AdfDhtmlMenuBarPeer._handleMenuBarItemAccessKeys(b,a)};
AdfDhtmlMenuBarPeer.prototype.ComponentRemoved=function(a){delete this._overflowContainer;delete this._overflowIndicator;delete this._childContainers;this._overflowSupport&&(this._overflowSupport.removeOverflowSupport(),delete this._overflowSupport);AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a);AdfDhtmlMenuBarPeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlMenuBarPeer._handleMenuBarItemAccessKeys=function(a,b){var c=b.getKeyStroke(),d=c.getModifiers();if(!(d&AdfKeyStroke.CTRL_MASK||d&AdfKeyStroke.ALT_MASK||d&AdfKeyStroke.META_MASK)){d&AdfKeyStroke.SHIFT_MASK&&(d>>=AdfKeyStroke.SHIFT_MASK,c=AdfKeyStroke.getKeyStroke(c.getKeyCode(),d));for(var c=c.toMarshalledString().toUpperCase(),d=a.getClientId(),d=AdfAgent.AGENT.getElementById(d).getElementsByTagName("A"),e=d.length,f=0;f<e;f++){var g=d[f];if(g&&g.nodeType==1){var h=g.getAttribute("accessKey");
if(h&&c==h.toUpperCase()){AdfFocusUtils.focusElement(g);b.cancel();break}}}}};AdfDhtmlMenuBarPeer.prototype._handleArrowKeys=function(a,b){var c=b.getNativeEvent(),c=AdfAgent.AGENT.getEventTarget(c);if(!AdfMenuUtils.isInOverflow(c.parentNode))switch(AdfMenuUtils.SubmenuFocusFromMouse=!1,a){case AdfKeyStroke.ARROWLEFT_KEY:this._moveHighlightToPreviousBarItem(b);b.cancel();break;case AdfKeyStroke.ARROWRIGHT_KEY:this._moveHighlightToNextBarItem(b),b.cancel()}};
AdfDhtmlMenuBarPeer.prototype._moveHighlightToPreviousBarItem=function(a){var a=a.getNativeEvent(),a=AdfAgent.AGENT.getEventTarget(a),b=this.getDomElement();AdfFocusUtils.focusPreviousTabStop(a,b)};AdfDhtmlMenuBarPeer.prototype._moveHighlightToNextBarItem=function(a){var a=a.getNativeEvent(),a=AdfAgent.AGENT.getEventTarget(a),b=this.getDomElement();AdfFocusUtils.focusNextTabStop(a,b,!0)};
AdfDhtmlMenuBarPeer.prototype._unStretch=function(){var a=this._getStretchElement();if(a)a.parentNode.style.width=""};AdfDhtmlMenuBarPeer.prototype._reStretch=function(){var a=this._getStretchElement();if(a){var b=AdfAgent.AGENT.getWindowWidth()+"px";a.parentNode.style.width=b}};
AdfDhtmlMenuBarPeer.prototype._createOverflowElement=function(a){var b=a.ownerDocument.createElement("table");b.cellPadding=0;b.cellSpacing=0;b.style.width="100%";var c=b.insertRow(-1).insertCell(-1);c.style.width="100%";c.setAttribute(AdfMenuUtils.OVERFLOW_KEY,"true");a=this._overflowSupport.createSwapPosition(a);c.appendChild(a);return b};
AdfDhtmlMenuBarPeer.prototype._getStretchElement=function(){var a=this.getComponent(),b=a.getStretchId();if(b)if(a=a.findComponent(b))return b=a.getClientId(),AdfAgent.AGENT.getElementById(b);else AdfLogger.LOGGER.warning("Unable to find client component for stretch id "+b);return null};
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlMenuPeer",!1);
AdfDhtmlMenuPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfMenuUtils);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.MOUSE_UP_EVENT_TYPE,AdfUIInputEvent.FOCUS_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_PRESS_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE,AdfUIInputEvent.MOUSE_OUT_EVENT_TYPE);
AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichMenu.DISABLED,AdfRichMenu.TEXT);this._sBarMenus=[];this._sDetachedMenus=[];this._SCROLL_DELTA=3;this._JUMP_SCROLL_DELTA=15;this._OPEN_CLOSE_DELAY=300;var a=AdfKeyStroke.M_KEY,b=AdfKeyStroke.SHIFT_MASK|AdfKeyStroke.CTRL_MASK;this._menuBarKeyStroke=AdfKeyStroke.getKeyStroke(a,b);a=AdfKeyStroke.W_KEY;b=AdfKeyStroke.SHIFT_MASK|AdfKeyStroke.CTRL_MASK;this._focusDetachedMenuKeyStroke=AdfKeyStroke.getKeyStroke(a,b)};
AdfDhtmlMenuPeer.prototype.Init=function(a){a.getParent();AdfDhtmlMenuPeer.superclass.Init.call(this,a);a=AdfPage.PAGE.getLookAndFeel();a=parseInt(a.getSkinProperty("af|menu-tr-visible-items"));this._maxDisplayItems=isNaN(a)?14:a;this._enterKeyDown=this._isDetached=!1};AdfDhtmlMenuPeer.prototype.InitDomElement=function(a,b){if(b.getAttribute(AdfMenuUtils.MENU_DEPTH_KEY)=="1"){var c=a.getClientId();AdfDhtmlMenuPeer._addBarMenu(c)}};
AdfDhtmlMenuPeer.cancelShowing=function(){AdfDhtmlMenuPeer._popupShowingHandle&&(window.clearTimeout(AdfDhtmlMenuPeer._popupShowingHandle),delete AdfDhtmlMenuPeer._popupShowingHandle,delete AdfDhtmlMenuPeer._popupPeerWaitingForShow)};
AdfDhtmlMenuPeer.prototype.show=function(a,b){var c=this.getDomElement(),d=this.getComponent(),e=d.getClientId();AdfDomUtils.addCSSClassName(c,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);!this.isContextMenu()&&this.isRootMenu()&&AdfMenuUtils.setLastOpenedRootMenuId(e);b==null&&(c=a[AdfDhtmlPopupWindow.HINT_FOCUS],b=c!=null?c:this.isContextMenu()?!0:!1);this._reattachMenu();if(this._getLazyState()=="noContent")this._setLazyState("fetching"),e={},e.menuDepth=this._getDepth(),this._lazyFetchPopupHints=a,this._lazyFetchFocusOnFirstElement=
b,(new AdfContentFetchEvent(d,AdfContentFetchEvent.FETCH_EVENT_TYPE,e)).queue(),this._showFetchingDataPopup();else if(this._getLazyState()=="fetching")AdfLogger.LOGGER.info("Currently waiting on menu content fetch: "+d.getClientId());else if(c=this._getMenuElement(),c.style.display=="block")b&&AdfFocusUtils.focusFirstTabStop(c);else{var f=this._createMenuPopupHints(a,b);c.style.display="block";var g=this._elemsInitialized;if(!g)c.style.visibility="hidden";this.showPopup(d,c,f,e);if(!g)this._initElements(d,
e,c),c.style.visibility="",this._elemsInitialized=!0,this._areScrollButtonsDisplayed&&this._moveShadow(!0);if(this._areScrollButtonsDisplayed)this._scrollBoxElement.scrollTop=0,this.updateScrollIconsState();this._isDetachable()&&this._createDetachableWindow()}};AdfDhtmlMenuPeer.prototype.showPopup=function(a,b,c,d){AdfMenuUtils.addOpenMenu(d);AdfDhtmlMenuPeer.superclass.showPopup.call(this,a,b,c,d)};
AdfDhtmlMenuPeer.prototype.hidePopup=function(){var a=this.getComponent(),b=a.getClientId();this._handleHideRequest(a,b);this._isDetached||(AdfDhtmlMenuPeer.superclass.hidePopup.call(this,a,b),this._isDetachable()&&(this._detachableWindow&&this._detachableWindow.destroy(),delete this._detachableWindow))};AdfDhtmlMenuPeer.prototype.cancelPopup=function(){var a=this.getComponent(),b=a.getClientId();this._handleHideRequest(a,b);this._isDetached||AdfDhtmlMenuPeer.superclass.cancelPopup.call(this,a,b)};
AdfDhtmlMenuPeer.prototype.close=function(a,b){var c=this.getComponent();if(this._isDetached){AdfDomUtils.addCSSClassName(this._getMenuElement(),AdfMenuUtils.DETACHED_STYLE_CLASS);if(this._detachedMenuLeft&&this._detachedMenuTop){var d=this._detachableWindow.getElement();d.style.left=this._detachedMenuLeft;d.style.top=this._detachedMenuTop}b||this._deselectElement();d=c.getClientId();AdfDhtmlMenuPeer._removeFromDetachedMenus(d);AdfDhtmlMenuPeer.superclass.hidePopup.call(this,c,d)}else this.isContextMenu()?
c.getParent().hide():(a?this.hidePopup():this._delayPopupHiding(),b||this._deselectElement())};AdfDhtmlMenuPeer.prototype.isDetached=function(){return this._isDetached};AdfDhtmlMenuPeer.prototype.isContextMenu=function(){return this.getComponent().getParent()instanceof AdfRichPopup};AdfDhtmlMenuPeer.prototype.isRootMenu=function(){return this._getDepth()==1};
AdfDhtmlMenuPeer.prototype.updateScrollIconsState=function(){if(this._areScrollButtonsDisplayed){var a=this._scrollBoxElement.scrollTop,b=this._scrollContentElement.offsetHeight-this._scrollBoxElement.offsetHeight;a<=0?(AdfDomUtils.addCSSClassName(this._scrollUpElement,AdfRichUIPeer.DISABLED_STYLECLASS),AdfDomUtils.addCSSClassName(this._scrollUpBackgroundElement,AdfRichUIPeer.DISABLED_STYLECLASS)):(AdfDomUtils.removeCSSClassName(this._scrollUpElement,AdfRichUIPeer.DISABLED_STYLECLASS),AdfDomUtils.removeCSSClassName(this._scrollUpBackgroundElement,
AdfRichUIPeer.DISABLED_STYLECLASS));a>=b?(AdfDomUtils.addCSSClassName(this._scrollDownElement,AdfRichUIPeer.DISABLED_STYLECLASS),AdfDomUtils.addCSSClassName(this._scrollDownBackgroundElement,AdfRichUIPeer.DISABLED_STYLECLASS)):(AdfDomUtils.removeCSSClassName(this._scrollDownElement,AdfRichUIPeer.DISABLED_STYLECLASS),AdfDomUtils.removeCSSClassName(this._scrollDownBackgroundElement,AdfRichUIPeer.DISABLED_STYLECLASS))}};
AdfDhtmlMenuPeer.prototype.ReplaceDomElement=function(a,b){if(this._getLazyState()!="fetching")AdfDhtmlMenuPeer.superclass.ReplaceDomElement.call(this,a,b);else{var c=AdfDomUtils.getFirstChildElement(a);c==null?(AdfLogger.LOGGER.warning("Unexpected element received by AdfDhtmlMenuPeer.prototype.ReplaceDomElement"),AdfDhtmlMenuPeer.superclass.ReplaceDomElement.call(this,a,b)):(this.getDomElement().appendChild(c),AdfAgent.AGENT.elementsAdded(c),this._setLazyState("contentLoaded"),this._hideFetchingDataPopup(),
this.show(this._lazyFetchPopupHints,this._lazyFetchFocusOnFirstElement))}};AdfDhtmlMenuPeer.prototype.PopupClosed=function(a,b){var c=this.getDomElement();AdfMenuUtils.dismiss(c,!0,!1);b.style.display="none";AdfDhtmlMenuPeer.superclass.PopupClosed.call(this,a,b);c.appendChild(b);this.isContextMenu()&&(c=a.getParent(),AdfDhtmlPopupPeer.__handlePopupCanceled(c,b),c.getPeer().PopupClosed(c,null))};
AdfDhtmlMenuPeer.prototype.HandleComponentMouseOut=function(){AdfDhtmlMenuPeer.OldMousePosition=AdfDhtmlMenuPeer.CurrentMousePosition;AdfMenuUtils.unhighlightRootMenuItem();if(this._isSubMenu()&&!this._isMenuVisible()){AdfDhtmlMenuPeer._popupPeerWaitingForShow==this&&AdfDhtmlMenuPeer.cancelShowing();var a=this.getDomElement();AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.DEPRESSED_STYLE_CLASS)}};
AdfDhtmlMenuPeer.prototype.HandleComponentKeyUp=function(a){if(!a.isCanceled()&&!this._isDisabled()){var b=this.getDomElement(),c=a.getKeyCode(),d=this._isSubMenu(),e=this.getComponent();AdfMenuUtils.SubmenuFocusFromMouse=!1;switch(c){case AdfKeyStroke.HOME_KEY:AdfFocusUtils.focusFirstTabStop(b.parentNode);a.cancel();return;case AdfKeyStroke.END_KEY:AdfFocusUtils.focusLastTabStop(b.parentNode);a.cancel();return;case AdfKeyStroke.SPACE_KEY:AdfDomUtils.addCSSClassName(b,AdfMenuUtils.DEPRESSED_STYLE_CLASS);
this.show(null,!0);a.cancel();return;case AdfKeyStroke.ENTER_KEY:this._enterKeyDown&&(AdfDomUtils.addCSSClassName(b,AdfMenuUtils.DEPRESSED_STYLE_CLASS),this.show(null,!0));this._enterKeyDown=!1;a.cancel();return;case AdfKeyStroke.ESC_KEY:if(AdfPage.PAGE.isScreenReaderMode())return;this._isDetached?(this._closeDetachedMenu(),a.cancel()):d?b!=AdfPage.PAGE.getActiveDomElement()&&(this.focus(e),this.close(!0,!0),a.cancel()):this.isContextMenu()?(AdfMenuUtils.closeAllMenus(),b.blur(),this.focus(e),e=e.getParent(),
e.getPeer().hide(e),a.cancel()):AdfMenuUtils.closeAllMenus(!0);return}b=this._isMenuVisible();c=this.isRootMenu();e=a.getSource()==e;if(b&&c||!e)e=this._scrollContentElement||this._getMenuElement(),AdfDhtmlMenuPeer._handleMenuItemAccessKeys(e,a)}};
AdfDhtmlMenuPeer.prototype.HandleComponentKeyDown=function(a){if(!a.isCanceled()&&!this._isDisabled()){var b=a.getKeyCode(),c=AdfAgent.AGENT;b==AdfKeyStroke.ENTER_KEY?(this._enterKeyDown=!0,a.cancel(),a.stopBubbling()):c.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_DOWN_EVENT_TYPE&&this._handleArrowKeys(b,a)}};
AdfDhtmlMenuPeer.prototype.HandleComponentKeyPress=function(a){!a.isCanceled()&&!this._isDisabled()&&AdfAgent.AGENT.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_PRESS_EVENT_TYPE&&this._handleArrowKeys(a.getKeyCode(),a)};AdfDhtmlMenuPeer.prototype.HandleComponentFocus=function(a){!a.isCanceled()&&!this._isDisabled()&&(a.cancel(),this.isRootMenu()?this._handleComponentFocusRootMenu():this._handleComponentFocusSubMenu())};
AdfDhtmlMenuPeer.prototype.HandleComponentMouseOver=function(a){this._cancelHiding();var b=a.getNativeEvent();AdfDhtmlMenuPeer.CurrentMousePosition=AdfAgent.AGENT.getMousePosition(b);AdfMenuUtils.SubmenuFocusFromMouse=this._isSubMenu();if(!a.isCanceled()&&!this._isDisabled()){var c=AdfAgent.AGENT,d=this.getDomElement();c.isEventInElement(b,d)&&(a.cancel(),this.isContextMenu()||(a=this.getComponent(),this._isSubMenu()&&(AdfDomUtils.addCSSClassName(d,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS),AdfMenuUtils.dismiss(d,
!1)),this._isSubMenu()||this._isMenuVisible()?AdfFocusUtils.containsFocus(d)&&this._isSubMenu()?this._handleComponentFocusSubMenu():this.focus(a):AdfMenuUtils.areMenusOpened()?this.focus(a):(b=(b=AdfPage.PAGE.getActiveDomElement())?AdfDomUtils.isAncestor(d.parentNode,b):!1,AdfMenuUtils.highlightRootMenuItem(d),b&&this.focus(a))))}};
AdfDhtmlMenuPeer.prototype.HandleComponentClick=function(a){if(AdfPage.PAGE.isScreenReaderMode()&&!a.isCanceled()&&!(this._isDisabled()||a.getEventPhase()!=AdfBaseEvent.AT_TARGET_PHASE)&&!this._isMenuVisible()){var b=this.getDomElement();AdfDomUtils.addCSSClassName(b,AdfMenuUtils.DEPRESSED_STYLE_CLASS);this.show(null,!0);a.cancel()}};
AdfDhtmlMenuPeer.prototype.HandleComponentMouseDown=function(a){if(!this._isDisabled()&&a.isLeftButtonPressed()){var b=AdfAgent.AGENT,c=a.getNativeEvent(),d=this.getDomElement(),e=this._scrollUpElement&&b.isEventInElement(c,this._scrollUpElement),a=this._scrollDownElement&&b.isEventInElement(c,this._scrollDownElement);if(e||a){if(b.getPlatform()==AdfAgent.IE_PLATFORM&&(b=e?this._scrollUpElement:this._scrollDownElement,b!=AdfPage.PAGE.getActiveDomElement()))b.tabIndex=0,b.focus(),b.tabIndex=-1;this._startScroll(a)}else if(b.isEventInElement(c,
d)){if(this.isRootMenu())AdfMenuUtils.SubmenuFocusFromMouse=!1;b.eatEvent(c);AdfDomUtils.addCSSClassName(d,AdfMenuUtils.DEPRESSED_STYLE_CLASS);this.isContextMenu()||(AdfMenuUtils.areMenusOpened()&&this.isRootMenu()?this.close(!0,!0):this.show(null,!1))}}};
AdfDhtmlMenuPeer.prototype.HandleComponentMouseUp=function(a){var b=AdfAgent.AGENT,c=!1;b.getPlatform()==AdfAgent.IE_PLATFORM&&b.getVersion()>=9?(c=a.getNativeEvent(),c=b.isLeftButton(c)):c=a.isLeftButtonPressed();if(!this._isDisabled()&&c&&(c=a.getNativeEvent(),this._handleElement&&AdfDomUtils.removeCSSClassName(this._handleElement,AdfMenuUtils.DEPRESSED_STYLE_CLASS),a=this._scrollUpElement&&b.isEventInElement(c,this._scrollUpElement),c=this._scrollDownElement&&b.isEventInElement(c,this._scrollDownElement),
a||c))b.getCapabilities()[AdfAgent.CAP_TOUCH_SCREEN]!=AdfAgent.CAP_TOUCH_SCREEN_NONE?this._startScroll(c,!0):this._endScroll()};AdfDhtmlMenuPeer.prototype.HandleComponentBlur=function(){var a=this.getDomElement(),b=!this._isSubMenu(),c=this._isSubMenu()&&!this._isMenuVisible(),d=this._isSubMenu()&&this._isMenuVisible()&&this.isDetached();(b||c||d)&&AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);(this._isDetached||!this._isMenuVisible())&&AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.DEPRESSED_STYLE_CLASS)};
AdfDhtmlMenuPeer.prototype.ComponentRemoved=function(a){var b=a.getClientId();AdfMenuUtils.isMenuOpen(b)?this.hidePopup():this._isDetached&&this._closeDetachedMenu();if(this._isDetachable()){var c=AdfAgent.AGENT,d=this._closeDetachedMenuCallback;d&&c.removeBubbleEventListener(this._closeElement,"click",d);delete this._closeElement;delete this._closeDetachedMenuCallback;(d=this._stopCallback)&&c.removeBubbleEventListener(this._handleElement,"mousedown",d);delete this._handleElement;delete this._stopCallback}this._isSubMenu()||
AdfDhtmlMenuPeer._removeBarMenu(b);delete this._menuElement;delete this._scrollUpElement;delete this._scrollDownElement;delete this._scrollUpBackgroundElement;delete this._scrollDownBackgroundElement;delete this._scrollBoxElement;delete this._scrollContentElement;AdfDhtmlMenuPeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlMenuPeer.prototype.ComponentDisabledChanged=function(a,b,c){c==!0?(AdfDomUtils.addCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),b.setAttribute("disabled",!0),b.removeAttribute("tabIndex")):(AdfDomUtils.removeCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),b.removeAttribute("disabled"),b.setAttribute("tabIndex","0"))};
AdfDhtmlMenuPeer.prototype.ComponentTextChanged=function(a,b,c,d){if(d!=null&&(b=AdfDomUtils.getFirstDescendentElement(b,"A")))return AdfDomUtils.handleTextChangeWithAccessKey(a,b,c);return!1};AdfDhtmlMenuPeer.prototype.GetInlineEditor=function(){return AdfDhtmlSimpleTextEditor.getAnchorInlineEditor()};AdfDhtmlMenuPeer.prototype.setVisibleItems=function(a){this._maxDisplayItems=a};
AdfDhtmlMenuPeer._redetachMenu=function(){var a=AdfDhtmlMenuPeer._reattachedMenuId;if(a!=null){if(a=AdfPage.PAGE.findComponent(a))if((a=a.getPeer())&&a instanceof AdfDhtmlMenuPeer&&a._detachableWindow){var b=a._detachableWindow.getElement();b.style.left=a._detachedMenuLeft;b.style.top=a._detachedMenuTop;a._makeDetached()}AdfDhtmlMenuPeer._reattachedMenuId=null}};
AdfDhtmlMenuPeer._focusNextDetachedMenuKeyHandler=function(){if(!AdfCollections.isEmpty(AdfDhtmlMenuPeer._sDetachedMenus)){var a,b=AdfDhtmlMenuPeer._lastSelectedDetachableMenuId;b==null?a=AdfDhtmlMenuPeer._sDetachedMenus[0]:(a=AdfDhtmlMenuPeer._sDetachedMenus.length,a==1?a=AdfDhtmlMenuPeer._sDetachedMenus[0]:(b=AdfCollections.indexOf(AdfDhtmlMenuPeer._sDetachedMenus,b),a=b>=a-1?AdfDhtmlMenuPeer._sDetachedMenus[0]:AdfDhtmlMenuPeer._sDetachedMenus[b+1]));(b=AdfPage.PAGE.findComponent(a))?(b=b.getPeer()._getMenuElement().getElementsByTagName("tbody")[0],
AdfFocusUtils.focusFirstTabStop(b),AdfDhtmlMenuPeer._lastSelectedDetachableMenuId=a):(AdfDhtmlMenuPeer._removeFromDetachedMenus(a),AdfDhtmlMenuPeer._focusNextDetachedMenuKeyHandler())}};
AdfDhtmlMenuPeer._addToDetachedMenus=function(a){var b=AdfAgent.AGENT;if(AdfCollections.isEmpty(AdfDhtmlMenuPeer._sDetachedMenus)){if(b.getPlatform()==AdfAgent.GECKO_PLATFORM){var c=AdfPage.PAGE.getDomDocument();b.addBubbleEventListener(c,"keypress",AdfDhtmlMenuPeer._cancelKeyPress)}AdfPage.PAGE.registerKeyStroke(AdfDhtmlMenuPeer._focusDetachedMenuKeyStroke,AdfDhtmlMenuPeer._focusNextDetachedMenuKeyHandler)}if(AdfCollections.indexOf(AdfDhtmlMenuPeer._sDetachedMenus,a)<0)AdfDhtmlMenuPeer._lastSelectedDetachableMenuId=
a,AdfDhtmlMenuPeer._sDetachedMenus.push(a)};
AdfDhtmlMenuPeer._removeFromDetachedMenus=function(a){AdfCollections.removeArrayValue(AdfDhtmlMenuPeer._sDetachedMenus,a);var b=AdfCollections.isEmpty(AdfDhtmlMenuPeer._sDetachedMenus);if(b||a==AdfDhtmlMenuPeer._lastSelectedDetachableMenuId)AdfDhtmlMenuPeer._lastSelectedDetachableMenuId=null;if(b)AdfPage.PAGE.unregisterKeyStroke(AdfDhtmlMenuPeer._focusDetachedMenuKeyStroke),a=AdfAgent.AGENT,a.getPlatform()==AdfAgent.GECKO_PLATFORM&&(b=AdfPage.PAGE.getDomDocument(),a.removeBubbleEventListener(b,"keypress",
AdfDhtmlMenuPeer._cancelKeyPress))};AdfDhtmlMenuPeer._cancelKeyPress=function(a){var b=AdfAgent.AGENT.getKeyCode(a);a.ctrlKey&&a.shiftKey&&b==AdfKeyStroke.W_KEY&&AdfAgent.AGENT.eatEvent(a)};AdfDhtmlMenuPeer._menuBarKeyHandler=function(){AdfDhtmlMenuPeer._focusFirstElementInMenuBar()};AdfDhtmlMenuPeer._addBarMenu=function(a){var b=AdfDhtmlMenuPeer._sBarMenus;b.length==0&&AdfPage.PAGE.registerKeyStroke(AdfDhtmlMenuPeer._menuBarKeyStroke,AdfDhtmlMenuPeer._menuBarKeyHandler);b.push(a)};
AdfDhtmlMenuPeer._removeBarMenu=function(a){var b=AdfDhtmlMenuPeer._sBarMenus;AdfCollections.removeArrayValue(b,a);b.length==0&&AdfPage.PAGE.unregisterKeyStroke(AdfDhtmlMenuPeer._menuBarKeyStroke)};AdfDhtmlMenuPeer._focusFirstElementInMenuBar=function(){var a=AdfDhtmlMenuPeer._sBarMenus;AdfAssert.assert(a.length>1);var a=AdfPage.PAGE.findComponent(a[0]),b=a.getParent();AdfAssert.assert(!(b instanceof AdfRichMenu));a=a.getPeer()._getParentId();a=AdfAgent.AGENT.getElementById(a);AdfFocusUtils.focusFirstTabStop(a)};
AdfDhtmlMenuPeer._handleMenuItemAccessKeys=function(a,b){var c=b.getKeyStroke(),d=c.getModifiers();if(!(d&AdfKeyStroke.CTRL_MASK||d&AdfKeyStroke.ALT_MASK||d&AdfKeyStroke.META_MASK)){d&AdfKeyStroke.SHIFT_MASK&&(d>>=AdfKeyStroke.SHIFT_MASK,c=AdfKeyStroke.getKeyStroke(c.getKeyCode(),d));for(var c=c.toMarshalledString().toUpperCase(),d=a.getElementsByTagName("tr"),e=d.length,f=0;f<e;f++){var g=d[f];if(g&&g.nodeType==1){var h=g.getAttribute("accessKey");if(h&&c==h.toUpperCase()){AdfFocusUtils.focusElement(g);
b.cancel();break}}}}};
AdfDhtmlMenuPeer.prototype._handleArrowKeys=function(a,b){var c=b.getNativeEvent();if(c.ctrlKey){if(this._detachableWindow){var d=AdfAgent.AGENT.getPlatform()==AdfAgent.IE_PLATFORM?a==187:a==61;if(c.altKey&&d)this._moveDetachable(0,0),b.cancel();else{c=!0;switch(a){case AdfKeyStroke.ARROWUP_KEY:this._moveDetachable(0,-20);break;case AdfKeyStroke.ARROWDOWN_KEY:this._moveDetachable(0,20);break;case AdfKeyStroke.ARROWLEFT_KEY:this._moveDetachable(-20,0);break;case AdfKeyStroke.ARROWRIGHT_KEY:this._moveDetachable(20,0);
break;default:c=!1}c&&b.cancel()}}}else AdfMenuUtils.SubmenuFocusFromMouse=!1,c=this.getDomElement(),d=this.getComponent(),AdfMenuUtils.handleArrowKeys(b,c,d)};AdfDhtmlMenuPeer.prototype._onHandleClick=function(a){AdfAgent.AGENT.eatEvent(a);AdfDomUtils.addCSSClassName(this._handleElement,AdfMenuUtils.DEPRESSED_STYLE_CLASS)};
AdfDhtmlMenuPeer.prototype._initElements=function(a,b){var c=AdfAgent.AGENT;if(this._isDetachable()){var d=AdfRichUIPeer.CreateSubId(b,"close");this._closeElement=c.getElementById(d);this._closeDetachedMenuCallback=this.createCallback(this._closeDetachedMenu);c.addBubbleEventListener(this._closeElement,"click",this._closeDetachedMenuCallback);d=AdfRichUIPeer.CreateSubId(b,"handle");this._handleElement=c.getElementById(d);this._stopCallback=this.createCallback(this._onHandleClick);c.addBubbleEventListener(this._handleElement,
"mousedown",this._stopCallback)}if(AdfPage.PAGE.isScreenReaderMode())this._areScrollButtonsDisplayed=!1;else{d=AdfRichUIPeer.CreateSubId(b,"ScrollContent");this._scrollContentElement=c.getElementById(d);var e=this._scrollContentElement.rows;if(e.length<this._maxDisplayItems)this._areScrollButtonsDisplayed=!1;else{d=[];for(i=0;i<e.length;i++){var f=e[i];f.style.display!="none"&&d.push(f)}if(this._areScrollButtonsDisplayed=d.length>this._maxDisplayItems)e=AdfRichUIPeer.CreateSubId(b,"ScrollUp"),this._scrollUpElement=
c.getElementById(e),this._scrollUpElement.style.display="block",e=AdfRichUIPeer.CreateSubId(b,"sUpBg"),this._scrollUpBackgroundElement=c.getElementById(e),e=AdfRichUIPeer.CreateSubId(b,"ScrollDown"),this._scrollDownElement=c.getElementById(e),this._scrollDownElement.style.display="block",e=AdfRichUIPeer.CreateSubId(b,"sDwnBg"),this._scrollDownBackgroundElement=c.getElementById(e),e=AdfRichUIPeer.CreateSubId(b,"ScrollBox"),this._scrollBoxElement=c.getElementById(e),this._scrollBoxElement.style.height=
d[this._maxDisplayItems].offsetTop-d[0].offsetTop+"px"}}};
AdfDhtmlMenuPeer.prototype._createMenuPopupHints=function(a,b){var c={},d=this.getDomElement(),e=AdfPage.PAGE,f=this.getComponent();c[AdfDhtmlPopupWindow.HINT_TYPE]=AdfDhtmlPopupWindow.HINT_TYPE_MENU;c[AdfDhtmlPopupWindow.HINT_AUTODISMISS]=AdfDhtmlPopupWindow.HINT_AUTODISMISS_MENU;c[AdfDhtmlPopupWindow.HINT_ALIGN_ELEMENT]=d;c[AdfDhtmlPopupWindow.HINT_FOCUS]=b?!0:!1;c[AdfDhtmlPopupWindow.HINT_TITLE]=f.getText();c[AdfDhtmlPopupWindow.HINT_ANIMATE]=!0;c[AdfDhtmlPopupWindow.HINT_CLOSE_ON_ESCAPE]=e.isScreenReaderMode()?
!0:!1;c[AdfDhtmlPopupWindow.HINT_CLOSE_HANDLER]=this.createCallback(this._clearHighlight);if(a==null||a[AdfDhtmlPopupWindow.HINT_MOUSEPOSITION]==null)c[AdfRichPopup.HINT_ALIGN]=this._isSubMenu()||AdfMenuUtils.isInOverflow(d)?AdfRichPopup.ALIGN_END_BEFORE:AdfRichPopup.ALIGN_AFTER_START;AdfCollections.copyInto(c,a);return c};
AdfDhtmlMenuPeer.prototype._showFetchingDataPopup=function(){var a=AdfAgent.AGENT,b=this.getComponent(),c=this.getDomElement().getAttribute("id"),c=AdfRichUIPeer.CreateSubId(c,"lazy-fetch-message"),a=a.getElementById(c),a=AdfDomUtils.getFirstChildElement(a),d=this._createMenuPopupHints(null,!1);d[AdfDhtmlPopupWindow.HINT_TYPE]=AdfDhtmlPopupWindow.HINT_TYPE_INLINESELECTOR;AdfDomUtils.setVisible(a,!0);AdfDhtmlMenuPeer.superclass.showPopup.call(this,b,a,d,c)};
AdfDhtmlMenuPeer.prototype._hideFetchingDataPopup=function(){var a=this.getComponent(),b=this.getDomElement().getAttribute("id"),b=AdfRichUIPeer.CreateSubId(b,"lazy-fetch-message");AdfDhtmlMenuPeer.superclass.hidePopup.call(this,a,b)};
AdfDhtmlMenuPeer.prototype._reattachMenu=function(){if(this._isDetached){var a=this._calculateReattachPosition(),b=this.getComponent().getClientId();AdfDhtmlMenuPeer._reattachedMenuId=b;AdfDomUtils.removeCSSClassName(this._getMenuElement(),AdfMenuUtils.DETACHED_STYLE_CLASS);var c=this._getMenuPopup();c&&c.autoSize();AdfMenuUtils.addOpenMenu(b);AdfDhtmlMenuPeer._removeFromDetachedMenus(b);this._snapDetachedMenu(a);this._isDetached=!1}};
AdfDhtmlMenuPeer.prototype._calculateReattachPosition=function(){var a=AdfPage.PAGE.getPositionManager(),b=this.getDomElement(),c=this._getMenuElement(),d=AdfRichPopup.ALIGN_END_BEFORE,e=c.clientHeight-4,c=c.clientWidth+AdfDhtmlShadowDecorator.getShadowSize();return a.calculatePlacementPosition(e,c,d,b,null)};
AdfDhtmlMenuPeer.prototype._contains=function(a){var b=this.getDomElement(),b=AdfDomUtils.isAncestorOrSelf(b,a);if(this._getLazyState()=="noContent")return b;a=AdfDomUtils.isAncestor(this._getMenuElement(),a);return b||a};AdfDhtmlMenuPeer.prototype._getParentId=function(){if(!this._parentId){var a=this.getDomElement().parentNode;do var b=a.getAttribute("id"),a=a.parentNode;while(!b&&a);if(b)this._parentId=b}return this._parentId};
AdfDhtmlMenuPeer.prototype._getDepth=function(){if(!this._depth){var a=this.getDomElement();this._depth=parseInt(a.getAttribute(AdfMenuUtils.MENU_DEPTH_KEY))}return this._depth};AdfDhtmlMenuPeer.prototype._isSubMenu=function(){return this._getDepth()>1};AdfDhtmlMenuPeer.prototype._isDisabled=function(){var a=this.getDomElement();return a.disabled||AdfDomUtils.containsCSSClassName(a,AdfRichUIPeer.DISABLED_STYLECLASS)};
AdfDhtmlMenuPeer.prototype._isDetachable=function(){if(AdfPage.PAGE.isScreenReaderMode())return!1;return this.getComponent().getDetachable()};
AdfDhtmlMenuPeer.prototype._handleComponentFocusRootMenu=function(){var a=AdfMenuUtils.areMenusOpened(),b=AdfMenuUtils.GetLastOpenedRootMenuId();if(a&&b&&(b=AdfPage.PAGE.findComponent(b).getPeer()._getParentId(),this._getParentId()!=b))return;var b=this.getDomElement(),c=AdfPage.PAGE;c.setLastFocusedElement(b);a&&!c.isScreenReaderMode()?(AdfMenuUtils.dismiss(b,!0),AdfDomUtils.addCSSClassName(b,AdfMenuUtils.DEPRESSED_STYLE_CLASS),AdfMenuUtils.SubmenuFocusFromMouse=!1,this.show(null,!1)):AdfMenuUtils.highlightRootMenuItem(b)};
AdfDhtmlMenuPeer.prototype._handleComponentFocusSubMenu=function(){var a=this.getDomElement();AdfPage.PAGE.setLastFocusedElement(a);AdfDomUtils.addCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);var b=AdfMenuUtils.SubmenuFocusFromMouse;AdfMenuUtils.dismiss(a,!b);b&&this._delayShow()};
AdfDhtmlMenuPeer.prototype._handleHideRequest=function(a,b){AdfDhtmlMenuPeer._redetachMenu();if(!this._isDetached){if(this.isRootMenu()){var c=this.getDomElement();AdfDomUtils.removeCSSClassName(c,AdfMenuUtils.DEPRESSED_STYLE_CLASS);AdfDomUtils.removeCSSClassName(c,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS)}AdfDhtmlMenuPeer._popupPeerWaitingForShow&&this._contains(AdfDhtmlMenuPeer._popupPeerWaitingForShow.getDomElement())&&AdfDhtmlMenuPeer.cancelShowing();AdfMenuUtils.removeOpenMenu(b)}};
AdfDhtmlMenuPeer.prototype._createDetachableWindow=function(){if(this._isMenuVisible()&&this._detachableWindow==null)this._detachableWindow=new AdfRepositionable(this._getMenuPopup(),this._handleElement),this._detachableWindow.setDragStartHandler(this.createCallback(this._dragStart)),this._detachableWindow.setDragEndHandler(this.createCallback(this._dragEnd))};
AdfDhtmlMenuPeer.prototype._dragStart=function(){this._deselectElement();var a=this._getMenuPopup();a!=null&&a.getShadowAnchor()!=null&&(a=a.getShadowAnchor(),AdfDhtmlShadowDecorator.hasShadowDecorator(a)&&AdfDhtmlShadowDecorator.showShadowDecorator(a,!1));a=this.getDomElement();AdfMenuUtils.dismiss(a,!0);a=this._detachableWindow.getElement();this._detachedMenuLeft=a.style.left;this._detachedMenuTop=a.style.top};
AdfDhtmlMenuPeer.prototype._dragEnd=function(){this._makeDetached();var a=this._getMenuPopup();if(a){a.setAlignElement(null);var b={y:a.getTop(),x:a.getLeft()};a.setAlignPosition(b);a.activate()}AdfMenuUtils.closeAllMenus()};AdfDhtmlMenuPeer.prototype._delayPopupHiding=function(a){this._popupHidingHandle&&this._cancelHiding();this._popupHidingHandle=AdfPage.PAGE.getDomWindow().setTimeout(this.createCallback(this._delayPopupHidingCallback),AdfDhtmlMenuPeer._OPEN_CLOSE_DELAY-a)};
AdfDhtmlMenuPeer.prototype._delayPopupHidingCallback=function(){var a=this.getComponent();this.isPopupVisible(a,a.getClientId())&&this.hidePopup()};AdfDhtmlMenuPeer.prototype._delayShow=function(){AdfDhtmlMenuPeer.cancelShowing();AdfDhtmlMenuPeer._popupShowingHandle=AdfPage.PAGE.getDomWindow().setTimeout(this.createCallback(this._delayShowCallback),AdfDhtmlMenuPeer._OPEN_CLOSE_DELAY);AdfDhtmlMenuPeer._popupPeerWaitingForShow=this};
AdfDhtmlMenuPeer.prototype._delayShowCallback=function(){var a=this.getComponent();this.isPopupVisible(a,a.getClientId())?this._reattachMenu():(delete AdfDhtmlMenuPeer._popupPeerWaitingForShow,delete AdfDhtmlMenuPeer._popupShowingHandle,AdfMenuUtils.SubmenuFocusFromMouse=!1,this.show(null,!1))};
AdfDhtmlMenuPeer.prototype._cancelHiding=function(){if(this._popupHidingHandle){window.clearTimeout(this._popupHidingHandle);delete this._popupHidingHandle;var a=AdfDhtmlMenuPeer._popupPeerWaitingForShow;a&&a._getDepth()<=this._getDepth()&&AdfDhtmlMenuPeer.cancelShowing()}};
AdfDhtmlMenuPeer.prototype._makeDetached=function(){AdfDomUtils.removeCSSClassName(this._handleElement,AdfMenuUtils.DEPRESSED_STYLE_CLASS);var a=this._detachableWindow.getElement();this._isDetached=!0;this._detachedMenuLeft=a.style.left;this._detachedMenuTop=a.style.top;AdfDomUtils.addCSSClassName(this._getMenuElement(),AdfMenuUtils.DETACHED_STYLE_CLASS);(a=this._getMenuPopup())&&a.autoSize();a=this.getComponent().getClientId();AdfMenuUtils.removeOpenMenu(a);AdfDhtmlMenuPeer._addToDetachedMenus(a);
AdfMenuUtils.dismiss(this.getDomElement().parentNode,!0,!0)};AdfDhtmlMenuPeer.prototype._deselectElement=function(){var a=this.getDomElement();AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.DEPRESSED_STYLE_CLASS)};
AdfDhtmlMenuPeer.prototype._closeDetachedMenu=function(){var a=this.getComponent(),b=a.getClientId();AdfDomUtils.removeCSSClassName(this._getMenuElement(),AdfMenuUtils.DETACHED_STYLE_CLASS);this._isDetached=!1;var c=this.getDomElement();AdfDomUtils.removeCSSClassName(c,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);AdfDhtmlMenuPeer._removeFromDetachedMenus(b);this._detachableWindow&&this._detachableWindow.destroy();delete this._detachableWindow;if(b==AdfDhtmlMenuPeer._reattachedMenuId)AdfDhtmlMenuPeer._reattachedMenuId=
null;AdfDhtmlMenuPeer.superclass.hidePopup.call(this,a,b);AdfMenuUtils.closeAllMenus();AdfMenuUtils.restoreFocusToLastOpenedRootMenu()};AdfDhtmlMenuPeer.prototype._moveDetachable=function(a,b){this._dragStart();var c=this._detachableWindow.getElement();c.style.left=c.offsetLeft+a+"px";c.style.top=c.offsetTop+b+"px";this._dragEnd()};
AdfDhtmlMenuPeer.prototype._snapDetachedMenu=function(a){var b=this._detachableWindow.getElement(),c=a.y,a=a.x;AdfPage.PAGE.isAnimationEnabled()?(this._showShadow(!1),AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,300,[{element:b,properties:{left:a,top:c}}],null,function(a){a[0]._moveShadow(!0)},[this])):(b.style.left=a+"px",b.style.top=c+"px",this._moveShadow(!0))};
AdfDhtmlMenuPeer.prototype._getShadowAnchor=function(){var a=this._getMenuPopup();if(a!=null&&a.getShadowAnchor()!=null)return a.getShadowAnchor()};AdfDhtmlMenuPeer.prototype._showShadow=function(a){var b=this._getShadowAnchor();AdfDhtmlShadowDecorator.hasShadowDecorator(b)&&AdfDhtmlShadowDecorator.showShadowDecorator(b,a)};
AdfDhtmlMenuPeer.prototype._moveShadow=function(a){var b=this._getShadowAnchor();b!=null&&AdfDhtmlShadowDecorator.hasShadowDecorator(b)&&(AdfDhtmlShadowDecorator.moveShadowDecorator(b),AdfDhtmlShadowDecorator.showShadowDecorator(b,a))};
AdfDhtmlMenuPeer.prototype._startScroll=function(a,b){this._scrollDelta=AdfDhtmlMenuPeer._SCROLL_DELTA;if(b)this._scrollDelta=AdfDhtmlMenuPeer._JUMP_SCROLL_DELTA;a||(this._scrollDelta*=-1);if(b)this._scroll();else{var c=this.createCallback(this._scroll);this._scrollTimer=setInterval(c,1)}};
AdfDhtmlMenuPeer.prototype._endScroll=function(){this._scrollTimer&&clearInterval(this._scrollTimer);this._scrollTimer=null;var a=this._getMenuItemHeight(),b=this._scrollBoxElement.scrollTop%a;b!=0&&(this._scrollDelta<0?this._scrollBoxElement.scrollTop-=b:this._scrollDelta>0&&(this._scrollBoxElement.scrollTop+=a-b))};
AdfDhtmlMenuPeer.prototype._getMenuItemHeight=function(){if(this._menuItemHeight!=null)return this._menuItemHeight;var a=AdfDomUtils.getFirstChildElement(this._scrollContentElement),a=AdfDomUtils.getFirstChildElement(a);this._menuItemHeight=a.clientHeight;if(this._menuItemHeight==0)this._menuItemHeight=a.scrollHeight;return this._menuItemHeight};
AdfDhtmlMenuPeer.prototype._scroll=function(){this._scrollBoxElement.scrollTop+=this._scrollDelta;var a=this._scrollBoxElement.scrollTop,b=this._scrollContentElement.offsetHeight-this._scrollBoxElement.offsetHeight;(a<=0||a>=b)&&this._endScroll();this.updateScrollIconsState()};AdfDhtmlMenuPeer.prototype._getMenuElement=function(){if(this._menuElement===void 0){var a=this.getDomElement().getAttribute("id"),a=AdfRichUIPeer.CreateSubId(a,"menu");this._menuElement=AdfAgent.AGENT.getElementById(a)}return this._menuElement};
AdfDhtmlMenuPeer.prototype._getMenuPopup=function(){var a=this.getComponent(),b=a.getClientId();return this.getPopupWindow(a,b)};AdfDhtmlMenuPeer.prototype._isMenuVisible=function(){return this._getMenuPopup()?!0:!1};AdfDhtmlMenuPeer.prototype._clearHighlight=function(){if(this._getLazyState()=="contentPresent")for(var a=(this._scrollContentElement||this._getMenuElement()).childNodes,b=a.length,c=0;c<b;c++){var d=a[c];d&&d.nodeType==1&&AdfDomUtils.removeCSSClassName(d,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS)}};
AdfDhtmlMenuPeer.prototype._getLazyState=function(){if(this._lazyState==null)this._lazyState=this.isContextMenu()?"contentLoaded":"lazy"==this.getComponent().getContentDelivery()?"noContent":"contentLoaded";return this._lazyState};AdfDhtmlMenuPeer.prototype._setLazyState=function(a){this._lazyState=a};
function AdfMenuUtils(){}AdfObject.createSubclass(AdfMenuUtils);AdfMenuUtils.InitClass=function(){this.SELECTED_STYLE_CLASS="p_AFSelected";this.HIGHLIGHTED_STYLE_CLASS="p_AFHighlighted";this.DEPRESSED_STYLE_CLASS="p_AFDepressed";this.DETACHED_STYLE_CLASS="p_AFDetached";this.MENU_DEPTH_KEY="_afrDth";this.OVERFLOW_KEY="_afrOflw";this.AFR_TARGETROWCURRENCY="_afrTargetRowCurrency";this.AFR_TARGETCOMPONENTID="_afrTargetComponentId";this._sOpenedMenus=[]};
AdfMenuUtils.isOnMenuBar=function(a){return(a=a.getParent())&&a instanceof AdfRichMenuBar};AdfMenuUtils.isInOverflow=function(a){return a.parentNode.getAttribute(AdfMenuUtils.OVERFLOW_KEY)=="true"};AdfMenuUtils.isInMenu=function(a){return(a=a.getParent())&&a instanceof AdfRichMenu};AdfMenuUtils.closeAllMenus=function(a){var b=this._sOpenedMenus;if(b&&b.length>0)for(var c=b.length-1;c>=0;c--){var d=AdfPage.PAGE.findComponent(b[c]);d?d.getPeer().hidePopup():delete b[c]}a&&AdfMenuUtils.restoreFocusToLastOpenedRootMenu()};
AdfMenuUtils.GetLastOpenedRootMenuId=function(){return AdfMenuUtils._sLastOpenedRootMenuId};AdfMenuUtils.setLastOpenedRootMenuId=function(a){AdfMenuUtils._sLastOpenedRootMenuId=a};AdfMenuUtils.restoreFocusToLastOpenedRootMenu=function(){var a=AdfMenuUtils._sLastOpenedRootMenuId;if(a&&(a=AdfPage.PAGE.findComponent(a),a!=null)){var b=a.getPeer(),c=b.getDomElement();b.focus(a);AdfMenuUtils.highlightRootMenuItem(c)}};
AdfMenuUtils.highlightRootMenuItem=function(a){var b=a.getAttribute("id"),c=AdfMenuUtils._highlightedRootMenuItemId;c&&c!=b&&AdfMenuUtils.unhighlightRootMenuItem();AdfDomUtils.addCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);AdfMenuUtils._highlightedRootMenuItemId=b};
AdfMenuUtils.unhighlightRootMenuItem=function(){var a=AdfAgent.AGENT.getElementById(AdfMenuUtils._highlightedRootMenuItemId);a&&AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);AdfMenuUtils._highlightedRootMenuItemId=null};AdfMenuUtils.dismiss=function(a,b,c){var d=this._sOpenedMenus;if(d&&d.length!=0)for(var e=d.length-1;e>=0;e--){var f=AdfPage.PAGE.findComponent(d[e]);if(f){f=f.getPeer();if(f._contains(a))break;c?d.pop():(f._deselectElement(),b?f.hidePopup():f._delayPopupHiding(e))}else delete d[e]}};
AdfMenuUtils.isImmediate=function(a){var b=a==1,c=AdfDhtmlMenuPeer.OldMousePosition,d=AdfDhtmlMenuPeer.CurrentMousePosition;if(!b&&d&&c&&(b=d.y-c.y,c=d.x-c.x,AdfPage.PAGE.getLocaleContext().isRightToLeft()&&(c=-c),b=b<0||c<0,!b)){if(c=AdfPage.PAGE.findComponent(AdfPage.PAGE.getLastFocusedElement().id))d=c.getPeer(),c instanceof AdfRichMenu&&(b=(b=!d._isSubMenu())||d._getDepth()<a);b=b||this._sOpenedMenus.length<a}return b};
AdfMenuUtils.areMenusOpened=function(){return this._sOpenedMenus&&this._sOpenedMenus.length>0};AdfMenuUtils.isMenuOpen=function(a){return AdfCollections.indexOf(this._sOpenedMenus,a)>=0};AdfMenuUtils.addOpenMenu=function(a){this.isMenuOpen(a)||this._sOpenedMenus.push(a)};AdfMenuUtils.removeOpenMenu=function(a){AdfCollections.removeArrayValue(this._sOpenedMenus,a)};
AdfMenuUtils.getContextMenuItemTargetAttrs=function(a){for(var b=null,a=a.getParent();a!=null&&(a instanceof AdfRichMenu||a instanceof AdfRichPopup);){var c;if((c=a[this.AFR_TARGETROWCURRENCY])!=null){b={targetRowCurrency:c,targetComponentId:a[this.AFR_TARGETCOMPONENTID]};break}a=a.getParent()}return b};
AdfMenuUtils.setContextMenuItemTargetAttrs=function(a,b){var c=a.getPropertyKeys(),d=this.AFR_TARGETROWCURRENCY,e=this.AFR_TARGETCOMPONENTID;c[d]==null&&(c[d]=c[e]={type:"String"},AdfRichUIPeer.addSuppressedPPRAttributes(this,d,e));a.setProperty(e,null);a.setProperty(d,null);a.setProperty(e,b.targetComponentId);a.setProperty(d,b.targetRowCurrency)};
AdfMenuUtils.handleArrowKeys=function(a,b,c){a.getNativeEvent().ctrlKey||(this.isInOverflow(b)?this._handleInMenuBarOverflowArrowKeys(a,b,c):this.isOnMenuBar(c)?this._handleInMenuBarArrowKeys(a,b,c):this.isInMenu(c)&&this._handleInMenuArrowKeys(a,b,c))};
AdfMenuUtils._handleInMenuBarArrowKeys=function(a,b,c){var d=AdfAgent.AGENT,e=a.getNativeEvent();switch(d.getKeyCode(e)){case AdfKeyStroke.ARROWDOWN_KEY:c instanceof AdfRichMenu&&(AdfDomUtils.addCSSClassName(b,this.DEPRESSED_STYLE_CLASS),c.getPeer().show(null,!0),a.cancel())}};AdfMenuUtils._handleInMenuBarOverflowArrowKeys=function(a,b,c){var b=AdfAgent.AGENT,d=a.getNativeEvent();switch(b.getKeyCode(d)){case AdfKeyStroke.ARROWRIGHT_KEY:c instanceof AdfRichMenu&&c.getPeer().show(null,!0),a.cancel()}};
AdfMenuUtils._handleInMenuArrowKeys=function(a,b,c){var d=AdfAgent.AGENT,e=a.getNativeEvent(),d=d.getKeyCode(e),e=c.getParent();switch(d){case AdfKeyStroke.ARROWUP_KEY:AdfMenuUtils._moveHighlightToPreviousMenuItem(b,c);a.cancel();e.getPeer().updateScrollIconsState();break;case AdfKeyStroke.ARROWDOWN_KEY:AdfMenuUtils._moveHighlightToNextMenuItem(b,c);a.cancel();e.getPeer().updateScrollIconsState();break;case AdfKeyStroke.ARROWLEFT_KEY:this._handleMenuItemLeftArrowKey(e);a.cancel();break;case AdfKeyStroke.ARROWRIGHT_KEY:c instanceof
AdfRichMenu?c.getPeer().show(null,!0):this._handleMenuItemRightArrowKey(e),a.cancel()}};AdfMenuUtils._handleMenuItemLeftArrowKey=function(a){var b=a.getPeer();this.isOnMenuBar(a)?(b.focus(a),b.close(!0,!0),a=a.getParent().getPeer().getDomElement(),b=b.getDomElement(),AdfFocusUtils.focusPreviousTabStop(b,a)):!b.isDetached()&&!b.isContextMenu()&&(b.focus(a),b.close(!0,!0))};
AdfMenuUtils._handleMenuItemRightArrowKey=function(a){if(a instanceof AdfRichMenu){var b=a.getPeer();!b.isDetached()&&!b.isContextMenu()&&(this.isOnMenuBar(a)?(b.focus(a),b.close(!0,!0),a=a.getParent().getPeer().getDomElement(),b=b.getDomElement(),AdfFocusUtils.focusNextTabStop(b,a,!0)):this._handleMenuItemRightArrowKey(a.getParent()))}};AdfMenuUtils._moveHighlightToPreviousMenuItem=function(a,b){AdfFocusUtils.focusPreviousTabStop(a,a.parentNode);var c=b.getParent();c&&c instanceof AdfRichMenu&&c.getPeer().updateScrollIconsState()};
AdfMenuUtils._moveHighlightToNextMenuItem=function(a,b){AdfFocusUtils.focusNextTabStop(a,a.parentNode,!0);var c=b.getParent();c&&c instanceof AdfRichMenu&&c.getPeer().updateScrollIconsState()};
AdfUIComponents.createComponentClass("AdfRichCommandMenuItem",{componentType:"oracle.adf.RichCommandMenuItem",propertyKeys:[{name:"text",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"accessKey",type:"String"},{name:"partialSubmit",type:"Boolean","default":!0},{name:"icon",type:"String"},{name:"selected",type:"Boolean","default":!1},{name:"selectedText",type:"String"},{name:"type",type:"String"},"accelerator",{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},
{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"useWindow",type:"Boolean","default":!1},{name:"windowModalityType",type:"String","default":"modeless"},{name:"windowEmbedStyle",type:"String","default":"window"},{name:"windowHeight",type:"Number"},{name:"windowWidth",type:"Number"}],superclass:AdfUICommand});
AdfRichCommandMenuItem.prototype.GetChanges=function(){var a=AdfRichCommandMenuItem.superclass.GetChanges.call(this),b=a[AdfRichCommandMenuItem.ACCELERATOR];b&&(a[AdfRichCommandMenuItem.ACCELERATOR]=b.toMarshalledString());return a};
function AdfMenuUtils(){}AdfObject.createSubclass(AdfMenuUtils);AdfMenuUtils.InitClass=function(){this.SELECTED_STYLE_CLASS="p_AFSelected";this.HIGHLIGHTED_STYLE_CLASS="p_AFHighlighted";this.DEPRESSED_STYLE_CLASS="p_AFDepressed";this.DETACHED_STYLE_CLASS="p_AFDetached";this.MENU_DEPTH_KEY="_afrDth";this.OVERFLOW_KEY="_afrOflw";this.AFR_TARGETROWCURRENCY="_afrTargetRowCurrency";this.AFR_TARGETCOMPONENTID="_afrTargetComponentId";this._sOpenedMenus=[]};
AdfMenuUtils.isOnMenuBar=function(a){return(a=a.getParent())&&a instanceof AdfRichMenuBar};AdfMenuUtils.isInOverflow=function(a){return a.parentNode.getAttribute(AdfMenuUtils.OVERFLOW_KEY)=="true"};AdfMenuUtils.isInMenu=function(a){return(a=a.getParent())&&a instanceof AdfRichMenu};AdfMenuUtils.closeAllMenus=function(a){var b=this._sOpenedMenus;if(b&&b.length>0)for(var c=b.length-1;c>=0;c--){var d=AdfPage.PAGE.findComponent(b[c]);d?d.getPeer().hidePopup():delete b[c]}a&&AdfMenuUtils.restoreFocusToLastOpenedRootMenu()};
AdfMenuUtils.GetLastOpenedRootMenuId=function(){return AdfMenuUtils._sLastOpenedRootMenuId};AdfMenuUtils.setLastOpenedRootMenuId=function(a){AdfMenuUtils._sLastOpenedRootMenuId=a};AdfMenuUtils.restoreFocusToLastOpenedRootMenu=function(){var a=AdfMenuUtils._sLastOpenedRootMenuId;if(a&&(a=AdfPage.PAGE.findComponent(a),a!=null)){var b=a.getPeer(),c=b.getDomElement();b.focus(a);AdfMenuUtils.highlightRootMenuItem(c)}};
AdfMenuUtils.highlightRootMenuItem=function(a){var b=a.getAttribute("id"),c=AdfMenuUtils._highlightedRootMenuItemId;c&&c!=b&&AdfMenuUtils.unhighlightRootMenuItem();AdfDomUtils.addCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);AdfMenuUtils._highlightedRootMenuItemId=b};
AdfMenuUtils.unhighlightRootMenuItem=function(){var a=AdfAgent.AGENT.getElementById(AdfMenuUtils._highlightedRootMenuItemId);a&&AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);AdfMenuUtils._highlightedRootMenuItemId=null};AdfMenuUtils.dismiss=function(a,b,c){var d=this._sOpenedMenus;if(d&&d.length!=0)for(var e=d.length-1;e>=0;e--){var f=AdfPage.PAGE.findComponent(d[e]);if(f){f=f.getPeer();if(f._contains(a))break;c?d.pop():(f._deselectElement(),b?f.hidePopup():f._delayPopupHiding(e))}else delete d[e]}};
AdfMenuUtils.isImmediate=function(a){var b=a==1,c=AdfDhtmlMenuPeer.OldMousePosition,d=AdfDhtmlMenuPeer.CurrentMousePosition;if(!b&&d&&c&&(b=d.y-c.y,c=d.x-c.x,AdfPage.PAGE.getLocaleContext().isRightToLeft()&&(c=-c),b=b<0||c<0,!b)){if(c=AdfPage.PAGE.findComponent(AdfPage.PAGE.getLastFocusedElement().id))d=c.getPeer(),c instanceof AdfRichMenu&&(b=(b=!d._isSubMenu())||d._getDepth()<a);b=b||this._sOpenedMenus.length<a}return b};
AdfMenuUtils.areMenusOpened=function(){return this._sOpenedMenus&&this._sOpenedMenus.length>0};AdfMenuUtils.isMenuOpen=function(a){return AdfCollections.indexOf(this._sOpenedMenus,a)>=0};AdfMenuUtils.addOpenMenu=function(a){this.isMenuOpen(a)||this._sOpenedMenus.push(a)};AdfMenuUtils.removeOpenMenu=function(a){AdfCollections.removeArrayValue(this._sOpenedMenus,a)};
AdfMenuUtils.getContextMenuItemTargetAttrs=function(a){for(var b=null,a=a.getParent();a!=null&&(a instanceof AdfRichMenu||a instanceof AdfRichPopup);){var c;if((c=a[this.AFR_TARGETROWCURRENCY])!=null){b={targetRowCurrency:c,targetComponentId:a[this.AFR_TARGETCOMPONENTID]};break}a=a.getParent()}return b};
AdfMenuUtils.setContextMenuItemTargetAttrs=function(a,b){var c=a.getPropertyKeys(),d=this.AFR_TARGETROWCURRENCY,e=this.AFR_TARGETCOMPONENTID;c[d]==null&&(c[d]=c[e]={type:"String"},AdfRichUIPeer.addSuppressedPPRAttributes(this,d,e));a.setProperty(e,null);a.setProperty(d,null);a.setProperty(e,b.targetComponentId);a.setProperty(d,b.targetRowCurrency)};
AdfMenuUtils.handleArrowKeys=function(a,b,c){a.getNativeEvent().ctrlKey||(this.isInOverflow(b)?this._handleInMenuBarOverflowArrowKeys(a,b,c):this.isOnMenuBar(c)?this._handleInMenuBarArrowKeys(a,b,c):this.isInMenu(c)&&this._handleInMenuArrowKeys(a,b,c))};
AdfMenuUtils._handleInMenuBarArrowKeys=function(a,b,c){var d=AdfAgent.AGENT,e=a.getNativeEvent();switch(d.getKeyCode(e)){case AdfKeyStroke.ARROWDOWN_KEY:c instanceof AdfRichMenu&&(AdfDomUtils.addCSSClassName(b,this.DEPRESSED_STYLE_CLASS),c.getPeer().show(null,!0),a.cancel())}};AdfMenuUtils._handleInMenuBarOverflowArrowKeys=function(a,b,c){var b=AdfAgent.AGENT,d=a.getNativeEvent();switch(b.getKeyCode(d)){case AdfKeyStroke.ARROWRIGHT_KEY:c instanceof AdfRichMenu&&c.getPeer().show(null,!0),a.cancel()}};
AdfMenuUtils._handleInMenuArrowKeys=function(a,b,c){var d=AdfAgent.AGENT,e=a.getNativeEvent(),d=d.getKeyCode(e),e=c.getParent();switch(d){case AdfKeyStroke.ARROWUP_KEY:AdfMenuUtils._moveHighlightToPreviousMenuItem(b,c);a.cancel();e.getPeer().updateScrollIconsState();break;case AdfKeyStroke.ARROWDOWN_KEY:AdfMenuUtils._moveHighlightToNextMenuItem(b,c);a.cancel();e.getPeer().updateScrollIconsState();break;case AdfKeyStroke.ARROWLEFT_KEY:this._handleMenuItemLeftArrowKey(e);a.cancel();break;case AdfKeyStroke.ARROWRIGHT_KEY:c instanceof
AdfRichMenu?c.getPeer().show(null,!0):this._handleMenuItemRightArrowKey(e),a.cancel()}};AdfMenuUtils._handleMenuItemLeftArrowKey=function(a){var b=a.getPeer();this.isOnMenuBar(a)?(b.focus(a),b.close(!0,!0),a=a.getParent().getPeer().getDomElement(),b=b.getDomElement(),AdfFocusUtils.focusPreviousTabStop(b,a)):!b.isDetached()&&!b.isContextMenu()&&(b.focus(a),b.close(!0,!0))};
AdfMenuUtils._handleMenuItemRightArrowKey=function(a){if(a instanceof AdfRichMenu){var b=a.getPeer();!b.isDetached()&&!b.isContextMenu()&&(this.isOnMenuBar(a)?(b.focus(a),b.close(!0,!0),a=a.getParent().getPeer().getDomElement(),b=b.getDomElement(),AdfFocusUtils.focusNextTabStop(b,a,!0)):this._handleMenuItemRightArrowKey(a.getParent()))}};AdfMenuUtils._moveHighlightToPreviousMenuItem=function(a,b){AdfFocusUtils.focusPreviousTabStop(a,a.parentNode);var c=b.getParent();c&&c instanceof AdfRichMenu&&c.getPeer().updateScrollIconsState()};
AdfMenuUtils._moveHighlightToNextMenuItem=function(a,b){AdfFocusUtils.focusNextTabStop(a,a.parentNode,!0);var c=b.getParent();c&&c instanceof AdfRichMenu&&c.getPeer().updateScrollIconsState()};
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlCommandMenuItemPeer");
AdfDhtmlCommandMenuItemPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfRichCommandMenuItem);AdfObject.ensureClassInitialization(AdfMenuUtils);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.MOUSE_UP_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.FOCUS_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_PRESS_EVENT_TYPE);AdfAgent.AGENT.getCapabilities()[AdfAgent.CAP_TOUCH_SCREEN]==
AdfAgent.CAP_TOUCH_SCREEN_NONE&&AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE,AdfUIInputEvent.MOUSE_OUT_EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichCommandMenuItem.DISABLED,AdfRichCommandMenuItem.SELECTED);this._AFR_GROUPID="_afrGrp";this._BUSY="_busy"};AdfDhtmlCommandMenuItemPeer.prototype.Init=function(a){a.getParent();AdfDhtmlCommandMenuItemPeer.superclass.Init.call(this,a)};
AdfDhtmlCommandMenuItemPeer.prototype.InitDomElement=function(a,b){AdfDhtmlCommandMenuItemPeer.superclass.InitDomElement.call(this,a,b);var c=a.getAccelerator();c!=null&&AdfRichUIPeer.registerKeyStroke(a,c,this._execute)};AdfDhtmlCommandMenuItemPeer.prototype.ComponentRemoved=function(a){var b=a.getAccelerator();b!=null&&AdfRichUIPeer.unregisterKeyStroke(a,b);AdfDhtmlCommandMenuItemPeer.superclass.ComponentRemoved.call(this,a)};AdfDhtmlCommandMenuItemPeer.prototype.GetAccessibleName=function(){return this.getComponent().getText()};
AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentKeyUp=function(a){var b=a.getNativeEvent();if(!b.ctrlKey){var c=AdfAgent.AGENT.getKeyCode(b),d=this.getDomElement(),b=this.getComponent();switch(c){case AdfKeyStroke.SPACE_KEY:case AdfKeyStroke.ENTER_KEY:b.getProperty(AdfDhtmlCommandMenuItemPeer._BUSY)||this._execute();c=!0;break;case AdfKeyStroke.HOME_KEY:AdfFocusUtils.focusFirstTabStop(d.parentNode);c=!0;break;case AdfKeyStroke.END_KEY:AdfFocusUtils.focusLastTabStop(d.parentNode);c=!0;break;default:return}if(c)a.cancel(),
AdfMenuUtils.SubmenuFocusFromMouse=!1;(a=b.getParent())&&a instanceof AdfRichMenu&&a.getPeer().updateScrollIconsState()}};AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentKeyDown=function(a){if(!a.isCanceled()&&!this._isDisabled()){var b=a.getKeyCode(),c=AdfAgent.AGENT;b==AdfKeyStroke.ENTER_KEY?(a.cancel(),a.stopBubbling()):c.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_DOWN_EVENT_TYPE&&(b=this.getDomElement(),c=this.getComponent(),AdfMenuUtils.handleArrowKeys(a,b,c))}};
AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentKeyPress=function(a){if(!a.isCanceled()&&!this._isDisabled()&&AdfAgent.AGENT.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_PRESS_EVENT_TYPE){var b=this.getDomElement(),c=this.getComponent();AdfMenuUtils.handleArrowKeys(a,b,c)}};
AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentFocus=function(a){if(!this._isDisabled()){var b=this.getDomElement();this._deselectElement();AdfPage.PAGE.setLastFocusedElement(b);AdfDhtmlMenuPeer.cancelShowing();var c=parseInt(b.getAttribute(AdfMenuUtils.MENU_DEPTH_KEY)),d=this.getComponent();AdfMenuUtils.isInMenu(d)&&(c=!AdfMenuUtils.SubmenuFocusFromMouse||AdfMenuUtils.isImmediate(c),AdfMenuUtils.dismiss(b,c));AdfDomUtils.addCSSClassName(b,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);a.cancel()}};
AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentMouseDown=function(a){!this._isDisabled()&&a.isLeftButtonPressed()&&(a=this.getDomElement(),AdfDomUtils.addCSSClassName(a,AdfMenuUtils.DEPRESSED_STYLE_CLASS))};AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentMouseUp=function(a){!this._isDisabled()&&a.isLeftButtonPressed()&&(a=this.getDomElement(),AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.DEPRESSED_STYLE_CLASS))};
AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentMouseOver=function(a){var b=a.getNativeEvent();AdfDhtmlMenuPeer.CurrentMousePosition=AdfAgent.AGENT.getMousePosition(b);if(!this._isDisabled())if(a.cancel(),a=this.getComponent(),b=this.getDomElement(),AdfMenuUtils.isInMenu(a))AdfDomUtils.addCSSClassName(b,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS),AdfFocusUtils.containsFocus(b)||this.focus(a);else if(AdfMenuUtils.areMenusOpened())this.focus(a);else{AdfMenuUtils.highlightRootMenuItem(b);var c=AdfPage.PAGE.getActiveDomElement();
c&&AdfDomUtils.isAncestor(b.parentNode,c)&&this.focus(a)}};AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentMouseOut=function(a){a.cancel();AdfDhtmlMenuPeer.OldMousePosition=AdfDhtmlMenuPeer.CurrentMousePosition;AdfMenuUtils.unhighlightRootMenuItem();var a=this.getComponent(),b=this.getDomElement();AdfMenuUtils.isInMenu(a)&&this._deselectElement();AdfDomUtils.removeCSSClassName(b,AdfMenuUtils.DEPRESSED_STYLE_CLASS)};AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentBlur=function(){this._deselectElement()};
AdfDhtmlCommandMenuItemPeer.prototype.HandleComponentClick=function(a){var b=this.getComponent().getProperty(AdfDhtmlCommandMenuItemPeer._BUSY);a.isLeftButtonPressed()&&!this._isDisabled()&&!b&&this._execute();a.cancel()};
AdfDhtmlCommandMenuItemPeer.prototype.ComponentDisabledChanged=function(a,b,c){c==!0?(AdfDomUtils.addCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),b.removeAttribute("tabIndex")):(AdfDomUtils.removeCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),b.setAttribute("tabIndex","0"));page.isScreenReaderMode()&&(b=c==!0?AdfPage.PAGE.getLookAndFeel().getTranslatedString("af_commandMenuItem.STATE_DISABLED"):null,AdfDomUtils.setAccessibleState(a,b),a.getType()=="antonym"&&(a=AdfRichUIPeer.CreateSubId(a.getClientId(),
"selected::state"),AdfDomUtils.setAccessibleStateByElementId(a,b)))};
AdfDhtmlCommandMenuItemPeer.prototype.ComponentSelectedChanged=function(a,b,c){var d=AdfPage.PAGE,e=null,f=a.getType();c?(AdfDomUtils.addCSSClassName(b,AdfMenuUtils.SELECTED_STYLE_CLASS),b=d.getLookAndFeel(),f=="check"?e=b.getTranslatedString("af_commandMenuItem.STATE_CHECKBOX_SELECTED"):f=="radio"&&(e=b.getTranslatedString("af_commandMenuItem.STATE_RADIO_SELECTED"))):AdfDomUtils.removeCSSClassName(b,AdfMenuUtils.SELECTED_STYLE_CLASS);d.isScreenReaderMode()&&(f=="check"||f=="radio")&&AdfDomUtils.setAccessibleState(a,
e)};AdfDhtmlCommandMenuItemPeer.prototype.SetBusy=function(a){var b=this.getComponent(),c=this.getDomElement(),d=AdfDomUtils.getFormElement(c),d=AdfDomUtils.getMultiPartForm(d)!=null;!b.getDisabled()&&!d&&(AdfDomUtils.addOrRemoveCSSClassName(a,c,AdfRichUIPeer.DISABLED_STYLECLASS),b.setProperty(AdfDhtmlCommandMenuItemPeer._BUSY,a,!1,AdfUIComponent.PROPAGATE_NEVER))};
AdfDhtmlCommandMenuItemPeer.prototype._execute=function(){if(!this._isDisabled()){for(var a=this.getComponent(),b=a.getParent();b instanceof AdfRichMenu;)b=b.getParent();b instanceof AdfRichPopup?(AdfMenuUtils.closeAllMenus(!1),b.getPeer().hide(b)):AdfMenuUtils.closeAllMenus(!0);b=AdfMenuUtils.getContextMenuItemTargetAttrs(a);b!=null&&AdfMenuUtils.setContextMenuItemTargetAttrs(a,b);b=new AdfActionEvent(a);b.queue(a.getPartialSubmit());b.isCanceled()||(b=a.getType(),b=="check"||b=="antonym"?a.setSelected(!a.getSelected()):
b=="radio"&&this._toggleRadioGroupItems())}};AdfDhtmlCommandMenuItemPeer.prototype._toggleRadioGroupItems=function(){var a=this.getComponent(),b=this.getDomElement(),c=this._getGroupId(b);if(c==null)AdfLogger.LOGGER.warning("Unexpected to have commandMenuItem without a group Id."),a.setSelected(!a.getSelected());else{for(var b=b.parentNode.childNodes,d=0;d<b.length;d++){var e=b[d],f=this._getGroupId(e);if(c==f&&(e=e.id))e=AdfPage.PAGE.findComponent(e),e!=a&&e.getType&&e.getType()=="radio"&&e.setSelected(!1)}a.setSelected(!0)}};
AdfDhtmlCommandMenuItemPeer.prototype._getGroupId=function(a){return a.getAttribute?a.getAttribute(AdfDhtmlCommandMenuItemPeer._AFR_GROUPID):null};AdfDhtmlCommandMenuItemPeer.prototype._deselectElement=function(){var a=this.getDomElement();AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS)};AdfDhtmlCommandMenuItemPeer.prototype._isDisabled=function(){var a=this.getDomElement();return a.disabled||AdfDomUtils.containsCSSClassName(a,AdfRichUIPeer.DISABLED_STYLECLASS)};
AdfUIComponents.createComponentClass("AdfRichGoMenuItem",{componentType:"oracle.adf.RichGoMenuItem",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},"accelerator",{name:"accessKey",type:"String"},{name:"icon",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"targetFrame",type:"String"},{name:"text",type:"String"}],superclass:AdfUIGo});
AdfRichGoMenuItem.prototype.GetChanges=function(){var a=AdfRichGoMenuItem.superclass.GetChanges.call(this),b=a[AdfRichGoMenuItem.ACCELERATOR];b&&(a[AdfRichGoMenuItem.ACCELERATOR]=b.toMarshalledString());return a};
function AdfMenuUtils(){}AdfObject.createSubclass(AdfMenuUtils);AdfMenuUtils.InitClass=function(){this.SELECTED_STYLE_CLASS="p_AFSelected";this.HIGHLIGHTED_STYLE_CLASS="p_AFHighlighted";this.DEPRESSED_STYLE_CLASS="p_AFDepressed";this.DETACHED_STYLE_CLASS="p_AFDetached";this.MENU_DEPTH_KEY="_afrDth";this.OVERFLOW_KEY="_afrOflw";this.AFR_TARGETROWCURRENCY="_afrTargetRowCurrency";this.AFR_TARGETCOMPONENTID="_afrTargetComponentId";this._sOpenedMenus=[]};
AdfMenuUtils.isOnMenuBar=function(a){return(a=a.getParent())&&a instanceof AdfRichMenuBar};AdfMenuUtils.isInOverflow=function(a){return a.parentNode.getAttribute(AdfMenuUtils.OVERFLOW_KEY)=="true"};AdfMenuUtils.isInMenu=function(a){return(a=a.getParent())&&a instanceof AdfRichMenu};AdfMenuUtils.closeAllMenus=function(a){var b=this._sOpenedMenus;if(b&&b.length>0)for(var c=b.length-1;c>=0;c--){var d=AdfPage.PAGE.findComponent(b[c]);d?d.getPeer().hidePopup():delete b[c]}a&&AdfMenuUtils.restoreFocusToLastOpenedRootMenu()};
AdfMenuUtils.GetLastOpenedRootMenuId=function(){return AdfMenuUtils._sLastOpenedRootMenuId};AdfMenuUtils.setLastOpenedRootMenuId=function(a){AdfMenuUtils._sLastOpenedRootMenuId=a};AdfMenuUtils.restoreFocusToLastOpenedRootMenu=function(){var a=AdfMenuUtils._sLastOpenedRootMenuId;if(a&&(a=AdfPage.PAGE.findComponent(a),a!=null)){var b=a.getPeer(),c=b.getDomElement();b.focus(a);AdfMenuUtils.highlightRootMenuItem(c)}};
AdfMenuUtils.highlightRootMenuItem=function(a){var b=a.getAttribute("id"),c=AdfMenuUtils._highlightedRootMenuItemId;c&&c!=b&&AdfMenuUtils.unhighlightRootMenuItem();AdfDomUtils.addCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);AdfMenuUtils._highlightedRootMenuItemId=b};
AdfMenuUtils.unhighlightRootMenuItem=function(){var a=AdfAgent.AGENT.getElementById(AdfMenuUtils._highlightedRootMenuItemId);a&&AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);AdfMenuUtils._highlightedRootMenuItemId=null};AdfMenuUtils.dismiss=function(a,b,c){var d=this._sOpenedMenus;if(d&&d.length!=0)for(var e=d.length-1;e>=0;e--){var f=AdfPage.PAGE.findComponent(d[e]);if(f){f=f.getPeer();if(f._contains(a))break;c?d.pop():(f._deselectElement(),b?f.hidePopup():f._delayPopupHiding(e))}else delete d[e]}};
AdfMenuUtils.isImmediate=function(a){var b=a==1,c=AdfDhtmlMenuPeer.OldMousePosition,d=AdfDhtmlMenuPeer.CurrentMousePosition;if(!b&&d&&c&&(b=d.y-c.y,c=d.x-c.x,AdfPage.PAGE.getLocaleContext().isRightToLeft()&&(c=-c),b=b<0||c<0,!b)){if(c=AdfPage.PAGE.findComponent(AdfPage.PAGE.getLastFocusedElement().id))d=c.getPeer(),c instanceof AdfRichMenu&&(b=(b=!d._isSubMenu())||d._getDepth()<a);b=b||this._sOpenedMenus.length<a}return b};
AdfMenuUtils.areMenusOpened=function(){return this._sOpenedMenus&&this._sOpenedMenus.length>0};AdfMenuUtils.isMenuOpen=function(a){return AdfCollections.indexOf(this._sOpenedMenus,a)>=0};AdfMenuUtils.addOpenMenu=function(a){this.isMenuOpen(a)||this._sOpenedMenus.push(a)};AdfMenuUtils.removeOpenMenu=function(a){AdfCollections.removeArrayValue(this._sOpenedMenus,a)};
AdfMenuUtils.getContextMenuItemTargetAttrs=function(a){for(var b=null,a=a.getParent();a!=null&&(a instanceof AdfRichMenu||a instanceof AdfRichPopup);){var c;if((c=a[this.AFR_TARGETROWCURRENCY])!=null){b={targetRowCurrency:c,targetComponentId:a[this.AFR_TARGETCOMPONENTID]};break}a=a.getParent()}return b};
AdfMenuUtils.setContextMenuItemTargetAttrs=function(a,b){var c=a.getPropertyKeys(),d=this.AFR_TARGETROWCURRENCY,e=this.AFR_TARGETCOMPONENTID;c[d]==null&&(c[d]=c[e]={type:"String"},AdfRichUIPeer.addSuppressedPPRAttributes(this,d,e));a.setProperty(e,null);a.setProperty(d,null);a.setProperty(e,b.targetComponentId);a.setProperty(d,b.targetRowCurrency)};
AdfMenuUtils.handleArrowKeys=function(a,b,c){a.getNativeEvent().ctrlKey||(this.isInOverflow(b)?this._handleInMenuBarOverflowArrowKeys(a,b,c):this.isOnMenuBar(c)?this._handleInMenuBarArrowKeys(a,b,c):this.isInMenu(c)&&this._handleInMenuArrowKeys(a,b,c))};
AdfMenuUtils._handleInMenuBarArrowKeys=function(a,b,c){var d=AdfAgent.AGENT,e=a.getNativeEvent();switch(d.getKeyCode(e)){case AdfKeyStroke.ARROWDOWN_KEY:c instanceof AdfRichMenu&&(AdfDomUtils.addCSSClassName(b,this.DEPRESSED_STYLE_CLASS),c.getPeer().show(null,!0),a.cancel())}};AdfMenuUtils._handleInMenuBarOverflowArrowKeys=function(a,b,c){var b=AdfAgent.AGENT,d=a.getNativeEvent();switch(b.getKeyCode(d)){case AdfKeyStroke.ARROWRIGHT_KEY:c instanceof AdfRichMenu&&c.getPeer().show(null,!0),a.cancel()}};
AdfMenuUtils._handleInMenuArrowKeys=function(a,b,c){var d=AdfAgent.AGENT,e=a.getNativeEvent(),d=d.getKeyCode(e),e=c.getParent();switch(d){case AdfKeyStroke.ARROWUP_KEY:AdfMenuUtils._moveHighlightToPreviousMenuItem(b,c);a.cancel();e.getPeer().updateScrollIconsState();break;case AdfKeyStroke.ARROWDOWN_KEY:AdfMenuUtils._moveHighlightToNextMenuItem(b,c);a.cancel();e.getPeer().updateScrollIconsState();break;case AdfKeyStroke.ARROWLEFT_KEY:this._handleMenuItemLeftArrowKey(e);a.cancel();break;case AdfKeyStroke.ARROWRIGHT_KEY:c instanceof
AdfRichMenu?c.getPeer().show(null,!0):this._handleMenuItemRightArrowKey(e),a.cancel()}};AdfMenuUtils._handleMenuItemLeftArrowKey=function(a){var b=a.getPeer();this.isOnMenuBar(a)?(b.focus(a),b.close(!0,!0),a=a.getParent().getPeer().getDomElement(),b=b.getDomElement(),AdfFocusUtils.focusPreviousTabStop(b,a)):!b.isDetached()&&!b.isContextMenu()&&(b.focus(a),b.close(!0,!0))};
AdfMenuUtils._handleMenuItemRightArrowKey=function(a){if(a instanceof AdfRichMenu){var b=a.getPeer();!b.isDetached()&&!b.isContextMenu()&&(this.isOnMenuBar(a)?(b.focus(a),b.close(!0,!0),a=a.getParent().getPeer().getDomElement(),b=b.getDomElement(),AdfFocusUtils.focusNextTabStop(b,a,!0)):this._handleMenuItemRightArrowKey(a.getParent()))}};AdfMenuUtils._moveHighlightToPreviousMenuItem=function(a,b){AdfFocusUtils.focusPreviousTabStop(a,a.parentNode);var c=b.getParent();c&&c instanceof AdfRichMenu&&c.getPeer().updateScrollIconsState()};
AdfMenuUtils._moveHighlightToNextMenuItem=function(a,b){AdfFocusUtils.focusNextTabStop(a,a.parentNode,!0);var c=b.getParent();c&&c instanceof AdfRichMenu&&c.getPeer().updateScrollIconsState()};
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlGoMenuItemPeer",!1);
AdfDhtmlGoMenuItemPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfRichGoMenuItem);AdfObject.ensureClassInitialization(AdfMenuUtils);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.MOUSE_UP_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.FOCUS_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_PRESS_EVENT_TYPE);AdfAgent.AGENT.getCapabilities()[AdfAgent.CAP_TOUCH_SCREEN]==
AdfAgent.CAP_TOUCH_SCREEN_NONE&&AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE,AdfUIInputEvent.MOUSE_OUT_EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichGoMenuItem.DISABLED)};AdfDhtmlGoMenuItemPeer.prototype.Init=function(a){a.getParent();AdfDhtmlGoMenuItemPeer.superclass.Init.call(this,a)};
AdfDhtmlGoMenuItemPeer.prototype.InitDomElement=function(a,b){AdfDhtmlGoMenuItemPeer.superclass.InitDomElement.call(this,a,b);var c=a.getAccelerator();c!=null&&AdfRichUIPeer.registerKeyStroke(a,c,this._execute)};AdfDhtmlGoMenuItemPeer.prototype.ComponentRemoved=function(a){var b=a.getAccelerator();b!=null&&AdfRichUIPeer.unregisterKeyStroke(a,b);AdfDhtmlGoMenuItemPeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlGoMenuItemPeer.prototype.HandleComponentKeyUp=function(a){var b=a.getNativeEvent();if(!b.ctrlKey){var b=AdfAgent.AGENT.getKeyCode(b),c=this.getDomElement();switch(b){case AdfKeyStroke.SPACE_KEY:case AdfKeyStroke.ENTER_KEY:this._execute();b=!0;break;case AdfKeyStroke.HOME_KEY:AdfFocusUtils.focusFirstTabStop(c.parentNode);b=!0;break;case AdfKeyStroke.END_KEY:AdfFocusUtils.focusLastTabStop(c.parentNode);b=!0;break;default:return}if(b)a.cancel(),AdfMenuUtils.SubmenuFocusFromMouse=!1;(a=this.getComponent().getParent())&&
a instanceof AdfRichMenu&&a.getPeer().updateScrollIconsState()}};AdfDhtmlGoMenuItemPeer.prototype.HandleComponentKeyDown=function(a){if(!a.isCanceled()&&!this._isDisabled()){var b=a.getKeyCode(),c=AdfAgent.AGENT;b==AdfKeyStroke.ENTER_KEY?(a.cancel(),a.stopBubbling()):c.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_DOWN_EVENT_TYPE&&(b=this.getDomElement(),c=this.getComponent(),AdfMenuUtils.handleArrowKeys(a,b,c))}};
AdfDhtmlGoMenuItemPeer.prototype.HandleComponentKeyPress=function(a){if(!a.isCanceled()&&!this._isDisabled()&&AdfAgent.AGENT.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_PRESS_EVENT_TYPE){var b=this.getDomElement(),c=this.getComponent();AdfMenuUtils.handleArrowKeys(a,b,c)}};
AdfDhtmlGoMenuItemPeer.prototype.HandleComponentFocus=function(a){if(!this._isDisabled()){var b=this.getDomElement();this._deselectElement();AdfPage.PAGE.setLastFocusedElement(b);AdfDhtmlMenuPeer.cancelShowing();var c=parseInt(b.getAttribute(AdfMenuUtils.MENU_DEPTH_KEY)),d=this.getComponent();AdfMenuUtils.isInMenu(d)&&(c=!AdfMenuUtils.SubmenuFocusFromMouse||AdfMenuUtils.isImmediate(c),AdfMenuUtils.dismiss(b,c));AdfDomUtils.addCSSClassName(b,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS);a.cancel()}};
AdfDhtmlGoMenuItemPeer.prototype.HandleComponentMouseDown=function(a){!this._isDisabled()&&a.isLeftButtonPressed()&&(a=this.getDomElement(),AdfDomUtils.addCSSClassName(a,AdfMenuUtils.DEPRESSED_STYLE_CLASS))};AdfDhtmlGoMenuItemPeer.prototype.HandleComponentMouseUp=function(a){!this._isDisabled()&&a.isLeftButtonPressed()&&(a=this.getDomElement(),AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.DEPRESSED_STYLE_CLASS))};
AdfDhtmlGoMenuItemPeer.prototype.HandleComponentMouseOver=function(a){var b=a.getNativeEvent();AdfDhtmlMenuPeer.CurrentMousePosition=AdfAgent.AGENT.getMousePosition(b);if(!this._isDisabled())if(a.cancel(),a=this.getDomElement(),b=this.getComponent(),AdfMenuUtils.isInMenu(b))AdfDomUtils.addCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS),AdfFocusUtils.containsFocus(a)||this.focus(b);else if(AdfMenuUtils.areMenusOpened())this.focus(b);else{a=this.getDomElement();AdfMenuUtils.highlightRootMenuItem(a);
var c=AdfPage.PAGE.getActiveDomElement();c&&AdfDomUtils.isAncestor(a.parentNode,c)&&this.focus(b)}};AdfDhtmlGoMenuItemPeer.prototype.HandleComponentMouseOut=function(a){a.cancel();AdfDhtmlMenuPeer.OldMousePosition=AdfDhtmlMenuPeer.CurrentMousePosition;AdfMenuUtils.unhighlightRootMenuItem();var a=this.getComponent(),b=this.getDomElement();AdfMenuUtils.isInMenu(a)&&this._deselectElement();AdfDomUtils.removeCSSClassName(b,AdfMenuUtils.DEPRESSED_STYLE_CLASS)};
AdfDhtmlGoMenuItemPeer.prototype.HandleComponentBlur=function(){this._deselectElement()};AdfDhtmlGoMenuItemPeer.prototype.HandleComponentClick=function(a){!this._isDisabled()&&a.isLeftButtonPressed()&&this._execute();a.cancel()};
AdfDhtmlGoMenuItemPeer.prototype.ComponentDisabledChanged=function(a,b,c){var d=null,e=AdfPage.PAGE;c==!0?(d=e.getLookAndFeel().getTranslatedString("af_goMenuItem.STATE_DISABLED"),AdfDomUtils.addCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),b.removeAttribute("tabIndex")):(AdfDomUtils.removeCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),b.setAttribute("tabIndex","0"));e.isScreenReaderMode()&&AdfDomUtils.setAccessibleState(a,d)};
AdfDhtmlGoMenuItemPeer.prototype._execute=function(){if(!this._isDisabled()){var a=this.getComponent(),b=AdfMenuUtils.getContextMenuItemTargetAttrs(a);b!=null&&AdfMenuUtils.setContextMenuItemTargetAttrs(a,b);var b=a.getDestination(),a=a.getTargetFrame(),c=b==null?!0:!1;b==null&&(b="#");a==null?self.location=b:window.open(b,a).focus();AdfMenuUtils.closeAllMenus(c)}};AdfDhtmlGoMenuItemPeer.prototype._deselectElement=function(){var a=this.getDomElement();AdfDomUtils.removeCSSClassName(a,AdfMenuUtils.HIGHLIGHTED_STYLE_CLASS)};
AdfDhtmlGoMenuItemPeer.prototype._isDisabled=function(){var a=this.getDomElement();return a.disabled||AdfDomUtils.containsCSSClassName(a,AdfRichUIPeer.DISABLED_STYLECLASS)};