AdfUIComponents.createComponentClass("AdfUINavigationLevel",{componentType:"org.apache.myfaces.trinidad.NavigationLevel",propertyKeys:["value",{name:"level",type:"Number","default":0,secured:!0}],namingContainer:!0,superclass:AdfUICollection});
AdfUIComponents.createComponentClass("AdfRichNavigationPane",{componentType:"oracle.adf.RichNavigationPane",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"hint",type:"String","default":"tabs"},{name:"title",type:"String"},{name:"itemRemoval",type:"String","default":"none"}],eventNames:["item"],
namingContainer:!0,superclass:AdfUINavigationLevel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlNavigationPanePeer",!1);
AdfDhtmlNavigationPanePeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfDhtmlPopupWindow);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE);AdfAgent.AGENT.getCapabilities()[AdfAgent.CAP_TOUCH_SCREEN]==AdfAgent.CAP_TOUCH_SCREEN_NONE&&AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE);this._CHOICE_BUTTON_ID="_afrChoiceButton";
this._CHOICE_DATA_CONTAINER_ID="_afrChoiceDataContainer";this._POPUP_ID="popupContent";this._POPUP_PANEL_ID="_afrChoicePopupPanel";this._POPUP_CLOSED_TIME="_afrPopupClosedTime";this._TAB_HEADER="tabh";this._TAB_HINT="tabs";this._BAR_HINT="bar";AdfDhtmlNavigationPanePeer._SELECTED_STYLECLASS="p_AFSelected";this._compressedLayoutMode="notSupported";var a=AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|navigationPane-tr-layout-type"),b=AdfAgent.AGENT,b=b.getPlatform()==AdfAgent.IE_PLATFORM&&Math.floor(b.getVersion())==
7;this._compressedLayoutMode=AdfPage.PAGE.isScreenReaderMode()?"notSupported":a=="overflow"?"overflow":a=="overflow-droplist"||b?"overflow-droplist":"conveyorBelt"};
AdfDhtmlNavigationPanePeer.prototype.InitDomElement=function(a,b){AdfDhtmlNavigationPanePeer.superclass.InitDomElement.call(this,a,b);this._isScreenReaderMode=AdfPage.PAGE.isScreenReaderMode();var c=a.getClientId(),d=AdfAgent.getAgent();if(!this._isScreenReaderMode)if(a.getHint()==AdfDhtmlNavigationPanePeer._TAB_HINT){if(c=AdfRichUIPeer.CreateSubId(c,AdfDhtmlNavigationPanePeer._TAB_HEADER),this._headerDiv=d.getElementById(c))c=AdfDhtmlNavigationPanePeer._compressedLayoutMode=="conveyorBelt"?AdfRichUIPeer.CreateSubId(c,
"cbc"):AdfRichUIPeer.CreateSubId(c,"oc"),this._headerContentDiv=d.getElementById(c),AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a)}else if(a.getHint()==AdfDhtmlNavigationPanePeer._BAR_HINT)c=AdfRichUIPeer.CreateSubId(c,"oc"),this._barOverflowContent=d.getElementById(c),AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a)};
AdfDhtmlNavigationPanePeer.prototype.needsResizeNotify=function(a){return!this._isScreenReaderMode&&(this._headerDiv||a.getHint()==AdfDhtmlNavigationPanePeer._BAR_HINT)?!0:!1};
AdfDhtmlNavigationPanePeer.prototype.ResizeNotify=function(a,b,c){if(AdfDhtmlNavigationPanePeer._compressedLayoutMode!="notSupported")if(b=this.getComponent(),this._headerContentDiv)this._resizeTabHeader(a,c);else if(this._barOverflowContent){if(!this._overflowSupport){a=b.getClientId();if(!AdfOverflowSupport.needsOverflow(a))return;this._overflowSupport=new AdfOverflowSupport(a,this,"both");for(var a=this._barOverflowContent.childNodes,c=this._getActiveChildIndex(a),d=-1;b=a[++d];)if(b.nodeType==
1&&(b.tagName.toLowerCase()=="a"||b.getElementsByTagName("a").length>0))c==-1&&(c=d),this._overflowSupport.createStep(),c==d?this._overflowSupport.addElement(b):d>c?(this._addSeparators(a,d,!0),this._overflowSupport.addElement(b)):(this._overflowSupport.addElement(b),this._addSeparators(a,d,!1)),this._overflowSupport.addOverflowElement(this._createBarOverflowElement(b))}this._overflowSupport.handleResize()}};
AdfDhtmlNavigationPanePeer.prototype._resizeTabHeader=function(a,b){var c=this.getComponent(),c=AdfRichUIPeer.CreateSubId(c.getClientId(),AdfDhtmlNavigationPanePeer._TAB_HEADER),d=this._getChildElements(c,this._headerContentDiv),e=AdfDhtmlNavigationPanePeer._compressedLayoutMode;if(e=="overflow"){if(!this._overflowSupport)this._overflowSupport=this._getTabOverflowSupport(c,d);this._resizeTabsWithCompressedLayout(a,b,this._overflowSupport,d,this._headerDiv)}else if(e=="overflow-droplist"){if(!this._overflowSupport)this._overflowSupport=
this._getTabOverflowDroplistSupport(c,d);this._resizeTabsWithCompressedLayout(a,b,this._overflowSupport,d,this._headerDiv)}else{if(!this._conveyorBeltSupport)this._conveyorBeltSupport=this._getTabConveyorBeltSupport(c,d);this._resizeTabsWithCompressedLayout(a,b,this._conveyorBeltSupport,d,this._headerDiv)}};
AdfDhtmlNavigationPanePeer.prototype._getChildElements=function(a,b){for(var c=b.childNodes,d=[],e=AdfDhtmlNavigationPanePeer._compressedLayoutMode=="conveyorBelt",f=e?AdfRichUIPeer.CreateSubId(a,"cbs"):null,g=0;g<c.length;g++){var h=c[g];h.nodeType==1&&!(e&&h.getAttribute("id")==f)&&d.push(h)}return d};AdfDhtmlNavigationPanePeer.prototype._resizeTabsWithCompressedLayout=function(a,b,c,d,e){c.handleResize();AdfDomUtils.setScrollTop(e,0)};
AdfDhtmlNavigationPanePeer.prototype.__saveAndRemoveCompressedLayout=function(){var a=this._conveyorBeltSupport;if(a)AdfDhtmlNavigationPanePeer._conveyorBeltFirstItem=a.getFirstItemDisplayed();this._removeCompressedLayoutSupport()};
AdfDhtmlNavigationPanePeer.prototype._isLayoutCompressed=function(a){var b=AdfDhtmlNavigationPanePeer._compressedLayoutMode;if((b=="overflow"||b=="overflow-droplist")&&!this._overflowSupport&&!AdfOverflowSupport.needsOverflow(a))return!1;if(b=="conveyorBelt"&&!this._conveyorBeltSupport&&!AdfConveyorBeltSupport.shouldUseConveyorBelt(a))return!1;return!0};
AdfDhtmlNavigationPanePeer.prototype._getTabOverflowSupport=function(a,b){for(var c=new AdfOverflowSupport(a,this,"both"),d=0;d<b.length;d++){var e=b[d];e.nodeType==1&&(c.createStep(),c.addElement(e),e.style.display!="none"&&c.addOverflowElement(this._createTabCompressedLayoutPopupElement(e)))}return c};
AdfDhtmlNavigationPanePeer.prototype._getTabOverflowDroplistSupport=function(a,b){for(var c=new AdfOverflowSupport(a,this,"droplist"),d=[],e=0;e<b.length;e++){var f=b[e];f.nodeType==1&&(c.createStep(),c.addElement(f),f.style.display!="none"&&(c.addOverflowElement(this._createTabCompressedLayoutPopupElement(f)),d.push(this._createTabCompressedLayoutPopupElement(f))))}c.addDropListElements(d);return c};
AdfDhtmlNavigationPanePeer.prototype._getTabConveyorBeltSupport=function(a,b){for(var c=new AdfConveyorBeltSupport(a,this),d=[],e=AdfRichUIPeer.CreateSubId(a,"cbs"),f=0;f<b.length;f++){var g=b[f];g.nodeType==1&&g.getAttribute("id")!=e&&g.style.display!="none"&&d.push(this._createTabCompressedLayoutPopupElement(g))}c.addDropListElements(d);if(d=AdfDhtmlNavigationPanePeer._conveyorBeltFirstItem)c.setFirstItemDisplayed(d),AdfDhtmlNavigationPanePeer._conveyorBeltFirstItem=null;return c};
AdfDhtmlNavigationPanePeer.prototype.ComponentRemoved=function(a){this._removeCompressedLayoutSupport();this._headerDiv?(delete this._headerDiv,delete this._headerContentDiv):this._barOverflowContent&&delete this._barOverflowContent;AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a);AdfDhtmlNavigationPanePeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlNavigationPanePeer.prototype._removeCompressedLayoutSupport=function(){if(this._overflowSupport)this._overflowSupport.removeOverflowSupport(),this._overflowSupport=null;if(this._conveyorBeltSupport)this._conveyorBeltSupport.removeConveyorBeltSupport(),this._conveyorBeltSupport=null};AdfDhtmlNavigationPanePeer.prototype.HandleComponentClick=function(a){a.cancel();return!1};
AdfDhtmlNavigationPanePeer.prototype.HandleComponentKeyUp=function(a){var b=this.getComponent(),c=a.getNativeEvent(),d=AdfAgent.AGENT.getEventTarget(c),e=AdfAgent.AGENT.getKeyCode(c);if(this.isPopupVisible(b,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)){var f=!1,g=this._getPopupContentDom(b);switch(e){case AdfKeyStroke.ESC_KEY:d=this._getChoiceDropDownElement(b);AdfFocusUtils.focusElement(d);f=!0;break;case AdfKeyStroke.ARROWDOWN_KEY:AdfFocusUtils.focusNextTabStop(d,g);cancelEvt=!0;break;case AdfKeyStroke.ARROWUP_KEY:AdfFocusUtils.focusPreviousTabStop(d,
g)}f&&this.hidePopup(b,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)}else d==this._getChoiceDropDownElement(b)&&e==AdfKeyStroke.ARROWDOWN_KEY&&this._showChoicePopupPanel(b);a.isCanceled()||(!c.ctrlKey||!(c.altKey&&e==87))&&a.cancel()};
AdfDhtmlNavigationPanePeer.prototype.HandleComponentMouseDown=function(a){var b=a.getNativeEvent(),a=a.getSource(),b=AdfAgent.AGENT.getEventTarget(b),c=this._getChoiceDropDownElement(a);if(b==c||b.parentNode==c)this.isPopupVisible(a,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)?this.hidePopup(a,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID):this._showChoicePopupPanel(a)};
AdfDhtmlNavigationPanePeer.prototype.HandleComponentMouseOver=function(a){if(this.isPopupVisible(this.getComponent(),AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)){var b=a.getNativeEventTarget();AdfFocusUtils.focusElement(b)}a.cancel()};AdfDhtmlNavigationPanePeer.prototype.HandleComponentKeyDown=function(a){var b=a.getNativeEvent(),b=AdfAgent.AGENT.getEventTarget(b),c=a.getSource();b==this._getChoiceDropDownElement(c)&&a.getKeyCode()==AdfKeyStroke.ENTER_KEY&&this._showChoicePopupPanel(c)};
AdfDhtmlNavigationPanePeer.prototype.GetPopupAlignmentNode=function(a){return this._getChoiceDropDownElement(a)};AdfDhtmlNavigationPanePeer.prototype.PopupClosed=function(a,b,c){c==AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID&&(a=a.getClientId(),a=AdfRichUIPeer.CreateSubId(a,AdfDhtmlNavigationPanePeer._CHOICE_DATA_CONTAINER_ID),AdfAgent.AGENT.getElementById(a).appendChild(b))};
AdfDhtmlNavigationPanePeer.prototype._getChoiceDropDownElement=function(a){a=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlNavigationPanePeer._CHOICE_BUTTON_ID);return AdfAgent.AGENT.getElementById(a)};
AdfDhtmlNavigationPanePeer.prototype._showChoicePopupPanel=function(a){AdfObject.ensureClassInitialization(AdfRichPopup);AdfObject.ensureClassInitialization(AdfDhtmlPopupWindow);var b=this._getPopupContentDom(a),c=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlNavigationPanePeer._CHOICE_BUTTON_ID);b.parentNode.removeChild(b);var d={};d[AdfDhtmlPopupWindow.HINT_TYPE]=AdfDhtmlPopupWindow.HINT_TYPE_MENU;d[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_START;d[AdfRichPopup.HINT_ALIGN_ID]=c;d[AdfDhtmlPopupWindow.HINT_AUTODISMISS]=
AdfDhtmlPopupWindow.HINT_AUTODISMISS_MENU;this.showPopup(a,b,d,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)};AdfDhtmlNavigationPanePeer.prototype._getPopupContentDom=function(a){a=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlNavigationPanePeer._POPUP_ID);return AdfAgent.AGENT.getElementById(a)};
AdfDhtmlNavigationPanePeer.prototype._createTabCompressedLayoutPopupElement=function(a){var b=AdfAgent.AGENT,c=AdfPage.PAGE.getLookAndFeel(),d=a.getAttribute("id"),e=a.getElementsByTagName("a")[0],f=a.getElementsByTagName("a")[1],g=a.getElementsByTagName("img")[0];g&&(g=g.cloneNode(!0));if(e&&e.className.indexOf("p_AFDisabled")==-1){var e=e.cloneNode(!0),h=AdfDhtmlNavigationPanePeer._tabCompressedLayoutElementStyleClass;if(h==null)h=AdfDhtmlNavigationPanePeer._compressedLayoutMode=="conveyorBelt"?
c.getStyleClass("AFConveyorBeltElement"):c.getStyleClass("AFOverflowElement"),AdfDhtmlNavigationPanePeer._tabCompressedLayoutElementStyleClass=h;f&&(f=f.cloneNode(!0),f.setAttribute("_componentId",d),c=this.createCallback(this._handleRemoveButtonClick),b.addBubbleEventListener(f,"click",c));var c=a.getAttribute("href"),k=b.getDomDocument().location.href;if(c&&c.indexOf(k)==-1){if(e.setAttribute("_href",c),g&&g.setAttribute("_href",c),d=a.getAttribute("target"))e.setAttribute("_target",d),g&&g.setAttribute("_target",
d)}else e.setAttribute("_componentId",d),g&&g.setAttribute("_componentId",d);d=this.createCallback(this._handleNavItemClick);b.addBubbleEventListener(e,"click",d);g&&b.addBubbleEventListener(g,"click",d)}else{b=e.innerHTML;e=a.ownerDocument.createElement("div");e.innerHTML=b;b=AdfDhtmlNavigationPanePeer._tabCompressedLayoutElementDisabledStyleClass;if(b==null)b=AdfDhtmlNavigationPanePeer._compressedLayoutMode=="conveyorBelt"?c.getStyleClass("AFConveyorBeltElementDisabled"):c.getStyleClass("AFOverflowElementDisabled"),
AdfDhtmlNavigationPanePeer._tabCompressedLayoutElementDisabledStyleClass=b;f&&(f=f.cloneNode(!0))}b=a.ownerDocument.createElement("table");b.cellPadding=0;b.cellSpacing=0;b.style.width="100%";d=b.insertRow(-1);c=d.insertCell(-1);g&&c.appendChild(g);g=d.insertCell(-1);g.style.width="100%";c=a.ownerDocument.createElement("div");c.className=h;g.appendChild(c);c.appendChild(e);e=d.insertCell(-1);if(f)a=a.ownerDocument.createElement("div"),a.className=h,e.appendChild(a),a.appendChild(f);return b};
AdfDhtmlNavigationPanePeer.prototype._createBarOverflowElement=function(a){var b=this.getComponent(),c=AdfDhtmlNavigationPanePeer._barOverflowElementStyleClass;if(c==null)c=AdfPage.PAGE.getLookAndFeel().getStyleClass("AFOverflowElement"),AdfDhtmlNavigationPanePeer._barOverflowElementStyleClass=c;var d=a.ownerDocument.createElement("div");d.className=c;c=a.cloneNode(!0);c.removeAttribute("id");d.appendChild(c);b=AdfPage.PAGE.findComponent(a.id);if(!b.getDisabled()){b=a.href;b==void 0&&(b=a.getAttribute("href"));
var e=AdfAgent.AGENT.getDomDocument().location.href;b&&b.indexOf(e)==-1?(c.setAttribute("_href",b),(a=a.getAttribute("target"))&&c.setAttribute("_target",a)):c.setAttribute("_componentId",a.getAttribute("id"));a=this.createCallback(this._handleNavItemClick);AdfAgent.AGENT.addBubbleEventListener(c,"click",a)}return d};
AdfDhtmlNavigationPanePeer.prototype._handleNavItemClick=function(a){this.hideAllPopups(this.getComponent());var b=AdfAgent.AGENT.getEventTarget(a);(a=b.getAttribute("_href"))?(b=b.getAttribute("_target"))?window.open(a,b):self.location=a:(this.__saveAndRemoveCompressedLayout(),a=b.getAttribute("_componentId"),a=AdfPage.PAGE.findComponent(a),AdfActionEvent.queue(a,a.getPartialSubmit()))};
AdfDhtmlNavigationPanePeer.prototype._handleRemoveButtonClick=function(a){var a=AdfAgent.AGENT.getEventTarget(a),b=a.getAttribute("_componentId");b==null&&(b=a.parentNode.getAttribute("_componentId"));a=AdfPage.PAGE.findComponent(b);b=a.getPeer();b.bind(a);b&&b.canRemove&&b.canRemove()&&(this.hideAllPopups(this.getComponent()),this.__saveAndRemoveCompressedLayout(),AdfItemEvent.queueItemRemoveEvent(a))};
AdfDhtmlNavigationPanePeer.prototype._addSeparators=function(a,b,c){var d=b+1;c&&(d=b-1);for(var b=!0,e=a[d];b&&e;){if(e.nodeType==1)if(e.tagName.toLowerCase()=="img"||e.getElementsByTagName("img").length>0)this._overflowSupport.addElement(e),b=!1;else if(e.tagName.toLowerCase()=="span"||e.getElementsByTagName("span").length>0)this._overflowSupport.addElement(e),b=!1;c?d--:d++;e=a[d]}};
AdfDhtmlNavigationPanePeer.prototype._getActiveChildIndex=function(a){for(var b=-1,c;c=a[++b];)if(AdfDomUtils.containsCSSClassName(c,"p_AFSelected"))return b;return-1};
AdfUIComponents.createComponentClass("AdfRichCommandNavigationItem",{componentType:"oracle.adf.RichCommandNavigationItem",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"useWindow",type:"Boolean","default":!1},{name:"windowModalityType",type:"String","default":"modeless"},{name:"windowEmbedStyle",type:"String","default":"window"},{name:"windowHeight",
type:"Number"},{name:"windowWidth",type:"Number"},{name:"accessKey",type:"String"},{name:"destination",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"icon",type:"String"},{name:"messageType",type:"String","default":"none"},{name:"partialSubmit",type:"Boolean","default":!1,secured:!0},{name:"selected",type:"Boolean","default":!1},{name:"showRequired",type:"Boolean","default":!1},{name:"targetFrame",type:"String"},{name:"text",type:"String"},{name:"visited",type:"Boolean",
"default":!1},"itemListener",{name:"remove",type:"String","default":"inherit"}],eventNames:["item"],superclass:AdfUICommand});
AdfRichUIPeer.createPeerClass(AdfDhtmlCommandLinkPeer,"AdfDhtmlCommandNavigationItemPeer");AdfDhtmlCommandNavigationItemPeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.FOCUS_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE);this._TAB_ANCHOR_ID="disclosureAnchor";this._REMOVE_ICON_ID="rmAbv";this._HIGHLIGHTED_STYLE_CLASS="p_AFHighlighted"};
AdfDhtmlCommandNavigationItemPeer.prototype.InitDomElement=function(a,b){AdfDhtmlCommandNavigationItemPeer.superclass.InitDomElement.call(this,a,b)};AdfDhtmlCommandNavigationItemPeer.prototype.HandleComponentKeyUp=function(a){var b=a.getNativeEvent(),c=a.getKeyCode();b.ctrlKey&&b.altKey&&c==AdfKeyStroke.F4_KEY&&(b=this.getComponent(),!b.getDisabled()&&this.canRemove()&&(this._saveAndRemoveCompressedLayout(),a=a.getNativeEventTarget(),AdfFocusUtils.focusNextTabStop(a,null,!0),AdfItemEvent.queueItemRemoveEvent(b)))};
AdfDhtmlCommandNavigationItemPeer.prototype.HandleComponentClick=function(a){var b=this.getComponent();if(a.isLeftButtonPressed()&&!b.getDisabled())if(this._isOnRemoveButton(a)){if(this.canRemove()){this._saveAndRemoveCompressedLayout();var c=a.getNativeEventTarget();AdfFocusUtils.focusNextTabStop(c,null,!0);AdfItemEvent.queueItemRemoveEvent(b)}}else{var c=AdfRichUIPeer.getDomElementForComponent(b),d=c.href,c=AdfRichUIPeer.getDomElementForComponent(b),d=c.href;d==void 0&&(d=c.getAttribute("href"));
var e=AdfAgent.AGENT.getDomDocument().location.href,f=e.indexOf("#"),e=f==-1?e:e.substring(0,f);d&&(d.indexOf(e)==-1||d.substring(d.indexOf("#")).length>1)?(AdfPage.PAGE.__perfTimings(!0,!0,!0,"User click Command Navigation , GET request"),c=c.getAttribute("target"),c!=null&&c.length>0?window.open(d,c):self.location=d,a.cancel()):(AdfActionEvent.queue(b,b.getPartialSubmit()),this._saveAndRemoveCompressedLayout(),AdfActionEvent.queue(b,b.getPartialSubmit()))}};
AdfDhtmlCommandNavigationItemPeer.prototype.HandleComponentFocus=function(a){this._isDisabled()?a.stopBubbling():this._handleTabFocusOrBlur(a,!0)};AdfDhtmlCommandNavigationItemPeer.prototype.HandleComponentBlur=function(a){this._handleTabFocusOrBlur(a,!1)};
AdfDhtmlCommandNavigationItemPeer.prototype._handleTabFocusOrBlur=function(a,b){a.cancel();var c=a.getNativeEventTarget().id;c!=null&&(c=c.split("::"),!(c.length<=1)&&c[c.length-1]==AdfDhtmlCommandNavigationItemPeer._TAB_ANCHOR_ID&&(c=this.getDomElement(),b?AdfDomUtils.addCSSClassName(c,AdfDhtmlCommandNavigationItemPeer._HIGHLIGHTED_STYLE_CLASS):AdfDomUtils.removeCSSClassName(c,AdfDhtmlCommandNavigationItemPeer._HIGHLIGHTED_STYLE_CLASS)))};
AdfDhtmlCommandNavigationItemPeer.prototype.GetInlineEditor=function(){return AdfDhtmlNavigationItemTextEditor.getInlineEditor()};AdfDhtmlCommandNavigationItemPeer.prototype.ComponentTextChanged=function(a,b,c,d){if(d!=null&&(b=AdfDhtmlCommandNavigationItemPeer.getInlineEditableTextElement(a,b)))return AdfDomUtils.handleTextChangeWithAccessKey(a,b,c);return!1};
AdfDhtmlCommandNavigationItemPeer.getInlineEditableTextElement=function(a,b){AdfAssert.assert(a.getProperty("text")!=null);var c=AdfDomUtils.getFirstDescendentElement(b,"a");c||AdfAgent.AGENT.getNodeName(b).toLowerCase()=="a"&&(c=b);if(c)if(AdfDomUtils.getFirstDescendentElement(c,"img")){if(c=AdfDomUtils.getLastChildElement(c),c.tagName=="SPAN")return c}else return c;return null};
AdfDhtmlCommandNavigationItemPeer.prototype._isOnRemoveButton=function(a){var b=this.getComponent().getClientId(),b=AdfRichUIPeer.createSubId(b,AdfDhtmlCommandNavigationItemPeer._REMOVE_ICON_ID),a=a.getNativeEventTarget();if(a.id==b)return!0;return a.parentNode.id==b};
AdfDhtmlCommandNavigationItemPeer.prototype.canRemove=function(){var a=this.getComponent();if(a.getRemove){var b=a.getRemove();if(b&&(b=="no"||b=="disabled"))return!1}b=a.getParent();if(b.getItemRemoval==null)return!1;b=b.getItemRemoval();if(a.getDisabled()||b==null||b=="none")return!1;if(b=="all")return!0;if(b=="allExceptLast")return a=a.getClientId(),a=AdfRichUIPeer.createSubId(a,AdfDhtmlCommandNavigationItemPeer._REMOVE_ICON_ID),AdfAgent.getAgent().getElementById(a)!=null};
AdfDhtmlCommandNavigationItemPeer.prototype._saveAndRemoveCompressedLayout=function(){var a=this.getComponent().getParent(),b=a!=null?a.getPeer():null;b&&(b.bind(a),b&&b.__saveAndRemoveCompressedLayout&&b.__saveAndRemoveCompressedLayout())};AdfDhtmlCommandNavigationItemPeer.prototype._isDisabled=function(){var a=this.getDomElement();return a.disabled||AdfDomUtils.containsCSSClassName(a,AdfRichUIPeer.DISABLED_STYLECLASS)};
AdfUIComponents.createComponentClass("AdfUINavigationPath",{componentType:"org.apache.myfaces.trinidad.NavigationPath",propertyKeys:["value"],namingContainer:!0,superclass:AdfUICollection});
AdfUIComponents.createComponentClass("AdfRichBreadCrumbs",{componentType:"oracle.adf.RichBreadCrumbs",propertyKeys:[{name:"orientation",type:"String","default":"horizontal"},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0}],namingContainer:!0,superclass:AdfUINavigationPath});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlBreadCrumbsPeer",!1);AdfDhtmlBreadCrumbsPeer.prototype.InitDomElement=function(a,b){AdfDhtmlBreadCrumbsPeer.superclass.InitDomElement.call(this,a,b);var c=a.getClientId(),c=AdfRichUIPeer.CreateSubId(c,"oc");this._overflowContents=AdfAgent.AGENT.getElementById(c);AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a)};AdfDhtmlBreadCrumbsPeer.prototype.needsResizeNotify=function(){return!0};
AdfDhtmlBreadCrumbsPeer.prototype.ResizeNotify=function(){var a=this.getComponent();this.getDomElement();if(!this._overflowSupport){a=a.getClientId();if(!AdfOverflowSupport.needsOverflow(a))return;this._overflowSupport=new AdfOverflowSupport(a,this,"start","before");for(var a=this._overflowContents.childNodes,b,c=0;b=a[c++];)b.nodeType==1&&(b.tagName.toLowerCase()=="a"||b.getElementsByTagName("a").length>0?(this._overflowSupport.createStep(),b=this._createOverflowElement(b),c++,this._overflowSupport.addOverflowElement(b)):
(this._overflowSupport.createStep(),this._overflowSupport.addElement(b)))}this._overflowSupport.handleResize()};AdfDhtmlBreadCrumbsPeer.prototype.ComponentRemoved=function(a){delete this._overflowContents;this._overflowSupport&&(this._overflowSupport.removeOverflowSupport(),delete this._overflowSupport);AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a);AdfDhtmlBreadCrumbsPeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlBreadCrumbsPeer.prototype._createOverflowElement=function(a){var b=a.ownerDocument.createElement("div"),c=AdfDhtmlBreadCrumbsPeer._overflowElementStyleClass;if(c==null)c=AdfPage.PAGE.getLookAndFeel().getStyleClass("AFOverflowElement"),AdfDhtmlBreadCrumbsPeer._overflowElementStyleClass=c;b.className=c;a=this._overflowSupport.createSwapPosition(a);b.appendChild(a);return b};