AdfUIComponents.createComponentClass("AdfUIRegion",{componentType:"oracle.adf.Region",propertyKeys:["disclosureListener",{name:"disclosed",type:"Boolean","default":!0},{name:"immediate",type:"Boolean","default":!1},"value","regionNavigationListener"],eventNames:["regionRemoteRefresh","disclosure"],namingContainer:!0});
AdfUIComponents.createComponentClass("AdfRichRegion",{componentType:"oracle.adf.RichRegion",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"persist",type:"Array"},{name:"dontPersist",type:"Array"},{name:"showDisclosure",type:"Boolean","default":!0},{name:"maximized",type:"Boolean","default":!1},{name:"showMaximize",type:"String","default":"auto"},
"maximizeListener",{name:"contentDelivery",type:"String","default":"lazyUncached"},{name:"helpTopicId",type:"String"},{name:"text",type:"String"},{name:"showHeader",type:"String","default":"never"}],superclass:AdfUIRegion});
AdfRichRegion.prototype.isEventRoot=function(){return!0};AdfRichRegion.prototype.HandleBubbledEvent=function(a){!a.isPartial()&&!a.isCanceled()&&(a.getType()==AdfActionEvent.ACTION_EVENT_TYPE?a.isResponseExpected()&&(AdfPage.PAGE.addPartialTargets(this),a.setPartial(!0)):a.setPartial(!0));AdfRichRegion.superclass.HandleBubbledEvent.call(this,a)};
AdfRichUIPeer.createPeerClass(AdfDhtmlPanelBoxPeer,"AdfDhtmlRegionPeer",!1);AdfDhtmlRegionPeer._INNER_SD_PEER=AdfRichUIPeer.createInnerPeerClassWithSubId(AdfDhtmlShowDisclosurePeer,"InnerRegionShowDetailPeer",AdfDhtmlPanelBoxPeer.DISCLOSURE_SUB_ID);InnerRegionShowDetailPeer.InitSubclass=function(){AdfDhtmlTogglePeer.Config(this,{toggledStyleClass:"af|region::disclosed-icon-style",untoggledStyleClass:"af|region::undisclosed-icon-style"})};
InnerRegionShowDetailPeer.prototype.HandleClientSideToggle=function(a){if(this.outerThis.GetContentDomElement()&&InnerRegionShowDetailPeer.superclass.HandleClientSideToggle.call(this,a))return this.outerThis.__handleClientSideDisclosure(a),!0;return!1};AdfDhtmlPanelBoxPeer.MAXIMIZE_SUB_ID="_afrMax";AdfDhtmlRegionPeer._INNER_MAXIMIZE_PEER=AdfRichUIPeer.createInnerPeerClassWithSubId(AdfDhtmlMaximizePeer,"InnerRegionMaximizePeer",AdfDhtmlPanelBoxPeer.MAXIMIZE_SUB_ID);
InnerRegionMaximizePeer.InitSubclass=function(){AdfDhtmlTogglePeer.Config(this,{toggledStyleClass:"af|region::maximized-icon-style",untoggledStyleClass:"af|region::unmaximized-icon-style"})};InnerRegionMaximizePeer.prototype.HandleClientSideToggle=function(a){var b=this.outerThis,c=b.GetContentDomElement();if(c&&InnerRegionMaximizePeer.superclass.HandleClientSideToggle.call(this,a))return b.__handleClientSideMaximize(b.getDomElement(),c,a),!0;return!1};
InnerRegionMaximizePeer.prototype.ComponentMaximizedChanged=function(a,b,c,d){b=InnerRegionMaximizePeer.superclass.ComponentMaximizedChanged.call(this,a,b,c,d);c&&a.setDisclosed(!0);return b};InnerRegionMaximizePeer.prototype.EventPropagatesToServer=function(){return!this.outerThis.GetContentDomElement()};AdfDhtmlRegionPeer.prototype.CreateDisclosurePeer=function(a){return new AdfDhtmlRegionPeer._INNER_SD_PEER(a,this)};
AdfDhtmlRegionPeer.prototype.CreateMaximizePeer=function(a){return new AdfDhtmlRegionPeer._INNER_MAXIMIZE_PEER(a,this)};AdfDhtmlRegionPeer.prototype.InitDomElement=function(a,b){AdfDhtmlRegionPeer.superclass.InitDomElement.call(this,a,b);if(b.tagName=="DIV"){var c=this.GetContentDomElement(b),c=AdfDhtmlRegionPeer._getOnlyChildElement(c);this._stretchOnlyChild(b,c)}};
AdfDhtmlRegionPeer.prototype.DomReplaceNotify=function(a){var b=this.getDomElement();if(b.tagName=="DIV"){var c=this.GetContentDomElement();AdfDhtmlRegionPeer._getOnlyChildElement(c)==a&&this._stretchOnlyChild(b,a)}return a};AdfDhtmlRegionPeer.prototype.GetContentDomElement=function(a){var b=AdfDhtmlRegionPeer.superclass.GetContentDomElement.call(this,a);b||(a||(a=this.getDomElement()),b=a);return b};
AdfDhtmlRegionPeer.prototype.TruncateClientId=function(a,b,c,d){b=c.split(":");a=a.getClientId();a=AdfStrings.count(a,":")+1;(b=b[a])&&(isNaN(b)||d.push(a))};
AdfDhtmlRegionPeer._getOnlyChildElement=function(a){var b=null;if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++){var e=a[d],f=e.nodeType;if(f!=8)if(f==3){if(e.data.replace(/\s*/,"").length>0)return null}else if(f==1){if(e.style==null||e.style.display!="none"){if((e.id==null||e.id=="")&&(e.className==null||e.className=="")){if(AdfDomUtils.getNonWhitespaceChildCount(e)==0)continue;e=AdfDomUtils.getOnlyChildElement(e);if(e==null)return null;else{if(b)return null;b=e;continue}}if(b)return null;b=e}}else return null}return b};
AdfDhtmlRegionPeer.prototype._isRegionStretched=function(a){var b=!1,a=a.style;if(a!=null&&"absolute"==a.position){var c=a.width;if(c==a.height)if("100%"==c)b=!0;else if("auto"==c){var c=a.bottom,d=a.left,e=a.right;a.top!="auto"&&c!="auto"&&d!="auto"&&e!="auto"&&(b=!0)}}return b};AdfDhtmlRegionPeer.prototype._stretchOnlyChild=function(a,b){b!=null&&this._isRegionStretched(a)&&AdfAgent.getAgent().prepareStretchedChild(b,"0")};
AdfDhtmlRegionPeer.prototype.ConvertClientIdToLocator=function(a,b,c,d){a=a.getClientId();a=AdfStrings.count(a,":");d.push([a+1,null])};