AdfUIComponents.createComponentClass("AdfRichSelectBooleanCheckbox",{componentType:"oracle.adf.RichSelectBooleanCheckbox",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"readOnly",type:"Boolean","default":!1,secured:!0},
{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"text",type:"String"}],superclass:AdfUISelectBoolean});
AdfRichUIPeer.createPeerClass(AdfDhtmlEditableValuePeer,"AdfDhtmlSelectBooleanCheckboxPeer");
AdfDhtmlSelectBooleanCheckboxPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfRichSelectBooleanCheckbox);AdfRichUIPeer.addComponentPropertyGetters(this,AdfUIEditableValue.SUBMITTED_VALUE,AdfRichSelectBooleanCheckbox.TEXT);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE);AdfAgent.AGENT.getCapabilities()[AdfAgent.CAP_TOUCH_SCREEN]==AdfAgent.CAP_TOUCH_SCREEN_NONE&&AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,
AdfRichSelectBooleanCheckbox.TEXT);this._inlineEditor=null;this._SELECT_BOOLEAN_VALUE_KEY="_adfSbv"};AdfDhtmlSelectBooleanCheckboxPeer.prototype.HandleComponentMouseOver=function(a){this.ShowNoteWindowMouseOver(a)};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.HandleComponentClick=function(a){AdfDhtmlSelectBooleanCheckboxPeer.superclass.HandleComponentClick.call(this,a);var b=this.getComponent(),a=a.getNativeEventTarget();AdfAgent.AGENT.getNodeName(a)=="INPUT"&&(a&&a.checked?this.Validate(b,!0):this.Validate(b,!1))};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.GetSubmittedValue=function(a,b){var c=AdfDhtmlEditableValuePeer.GetContentNode(a,b);if(a.getReadOnly())return AdfAgent.AGENT.getAttribute(c,AdfDhtmlSelectBooleanCheckboxPeer._SELECT_BOOLEAN_VALUE_KEY);return c!=null&&c.checked?!0:!1};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.SetDisplayValue=function(a,b,c){b=AdfDhtmlEditableValuePeer.GetContentNode(a,b);if(b!=null)a.getReadOnly()?c=="true"||c==!0?(a=a.getText(),AdfAgent.AGENT.setTextContent(b,a)):AdfAgent.AGENT.setTextContent(b,""):b.checked=c=="true"||c==!0?!0:!1};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.GetInlineEditor=function(){var a=AdfDhtmlSelectBooleanCheckboxPeer._inlineEditor;if(a==null)a=new AdfDhtmlSelectBooleanTextEditor,AdfDhtmlSelectBooleanCheckboxPeer._inlineEditor=a;return a};AdfDhtmlSelectBooleanCheckboxPeer.prototype.GetComponentText=function(a,b){var c=AdfDhtmlSelectBooleanCheckboxPeer.__getInlineEditableTextElement(b);return c!=null?AdfAgent.AGENT.getTextContent(c):null};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.ComponentTextChanged=function(a,b,c){b=AdfDhtmlSelectBooleanCheckboxPeer.__getInlineEditableTextElement(b);return b!=null?AdfDomUtils.handleTextChangeWithAccessKey(a,b,c):!1};AdfDhtmlSelectBooleanCheckboxPeer.__getInlineEditableTextElement=function(a){for(var a=a.getElementsByTagName("LABEL"),b=a.length,c=0;c<b;c++){var d=a[c];if(d!=null&&d.parentNode.parentNode.className=="AFContentCell")return d}return null};
AdfUIComponents.createComponentClass("AdfRichSelectBooleanRadio",{componentType:"oracle.adf.RichSelectBooleanRadio",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"readOnly",type:"Boolean","default":!1,secured:!0},
{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"group",type:"String"},{name:"text",type:"String"}],superclass:AdfUISelectBoolean});
AdfRichUIPeer.createPeerClass(AdfDhtmlSelectBooleanCheckboxPeer,"AdfDhtmlSelectBooleanRadioPeer");AdfDhtmlSelectBooleanRadioPeer.prototype.HandleComponentClick=function(a){AdfDhtmlSelectBooleanRadioPeer.superclass.HandleComponentClick.call(this,a);var b=this.getComponent();(a=a.getNativeEventTarget())&&a.checked?this.Validate(b,!0):this.Validate(b,!1);this._validateUncheckedComponents(a)};
AdfDhtmlSelectBooleanRadioPeer.prototype._validateUncheckedComponents=function(a){var b=a.name;if(b!=""&&(a=AdfDomUtils.getFormElement(a).elements[b]))for(b=0;b<a.length;++b){var c=a[b];c.type=="radio"&&c.checked==!1&&(c=AdfRichUIPeer.getFirstAncestorComponent(c),c!=null&&(c.getSubmittedValue()==!0||c.getValue()==!0)&&this.Validate(c,!1))}};
AdfUIComponents.createComponentClass("AdfRichSelectManyCheckbox",{componentType:"oracle.adf.RichSelectManyCheckbox",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"readOnly",type:"Boolean","default":!1,secured:!0},
{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"valuePassThru",type:"Boolean","default":!1,secured:!0},{name:"layout",type:"String","default":"vertical"}],superclass:AdfUISelectMany});
AdfRichUIPeer.createPeerClass(AdfDhtmlSelectManyPeer,"AdfDhtmlSelectManyCheckboxPeer");AdfDhtmlSelectManyCheckboxPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyGetters(this,AdfUIEditableValue.SUBMITTED_VALUE,AdfUISelectMany.SELECT_ITEMS);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichSelectManyCheckbox.LABEL);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE)};
AdfDhtmlSelectManyCheckboxPeer.prototype.HandleComponentClick=function(a){AdfDhtmlSelectManyCheckboxPeer.superclass.HandleComponentClick.call(this,a);var b=this.getComponent(),a=a.getNativeEventTarget();AdfAgent.AGENT.getNodeName(a)=="INPUT"&&(a=this.GetSubmittedValue(b,a),this.Validate(b,a))};AdfDhtmlSelectManyCheckboxPeer.prototype.GetNoteWindowAlignmentHint=function(){return AdfRichPopup.ALIGN_BEFORE_START};
AdfDhtmlSelectManyCheckboxPeer.prototype.SetDisplayValue=function(a,b,c){AdfAssert.assertDomElement(b);AdfAssert.assertArray(c);if(a=this.GetCheckboxes(a,b))for(b=0;b<a.length;b++){var d=a[b],e=AdfCollections.indexOf(c,d.value);d.checked=e>=0}};AdfDhtmlSelectManyCheckboxPeer.prototype.GetLabelValue=function(a){return a.parentNode.nextSibling.firstChild.nodeValue};AdfDhtmlSelectManyCheckboxPeer.prototype.GetInlineEditor=function(){return AdfDhtmlSimpleLabelEditor.getInlineEditor()};
AdfUIComponents.createComponentClass("AdfRichSelectOneRadio",{componentType:"oracle.adf.RichSelectOneRadio",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"readOnly",type:"Boolean","default":!1,secured:!0},{name:"showRequired",
type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"valuePassThru",type:"Boolean","default":!1,secured:!0},{name:"layout",type:"String","default":"vertical"},{name:"unselectedLabel",type:"String"}],superclass:AdfUISelectOne});
AdfRichUIPeer.createPeerClass(AdfDhtmlSelectOnePeer,"AdfDhtmlSelectOneRadioPeer");AdfDhtmlSelectOneRadioPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyGetters(this,AdfUIEditableValue.SUBMITTED_VALUE,AdfUISelectOne.SELECT_ITEMS);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichSelectOneRadio.LABEL);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE);this._ITEM_VALUE_EXPANDO="_adfIV"};
AdfDhtmlSelectOneRadioPeer.prototype.HandleComponentClick=function(a){AdfDhtmlSelectOneRadioPeer.superclass.HandleComponentClick.call(this,a);a=this.getComponent();this.Validate(a,this.GetSubmittedValue(a,this.getDomElement()))};AdfDhtmlSelectOneRadioPeer.prototype.GetNoteWindowAlignmentHint=function(){return AdfRichPopup.ALIGN_BEFORE_START};
AdfDhtmlSelectOneRadioPeer.prototype.GetComponentSelectItems=function(a,b){var c=AdfDhtmlEditableValuePeer.GetContentNode(a,b);if(c!=null){var c=c.getElementsByTagName("input"),d=[];if(c!=null)for(var e=c.length,f=0;f<e;f++)d[f]=new AdfSelectItem,d[f].setValue(c[f].value),d[f].setLabel(c[f].text),d[f].setDisabled(c[f].disabled);return d}};
AdfDhtmlSelectOneRadioPeer.prototype.GetSubmittedValue=function(a,b){var c=AdfDhtmlEditableValuePeer.GetContentNode(a,b);if(a.getReadOnly())return c.getAttribute(AdfDhtmlSelectOneRadioPeer._ITEM_VALUE_EXPANDO);else for(var c=c.getElementsByTagName("input"),d=0;d<c.length;d++)if(c[d].checked)return c[d].value;return null};
AdfDhtmlSelectOneRadioPeer.prototype.SetDisplayValue=function(a,b,c){b=AdfDhtmlEditableValuePeer.GetContentNode(a,b);if(b!=null)if(a=a.getReadOnly(),AdfAssert.assertString(c),a)AdfAgent.AGENT.setTextContent(b,c);else if(a=b.getElementsByTagName("input"),a!=null)for(var b=a.length,d=0;d<b;d++)if(a[d].value==c)a[d].checked=!0};AdfDhtmlSelectOneRadioPeer.prototype.GetInlineEditor=function(){return AdfDhtmlSimpleLabelEditor.getInlineEditor()};