AdfUIComponents.createComponentClass("AdfRichPanelSplitter",{componentType:"oracle.adf.RichPanelSplitter",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"persist",type:"Array"},{name:"dontPersist",type:"Array"},{name:"dimensionsFrom",type:"String","default":"parent"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"orientation",
type:"String","default":"horizontal"},{name:"positionedFromEnd",type:"Boolean","default":!1},{name:"splitterPosition",type:"Number","default":200},{name:"collapsed",type:"Boolean","default":!1},{name:"firstBorder",type:"String","default":"skin"},{name:"secondBorder",type:"String","default":"skin"},{name:"firstLandmark",type:"String","default":"none"},{name:"secondLandmark",type:"String","default":"none"}],superclass:AdfUIPanel});
AdfRichPanelSplitter.HORIZONTAL_SPLIT="horizontal";AdfRichPanelSplitter.VERTICAL_SPLIT="vertical";
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelSplitterBasePeer",!1);
AdfDhtmlPanelSplitterBasePeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichPanelSplitter.SPLITTER_POSITION,AdfRichPanelSplitter.COLLAPSED);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE);this._DIVIDER_WIDTH=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelSplitter-tr-divider-size"),10);this._SPLITTER_PADDING_PIXELS="0px";this._MINIMUM_PANE_SIZE=0;this._PANEL_SPLITTER_COLLAPSE_ANIMATION_DURATION="af|panelSplitter-tr-collapse-animation-duration";
this._DISCLOSED_STATE="p_AFDisclosed";this._COLLAPSE_KEY="af_panelSplitter.TIP_COLLAPSE";this._RESTORE_KEY="af_panelSplitter.TIP_RESTORE";this._COLLAPSE_LABELED_SECTION_KEY="af_panelSplitter.TIP_COLLAPSE_LABELED_PANE";this._RESTORE_LABELED_SECTION_KEY="af_panelSplitter.TIP_RESTORE_LABELED_PANE"};
AdfDhtmlPanelSplitterBasePeer.prototype.BindToComponent=function(a,b){AdfDhtmlPanelSplitterBasePeer.superclass.BindToComponent.call(this,a,b);var c=a.getClientId(),d=AdfRichUIPeer.CreateSubId(c,"f"),e=AdfRichUIPeer.CreateSubId(c,"s"),f=AdfRichUIPeer.CreateSubId(c,"d"),g=AdfRichUIPeer.CreateSubId(c,"h"),c=AdfRichUIPeer.CreateSubId(c,"i"),h=AdfAgent.AGENT;this._firstDom=h.getElementById(d);this._secondDom=h.getElementById(e);this._dividerDom=h.getElementById(f);this._highlighterDom=h.getElementById(g);
this._iconDom=h.getElementById(c)};AdfDhtmlPanelSplitterBasePeer.prototype.ComponentSplitterPositionChanged=function(a){AdfPage.PAGE.doResizeNotify(a)};AdfDhtmlPanelSplitterBasePeer.prototype.ComponentCollapsedChanged=function(a,b,c){b=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(a);this._dividerDom.style.cursor=c?"default":"";this._handleCollapseAnimation(c,a,b)};AdfDhtmlPanelSplitterBasePeer.prototype.needsResizeNotify=function(){return!0};
AdfDhtmlPanelSplitterBasePeer.prototype.needsChildVisibilityChanges=function(){return!0};
AdfDhtmlPanelSplitterBasePeer.prototype.ResizeNotify=function(a,b,c,d){if(!this._collapseAnimator){var e=this.getComponent(),f=this._firstDom,g=this._secondDom,h=this._dividerDom,k=AdfDhtmlPanelSplitterBasePeer._isHorizontal(e),l=this._isDimensionsFromParent(),m=AdfDhtmlPanelSplitterBasePeer._isChildVisible(f),n=AdfDhtmlPanelSplitterBasePeer._isChildVisible(g),o=e.getCollapsed(),q=o?0:parseInt(e.getSplitterPosition(),10),e=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(e);if(!l&&k){if(!o)if(e){if(g!=
null)g.style.width=q+"px"}else if(f!=null)f.style.width=q+"px"}else if(!(m==!1&&n==!1)){var a=a!=c,b=b!=d,p=!(a||b);if(l)m!=n?this._resizeOnly(m?f:g,c,d,a,b):(e?(m=g,n=f):(m=f,n=g),(k?this._resizeHorizontal:this._resizeVertical).call(this,m,n,h,c,d,q,a,b,p,AdfDhtmlPanelSplitterBasePeer._DIVIDER_WIDTH,e),c=AdfDomUtils.getFirstChildElement(f),g=AdfDomUtils.getFirstChildElement(g),f=this._getPanePadding(f),q=AdfAgent.AGENT,q.resizeStretchedChild(c,f),q.resizeStretchedChild(g,f));else if(d=!e,h=null,
d&&n&&(h=f),!d&&m&&(h=g),h!=null&&this._resizeOnly(h,c,q,a,!1),m&&n&&!o)e?g.style.height=q+"px":f.style.height=q+"px"}}};
AdfDhtmlPanelSplitterBasePeer.prototype.DomReplaceNotify=function(a){var b=a.parentNode;if(b==this._firstDom||b==this._secondDom){var c=this.getComponent(),d=AdfDhtmlPanelSplitterBasePeer._isHorizontal(c);if(!this._isDimensionsFromParent()){if(d)return a;c=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(c);if(b==this._firstDom&&c)return a;if(b==this._secondDom&&!c)return a}var c=!1,d=AdfDomUtils.isVisible(b),e=AdfDomUtils.isVisible(a);e!=d&&(b!=this._getCollapsedPane()&&AdfDomUtils.setVisible(b,
e),this._repositionPanes(),c=!0);b=this._getPanePadding(b);d=AdfAgent.AGENT;d.prepareStretchedChild(a,b);if(!c)return d.resizeStretchedChild(a,b),a;return this.getDomElement()}return a};AdfDhtmlPanelSplitterBasePeer.prototype.ChildVisibilityChanged=function(a,b,c){a=b.parentNode;if(a==this._firstDom||a==this._secondDom)return a!=this._getCollapsedPane()&&AdfDomUtils.setVisible(a,c),AdfDomUtils.setVisible(b,c),this._repositionPanes(),AdfPage.PAGE.doResizeNotify(this.getComponent()),!0};
AdfDhtmlPanelSplitterBasePeer.prototype.__handleCollapseRestore=function(a){var b=a.getNativeEventTarget();if(AdfDomUtils.isAncestorOrSelf(this._iconDom,b)){var b=this.getComponent(),c=b.getCollapsed();b.setProperty(AdfRichPanelSplitter.COLLAPSED,!c,!0);AdfAgent.AGENT.eatEvent(a.getNativeEvent());return!0}return!1};
AdfDhtmlPanelSplitterBasePeer.prototype.HandleComponentKeyDown=function(a){if(!a.isCanceled()){var b=this.getComponent(),c=a.getNativeEventTarget(),d=a.getKeyCode();if(d==AdfKeyStroke.P_KEY){var e=a.getNativeEvent();e.ctrlKey&&e.altKey&&(this._handleSplitterNavigationEvent(a),a.cancel())}if(!b.getCollapsed()&&AdfDomUtils.isAncestorOrSelf(this._iconDom,c)){var c=parseInt(b.getSplitterPosition(),10),e=AdfDhtmlPanelSplitterBasePeer._isHorizontal(b),f=0;if(d==AdfKeyStroke.ARROWUP_KEY&&!e||d==AdfKeyStroke.ARROWLEFT_KEY&&
e)f=-5;else if(d==AdfKeyStroke.ARROWDOWN_KEY&&!e||d==AdfKeyStroke.ARROWRIGHT_KEY&&e)f=5;if(f!=0){AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(b)&&(f=-f);var d=this._isDimensionsFromParent(),g=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(b),d=this._getConstrainedSplitterPos(b,e,c+f,!d&&!e&&!g);b.setProperty(AdfRichPanelSplitter.SPLITTER_POSITION,d,!0);a.cancel()}}}};
AdfDhtmlPanelSplitterBasePeer.prototype._handleCollapseAnimation=function(a,b,c){var d=AdfDhtmlPanelSplitterBasePeer._isHorizontal(b),e=c?this._secondDom:this._firstDom,f=AdfDomUtils.getFirstChildElement(e),g=c?this._firstDom:this._secondDom,h,k=a?0:parseInt(b.getSplitterPosition(),10),l=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty(AdfDhtmlPanelSplitterBasePeer._PANEL_SPLITTER_COLLAPSE_ANIMATION_DURATION),10);isNaN(l)&&(l=0);var m=this;if(this._isDimensionsFromParent()){var n=f.style,o=
AdfDomUtils.getFirstChildElement(g),q=o.style,p=AdfDhtmlPanelSplitterBasePeer._DIVIDER_WIDTH,s,t,u,v=this.getDomElement(),w=d?v.clientWidth:v.clientHeight,y=this._dividerDom,A=g.style;a?(s=0,u=w-p+1):(s=k+1,u=w-k-p+1);d?(h="width",t="right"):(h="height",t="bottom");w=c?w-k-p:k;a?d?(n.width=this._getStyleWidth(f)+"px",q.width=v.clientWidth-p+1+"px",A.width=this._getStyleWidth(g)+"px"):(n.height=this._getStyleHeight(f)+"px",q.height=v.clientHeight-p+1+"px",A.height=this._getStyleHeight(g)+"px"):d?(n.width=
k+1+"px",q.width=this._getStyleWidth(o)+"px",A.width=v.clientWidth-p+1+"px"):(n.height=k+1+"px",q.height=this._getStyleHeight(o)+"px",A.height=v.clientHeight-p+1+"px");n[t]="";q[t]="";A[t]="";if(c)k=y.style,d?(k.left=y.offsetLeft+"px",k.right=""):(k.top=y.offsetTop+"px",k.bottom="");AdfDomUtils.setVisible(e,!0);k=[];n={element:e,properties:{}};n.properties[h]=s;k.push(n);n={element:g,properties:{}};n.properties[h]=u;c||(n.properties[d?"offsetLeft":"offsetTop"]=w+p-1);k.push(n);n={element:y,properties:{}};
n.properties[d?"offsetLeft":"offsetTop"]=w;k.push(n);this._collapseAnimator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,l,k,null,function(){m._afterCollapseAnimation(a,d,b,c,e,f,g,o,!0)},[],null)}else h=d?"width":"height",s=a?0:k,AdfDomUtils.setVisible(e,!0),p={element:e,properties:{}},p.properties[h]=s,this._collapseAnimator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,l,[p],null,function(){m._afterCollapseAnimation(a,
d,b,c,e,f,g,null,!1)},[],b)};
AdfDhtmlPanelSplitterBasePeer.prototype._afterCollapseAnimation=function(a,b,c,d,e,f,g,h,k){delete this._collapseAnimator;AdfDomUtils.setVisible(e,!a);e=AdfAgent.AGENT;(k||!b)&&e.prepareStretchedChild(f,"0px");k&&e.prepareStretchedChild(h,"0px");k&&!d&&(g.style[b?"right":"bottom"]="0px");AdfDomUtils.setVisible(this._highlighterDom,!1);this._updateDivider(a,d);k&&(g.style[b?"width":"height"]="");k&&d&&(this._dividerDom.style[b?"left":"top"]="");if(!k&&b&&e.getPlatform()==AdfAgent.IE_PLATFORM&&(a=e.getVersion(),
a>7&&a<9))a=this.getDomElement(),a.style.display="none",AdfPage.PAGE.scheduleTimer(this,this._afterTheAfterCollapseAnimationForIe,[a],1);AdfPage.PAGE.doResizeNotify(c)};AdfDhtmlPanelSplitterBasePeer.prototype._afterTheAfterCollapseAnimationForIe=function(a){a[0].style.display="";this._iconDom.focus()};
AdfDhtmlPanelSplitterBasePeer.prototype._getStyleHeight=function(a){var b=AdfAgent.AGENT.getComputedStyle(a);return a.offsetHeight-AdfAgent.getCSSLengthAsInt(b.borderTopWidth)-AdfAgent.getCSSLengthAsInt(b.borderBottomWidth)-AdfAgent.getCSSLengthAsInt(b.paddingTop)-AdfAgent.getCSSLengthAsInt(b.paddingBottom)};
AdfDhtmlPanelSplitterBasePeer.prototype._getStyleWidth=function(a){var b=AdfAgent.AGENT.getComputedStyle(a);return a.offsetWidth-AdfAgent.getCSSLengthAsInt(b.borderLeftWidth)-AdfAgent.getCSSLengthAsInt(b.borderRightWidth)-AdfAgent.getCSSLengthAsInt(b.paddingLeft)-AdfAgent.getCSSLengthAsInt(b.paddingRight)};
AdfDhtmlPanelSplitterBasePeer.prototype._handleSplitterNavigationEvent=function(a){var b=a.getNativeEventTarget(),c=AdfRichUIPeer.getFirstAncestorComponent(b);c&&c instanceof AdfRichPanelSplitter?(c=c.getPeer(),AdfDomUtils.isAncestorOrSelf(c._iconDom,b)?(c=c._secondDom,b=!1):(c=document.body,b=!0)):(c=document.body,b=!0);c=this._findNextSplitter(c);!c&&!b&&(c=this._findNextSplitter(document.body));c&&(c.focus(),a.cancel())};
AdfDhtmlPanelSplitterBasePeer.prototype._findNextSplitter=function(a){for(var b=AdfDomUtils.isVisible,c=AdfAgent.AGENT.isElementHTML,d=AdfRichUIPeer.getFirstAncestorComponent,e=/::i$/;;){if(a.hasChildNodes()&&b(a))a=a.firstChild;else for(;;){var f=a,a=f.nextSibling;if(a==null){if(a=f.parentNode,a==null)return null}else break}var g,h;if(a.nodeType==1&&c(a)&&b(a)&&a.nodeName=="A"&&a.id&&e.test(a.id)&&(g=d(a))&&g instanceof AdfRichPanelSplitter&&(h=g.getPeer())&&h._iconDom==a)return h._iconDom}};
AdfDhtmlPanelSplitterBasePeer.prototype._getConstrainedSplitterPos=function(a,b,c,d){a=this.getDomElement();b=(b?a.clientWidth:a.clientHeight)-AdfDhtmlPanelSplitterBasePeer._DIVIDER_WIDTH-AdfDhtmlPanelSplitterBasePeer._MINIMUM_PANE_SIZE;c=Math.max(c,AdfDhtmlPanelSplitterBasePeer._MINIMUM_PANE_SIZE);d||(c=Math.min(c,b));return c};AdfDhtmlPanelSplitterBasePeer.prototype._getPanePadding=function(a){a=a.style.paddingTop;a==""&&(a="0px");return a};
AdfDhtmlPanelSplitterBasePeer.prototype._handleTouchMovement=function(a,b){this._handleDrag(null,a,b);this._handleDrop(null,a,b)};
AdfDhtmlPanelSplitterBasePeer.prototype._handleDrag=function(a,b,c){var d,a=this.getComponent(),e=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(a),f=AdfDhtmlPanelSplitterBasePeer._isHorizontal(a),g=null;if(f){if(b==0)return;c=b;b=e?"right":"left"}else{if(c==0)return;b=e?"bottom":"top"}var h=this._isDimensionsFromParent();if(h)g=this._dividerDom.style;else if(this._flowDividerDom==null){var g=AdfAgent.AGENT,k=this._highlighterDom.cloneNode(!0),d=k.ownerDocument.createElement("div");d.className=
this._dividerDom.className;var l=this._dividerDom.offsetHeight,m=d.style;m.position="absolute";m.height=l+"px";f?m.width=this._dividerDom.style.width:(m.left="0px",m.right="0px");d.appendChild(k);g.disableUserSelect(d);this._highlighterDom.style.visibility="hidden";g.removeIdsFromDomSubTree(d);g=d.style;!f&&e?(b="top",g[b]=this._firstDom.offsetHeight+"px"):(k=a.getCollapsed()?0:parseInt(a.getSplitterPosition(),10),g[b]=k+"px");k=this.getDomElement();k.insertBefore(d,k.firstChild);this._flowDividerDom=
d}else!f&&e&&(b="top"),AdfDomUtils.setVisible(this._flowDividerDom,!0),g=this._flowDividerDom.style;d=parseInt(g[b],10);!h&&!f&&e?(c=d+c,e=(a.getCollapsed()?0:parseInt(a.getSplitterPosition(),10))+this._firstDom.offsetHeight,a=this._getConstrainedSplitterPos(a,f,e-c,!1),g[b]=e-a+"px"):(a=this._getConstrainedSplitterPos(a,f,e?d-c:d+c,!h&&!f&&!e),g[b]=a+"px")};
AdfDhtmlPanelSplitterBasePeer.prototype._handleDrop=function(){this._dragging=!1;AdfDomUtils.setVisible(this._iconDom,!0);var a,b=this.getComponent(),c=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(b),d=AdfDhtmlPanelSplitterBasePeer._isHorizontal(b),e=this._isDimensionsFromParent(),a=d?c?"right":"left":c?"bottom":"top",f;if(e)f=this._dividerDom.style;else if(this._flowDividerDom!=null)f=this._flowDividerDom.style,AdfDomUtils.setVisible(this._flowDividerDom,!1);else return;!e&&!d&&c?(a=parseInt(f.top,
10),a=(b.getCollapsed()?0:parseInt(b.getSplitterPosition(),10))+this._firstDom.offsetHeight-a):a=parseInt(f[a],10);if(this._flowDividerDom!=null)this._highlighterDom.style.visibility="visible",this._flowDividerDom.parentNode.removeChild(this._flowDividerDom),this._flowDividerDom=null;b.setProperty(AdfRichPanelSplitter.SPLITTER_POSITION,a,!0)};
AdfDhtmlPanelSplitterBasePeer.prototype._repositionPanes=function(){var a=AdfAgent.AGENT,b=this._firstDom,c=this._secondDom,d=this._dividerDom,e=AdfDhtmlPanelSplitterBasePeer._isChildVisible(b),f=AdfDhtmlPanelSplitterBasePeer._isChildVisible(c);AdfDomUtils.setVisible(d,e&&f);if(this._isDimensionsFromParent())e!=f?(d=AdfDhtmlPanelSplitterBasePeer._SPLITTER_PADDING_PIXELS,a.repositionStretchedElement(e?b:c,d,d,d,d)):(d=this.getComponent(),e=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(d),d=AdfDhtmlPanelSplitterBasePeer._isHorizontal(d),
a.removeStyleProperty(e?c:b,d?e?"left":"right":e?"top":"bottom"))};AdfDhtmlPanelSplitterBasePeer.prototype._resizeHorizontal=function(a,b,c,d,e,f,g,h,k,l,m){var n=AdfAgent.AGENT;k&&(n.setOuterWidth(a,f+1),m=m?"right":"left",c.style[m]=f+"px",b.style[m]=f+l-1+"px");if(k||g)d=Math.max(0,d-f-l),n.resizeStretchedElement(b,d);h&&(n.resizeStretchedElement(a,void 0,e),n.resizeStretchedElement(b,void 0,e),n.resizeStretchedElement(c,void 0,e))};
AdfDhtmlPanelSplitterBasePeer.prototype._resizeVertical=function(a,b,c,d,e,f,g,h,k,l,m){var n=AdfAgent.AGENT;k&&(n.setOuterHeight(a,f+1),m=m?"bottom":"top",c.style[m]=f+"px",b.style[m]=f+l-1+"px");if(k||h)e=Math.max(0,e-f-l),n.resizeStretchedElement(b,void 0,e);g&&(n.resizeStretchedElement(a,d,void 0),n.resizeStretchedElement(b,d,void 0),n.resizeStretchedElement(c,d,void 0))};
AdfDhtmlPanelSplitterBasePeer.prototype._resizeOnly=function(a,b,c){var d=AdfAgent.AGENT;d.resizeStretchedElement(a,b,c);b=AdfDomUtils.getFirstChildElement(a);a=this._getPanePadding(a);d.resizeStretchedChild(b,a)};AdfDhtmlPanelSplitterBasePeer.prototype._getCollapsedPane=function(){var a=this.getComponent();if(a.getCollapsed())return AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(a)?this._secondDom:this._firstDom;return null};
AdfDhtmlPanelSplitterBasePeer.prototype._updateDivider=function(a,b){var c,d=this.getComponent(),c=AdfDhtmlPanelSplitterBasePeer._isHorizontal(d)?b?a?"af|panelSplitter::horizontal-collapse-icon":"af|panelSplitter::horizontal-restore-icon":a?"af|panelSplitter::horizontal-restore-icon":"af|panelSplitter::horizontal-collapse-icon":b?a?"af|panelSplitter::vertical-collapse-icon":"af|panelSplitter::vertical-restore-icon":a?"af|panelSplitter::vertical-restore-icon":"af|panelSplitter::vertical-collapse-icon";
AdfDomUtils.addOrRemoveCSSClassName(!a,this._dividerDom,AdfDhtmlPanelSplitterBasePeer._DISCLOSED_STATE);var e=this._iconDom,f=AdfDomUtils.getFirstChildElement(e);AdfDomUtils.swapIcon(f,c);c=AdfDomUtils.getFirstChildElement(e);d=AdfDhtmlPanelSplitterBasePeer._getCollapseIconTooltipText(d,a,b);e.title=d;if(c.tagName=="IMG")c.alt=d;c.title=d};
AdfDhtmlPanelSplitterBasePeer.prototype.ComponentRemoved=function(a){this._touchMoveManager&&this._touchMoveManager.unregister();AdfDhtmlPanelSplitterBasePeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlPanelSplitterBasePeer.prototype._isDimensionsFromParent=function(){if(this._dimensionsFromParent==null){var a=null;this._dividerDom!=null?a=AdfAgent.AGENT.getComputedStyle(this._dividerDom):a==null&&this._firstDom!=null?a=AdfAgent.AGENT.getComputedStyle(this._firstDom):a==null&&this._secondDom!=null&&(a=AdfAgent.AGENT.getComputedStyle(this._secondDom));this._dimensionsFromParent=a.position=="absolute"}return this._dimensionsFromParent};
AdfDhtmlPanelSplitterBasePeer._isChildVisible=function(a){if(a==null)return!1;a=AdfDomUtils.getFirstChildElement(a);return AdfDomUtils.isVisible(a)};AdfDhtmlPanelSplitterBasePeer._isHorizontal=function(a){return a.getOrientation()!=AdfRichPanelSplitter.VERTICAL_SPLIT};AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd=function(a){var b=a.getPositionedFromEnd();AdfDhtmlPanelSplitterBasePeer._isHorizontal(a)&&AdfPage.PAGE.getLocaleContext().isRightToLeft()&&(b=!b);return b};
AdfDhtmlPanelSplitterBasePeer._getCollapseIconTooltipText=function(a,b,c){var d=AdfPage.PAGE.getLookAndFeel(),e=a.getFirstLandmark(),a=a.getSecondLandmark();return!c&&e!="none"?(b=b?AdfDhtmlPanelSplitterBasePeer._RESTORE_LABELED_SECTION_KEY:AdfDhtmlPanelSplitterBasePeer._COLLAPSE_LABELED_SECTION_KEY,d.getTranslatedString(b,e)):c&&a!="none"?(b=b?AdfDhtmlPanelSplitterBasePeer._RESTORE_LABELED_SECTION_KEY:AdfDhtmlPanelSplitterBasePeer._COLLAPSE_LABELED_SECTION_KEY,d.getTranslatedString(b,a)):(b=b?AdfDhtmlPanelSplitterBasePeer._RESTORE_KEY:
AdfDhtmlPanelSplitterBasePeer._COLLAPSE_KEY,d.getTranslatedString(b))};
AdfRichUIPeer.createPeerClass(AdfDhtmlPanelSplitterBasePeer,"AdfDhtmlPanelSplitterPeer",!1);AdfDhtmlPanelSplitterPeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE,AdfUIInputEvent.MOUSE_OUT_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE)};AdfDhtmlPanelSplitterPeer.prototype.HandleComponentClick=function(a){this.__handleCollapseRestore(a)};
AdfDhtmlPanelSplitterPeer.prototype.HandleComponentMouseOver=function(a){this.getComponent().getCollapsed()||(a=a.getNativeEventTarget(),AdfDomUtils.isAncestorOrSelf(this._dividerDom,a)&&AdfDomUtils.setVisible(this._highlighterDom,!0))};AdfDhtmlPanelSplitterPeer.prototype.HandleComponentMouseOut=function(a){this._dragging||(a=a.getNativeEventTarget(),AdfDomUtils.isAncestorOrSelf(this._dividerDom,a)&&AdfDomUtils.setVisible(this._highlighterDom,!1))};
AdfDhtmlPanelSplitterPeer.prototype.HandleComponentMouseDown=function(a){if(!this.getComponent().getCollapsed()){var b=a.getNativeEventTarget();if(AdfDomUtils.isAncestorOrSelf(this._dividerDom,b)&&!AdfDomUtils.isAncestorOrSelf(this._iconDom,b))AdfDomUtils.setVisible(this._iconDom,!1),a=a.getNativeEvent(),AdfPage.PAGE.startDrag(a,this.createCallback(this._handleDrag),this.createCallback(this._handleDrop),void 0,!0),this._dragging=!0;return!1}};
function AdfDashboardDropTarget(a){this.Init(AdfDnDContext.ACTION_MOVE,a)}AdfObject.createSubclass(AdfDashboardDropTarget,AdfStampedDropTarget);AdfDashboardDropTarget.prototype.Init=function(a,b){AdfDashboardDropTarget.superclass.Init.call(this,a);this._allowedFlavors=b};AdfDashboardDropTarget.prototype.GetAllowedFlavors=function(){return this._allowedFlavors};
AdfDashboardDropTarget.prototype.AcceptDragOverrideIfRejectedByFlavor=function(a,b){var c=a.getDragSource().getComponent();if(c&&c.getParent()==this.getComponent()&&this.GetAllowedActions()&b)return b;return AdfDnDContext.ACTION_NONE};AdfDashboardDropTarget.prototype.NeedsRowKeyCollectionCheck=function(){return!1};
AdfDashboardDropTarget.prototype.DropOnRowKey=function(a,b,c,d,e,f){AdfLogger.LOGGER.fine("Queing Drop Event with desired drop index:",e);AdfAssert.assertString(e);var e=parseInt(e),g=this.getComponent(),h=a.getDragSource(),k=a.getDragSource().getComponent(),k=g.getPeer().getDraggedSourceChildIndex(k,!1);return e==k?AdfDnDContext.ACTION_NONE:((new AdfDropEvent(g,h,a.getTransferable(),b,c,d,f,"children",e)).queue(),b)};
AdfUIComponents.createComponentClass("AdfRichPanelDashboard",{componentType:"oracle.adf.RichPanelDashboard",propertyKeys:[{name:"dimensionsFrom",type:"String","default":"parent"},{name:"columns",type:"Number","default":3},{name:"rowHeight",type:"String","default":"100px"},"dropListener",{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelDashboardPeer",!1);AdfDhtmlPanelDashboardPeer.InitSubclass=function(){this._INSERT_DELETE_PIXEL_HEIGHT="40";this._PHASE_2_DURATION_FACTOR=this._PHASE_1_DURATION_FACTOR=0.5};AdfDhtmlPanelDashboardPeer.prototype.InitDomElement=function(a){var b=a.getProperty("_allowedFlavors"),c=[];b!=null&&b.length>0&&(c=eval(b));a.setDropTarget(new AdfDashboardDropTarget(c))};AdfDhtmlPanelDashboardPeer.prototype.needsResizeNotify=function(){return!0};
AdfDhtmlPanelDashboardPeer.prototype.ResizeNotify=function(a,b,c){delete this._cachedChildWidthInPixels;delete this._cachedChildHeightInPixels;this._workaroundForInternetExplorer(c)};AdfDhtmlPanelDashboardPeer.prototype.ComponentRemoved=function(){this._animator!=null&&this._animator.stop()};
AdfDhtmlPanelDashboardPeer.prototype.DomReplaceNotify=function(a){if(a.id.indexOf("optRnd")>0){if(this._animator!=null){var b=this._animator.stop();this._processingOptimizedChanges&&b!=null&&b.length==2&&this._deleteElements(b[1],!0)}this._processingOptimizedChanges=!0;for(var c=AdfAgent.AGENT,d=this.__getDataBody(),b=AdfDomUtils.getChildElements(d),e=b.length,f=[],g=0,h,k,h=0;h<e;h++)k=AdfDomUtils.getFirstChildElement(b[h]),k==null||k.name=="afrPlaceholder"?(f[h]="placeholder",g++):f[h]="existing";
e=c.getAttribute(a,"afrDel");if(e!=null){e=eval(e);e.sort(AdfDhtmlPanelDashboardPeer._sortAscending);for(h=k=0;h<f.length;h++)f[h]=="existing"&&(AdfDhtmlPanelDashboardPeer._arrayContains(e,k)&&(f[h]="delete"),k++)}k=AdfDomUtils.getChildElements(a);e=k.length;h=parseInt(c.getAttribute(a,"afrIns"));if(e>0&&(isNaN(h)||h!=e))AdfLogger.LOGGER.severe("Error - the panelDashboard was told to expect "+h+" inserted "+(h==1?"child":"children")+" but "+e+" were sent.");if(g!=0||e!=0){g=[];for(h=0;h<e;h++)g.push(parseInt(c.getAttribute(k[h],
"afrIns")));g.sort(AdfDhtmlPanelDashboardPeer._sortAscending);for(var c=d.ownerDocument,l=k=0,h=0;h<f.length;h++)if(f[h]!="delete")if(f[h]=="placeholder")AdfDhtmlPanelDashboardPeer._arrayContains(g,k)?(l++,k++):(f.splice(h,1),d.removeChild(b[h]),b=AdfDomUtils.getChildElements(d),h--);else{if(AdfDhtmlPanelDashboardPeer._arrayContains(g,k)){f.splice(h,0,"placeholder");var m=c.createElement("div"),n=m.style;n.position="absolute";n.overflow="hidden";n.width="1px";n.height=AdfDhtmlPanelDashboardPeer._INSERT_DELETE_PIXEL_HEIGHT+
"px";h<b.length?d.insertBefore(m,b[h]):d.appendChild(m);b=AdfDomUtils.getChildElements(d);l++}k++}for(;l<e;)f.push("placeholder"),g=c.createElement("div"),k=g.style,k.position="absolute",k.overflow="hidden",k.width="1px",k.height=AdfDhtmlPanelDashboardPeer._INSERT_DELETE_PIXEL_HEIGHT+"px",h++<b.length?d.insertBefore(g,b[h++]):d.appendChild(g),b=AdfDomUtils.getChildElements(d),l++}d=[];for(h=0;h<f.length;h++)f[h]=="placeholder"&&d.push(b[h]);for(h=0;h<e;h++){c=d[h];for(g=AdfDomUtils.getFirstChildElement(c);g;)c.removeChild(g),
g=AdfDomUtils.getFirstChildElement(c);g=AdfDomUtils.getFirstChildElement(a);k=AdfDomUtils.getFirstChildElement(g);a.removeChild(g);g.removeChild(k);c.appendChild(k)}d=[];for(h=0;h<f.length;h++)f[h]=="delete"&&d.push(b[h]);var n=AdfPage.PAGE.getLocaleContext().isRightToLeft(),o=this.getComponent(),c=o.getColumns(),g=this._getChildWidthInPixels(o),k=this._getChildHeightInPixels(o),q=0,l=[];if(f.length>b.length)AdfLogger.LOGGER.severe("ERROR - Mismatch among metaData "+f.length+" and dataBodyChildren "+
b.length);else{for(h=m=0;h<f.length;h++){var p=q%c,s=Math.floor(q/c),t=b[h];this._preventDiagonalMovement(t,p,s,c,g,k,n);f[h]=="delete"?s={element:t,properties:{height:AdfDhtmlPanelDashboardPeer._INSERT_DELETE_PIXEL_HEIGHT,offsetLeft:p*g,offsetTop:s*k}}:(++m,s={element:t,properties:{width:g,offsetLeft:p*g,offsetTop:s*k}});if(n)t.style.left=t.offsetLeft+"px",t.style.right="auto",s.properties.offsetLeft=(c-1-p)*g;l.push(s);q++}h=o.getClientId();AdfDhtmlPanelDashboardPeer._adjustShim(l,h,c,k,m);n=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelDashboard-tr-insert-delete-animation-duration"));
n=isNaN(n)?0:Math.round(n*AdfDhtmlPanelDashboardPeer._PHASE_1_DURATION_FACTOR);o=null;AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren(h)&&(o=this.getComponent());this._animator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,n,l,null,AdfDhtmlPanelDashboardPeer._domReplaceNotifyPhase2,[this,d,f,b,c,g,k,e,h,m],o)}}return a};
AdfDhtmlPanelDashboardPeer._domReplaceNotifyPhase2=function(a){for(var b=a[0],c=a[1],d=a[2],e=a[3],f=a[4],g=a[5],h=a[6],k=a[7],l=a[8],m=a[9],a=[],n=0,o=AdfPage.PAGE.getLocaleContext().isRightToLeft(),q,q=0;q<d.length;q++){var p=e[q],s;if(d[q]=="delete"){if(s={element:p,properties:{width:1}},o){var t=p.offsetLeft;p.style.left=t+"px";p.style.right="auto";s.properties.offsetLeft=t+g}}else{t=n%f;s=Math.floor(n/f);b._preventDiagonalMovement(p,t,s,f,g,h,o);s={element:p,properties:{height:h,offsetLeft:t*
g,offsetTop:s*h}};if(o)p.style.left=p.offsetLeft+"px",p.style.right="auto",s.properties.offsetLeft=(f-1-t)*g;n++}a.push(s)}if(k==1&&c.length==0)for(q=e=0;q<d.length;q++)if(d[q]=="placeholder"){d=h*Math.floor(e/f);e=b.getDomElement();a.push({element:e,properties:{scrollTop:d}});break}else d[q]!="delete"&&e++;AdfDhtmlPanelDashboardPeer._adjustShim(a,l,f,h,m);f=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelDashboard-tr-insert-delete-animation-duration"));f=isNaN(f)?0:Math.round(f*AdfDhtmlPanelDashboardPeer._PHASE_2_DURATION_FACTOR);
h=null;AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren(l)&&(h=b.getComponent());b._animator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,f,a,null,AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles,[b,c],h)};AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren=function(a){a=AdfRichUIPeer.CreateSubId(a,"shim");return AdfAgent.AGENT.getElementById(a)!=null};
AdfDhtmlPanelDashboardPeer._adjustShim=function(a,b,c,d,e){b=AdfRichUIPeer.CreateSubId(b,"shim");b=AdfAgent.AGENT.getElementById(b);if(b!=null)c=Math.ceil(e/c)*d,a==null?b.style.height=c+"px":a.push({element:b,properties:{height:c}})};
AdfDhtmlPanelDashboardPeer.prototype.insertChildBehavior=function(a,b){var c=this.__getDataBody(),d=AdfDomUtils.getChildElements(c),e=d.length,f=a.getColumns(),g=this._getChildWidthInPixels(a),h=this._getChildHeightInPixels(a);b==-1&&(b=e);var k=b%f,l=Math.floor(b/f),m=c.ownerDocument,n=m.createElement("div"),o=n.style,q=l*h;o.position="absolute";o.top=q+"px";var p=AdfPage.PAGE.getLocaleContext().isRightToLeft();p?(o.right="auto",o.left=(f-1-k)*g+"px"):o.left=k*g+"px";o.overflow="hidden";o.width=
"1px";o.height=AdfDhtmlPanelDashboardPeer._INSERT_DELETE_PIXEL_HEIGHT+"px";b<d.length?c.insertBefore(n,d[b]):c.appendChild(n);d=AdfDomUtils.getChildElements(c);k=m.createElement("div");k.name="afrPlaceholder";l=k.style;l.position="absolute";l.top="2px";l.bottom="2px";l.left="2px";l.right="2px";l.padding="4px";l.borderWidth="1px";l.borderStyle="solid";l.borderColor="#CCCCCC";n.appendChild(k);k.appendChild(m.createTextNode(" "));m=[];m.push({element:n,properties:{width:g}});for(n=1+b;n<=e;n++){k=n%
f;l=Math.floor(n/f);c=d[n];this._preventDiagonalMovement(c,k,l,f,g,h,p);l={element:c,properties:{offsetLeft:k*g,offsetTop:l*h}};if(p)c.style.left=c.offsetLeft+"px",c.style.right="auto",l.properties.offsetLeft=(f-1-k)*g;m.push(l)}d=a.getClientId();AdfDhtmlPanelDashboardPeer._adjustShim(m,d,f,h,1+e);e=this.getDomElement();m.push({element:e,properties:{scrollTop:q}});q=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelDashboard-tr-insert-delete-animation-duration"));q=isNaN(q)?0:Math.round(q*
AdfDhtmlPanelDashboardPeer._PHASE_1_DURATION_FACTOR);e=null;AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren(d)&&(e=this.getComponent());this._animator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,q,m,null,AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles,[this,null],e)};
AdfDhtmlPanelDashboardPeer.prototype.showDragFeedback=function(a,b,c,d,e,f,g){AdfAssert.assertPrototype(a,AdfDnDContext);AdfAssert.assertStringOrNull(b);AdfAssert.assertNumber(c);AdfAssert.assertStringOrNull(d);e=a.getDragSource().getComponent();a=this.getComponent();e=this.getDraggedSourceChildIndex(e,!0);f=AdfRichUIPeer.CreateSubId(a.getClientId(),"drpt");f=AdfAgent.AGENT.getElementById(f);if(g&&c==AdfDnDContext.ACTION_NONE)AdfDomUtils.removeCSSClassName(f,"p_AFDropTarget"),this._animateReorderPositionTo(a,
e,null);else if(d!=b)if(c=null,b!=null){var c=parseInt(b),h=a.getColumns(),b=this._getChildWidthInPixels(a),d=this._getChildHeightInPixels(a),k=Math.max(0,c%h),g=k*b,l=Math.max(0,Math.floor(c/h))*d;AdfPage.PAGE.getLocaleContext().isRightToLeft()&&(g=(h-1-k)*b);g+=4;l+=4;h=f.style;h.width=b+"px";h.height=d+"px";h.left=g+"px";h.top=l+"px";AdfDomUtils.addCSSClassName(f,"p_AFDropTarget");this._animateReorderPositionTo(a,e,c)}else d!=null&&(AdfDomUtils.removeCSSClassName(f,"p_AFDropTarget"),e!=null&&(this._animator!=
null&&this._animator.stop(),AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles([this,null],e,parseInt(d))))};
AdfDhtmlPanelDashboardPeer.prototype.getRowKeyBounds=function(a){if(a==null)return null;var b=this.__getDataBody(),c=AdfDomUtils.getChildElements(b).length,a=parseInt(a);if(a<c){var d=this.getComponent(),e=d.getColumns(),c=a%e,e=Math.floor(a/e),a=this._getChildWidthInPixels(d),d=this._getChildHeightInPixels(d);c*=a;e*=d;var f=AdfAgent.AGENT.getElementPageBounds(b);f.left+=c-b.scrollLeft;f.right=f.left+a;f.top+=e-b.scrollTop;f.bottom=f.top+d;return f}return null};
AdfDhtmlPanelDashboardPeer.prototype.getRowKeyAndOrientationFromHints=function(a,b,c){AdfAssert.assertNumber(a);AdfAssert.assertNumber(b);AdfAssert.assert(c!=null);var d=c[AdfStampedDropTarget.HINT_LAST_ROWKEY],e=c[AdfStampedDropTarget.HINT_LAST_ROWKEY_BOUNDS],f=c[AdfStampedDropTarget.HINT_LAST_DROP_ORIENTATION];if(d&&e&&(AdfAssert.assertString(d),AdfAssert.assertObject(e),a>=e.left&&b>=e.top&&a<=e.right&&b<=e.bottom)){c[AdfStampedDropTarget.ROW_KEY]=d;c[AdfStampedDropTarget.DROP_ORIENTATION]=f;return}d=
!0;e=AdfPage.PAGE.getDnDContext();e!=null&&(e=e.getDragSource().getComponent(),f=this.getComponent(),e.getParent()==f&&(d=!1));this._getRowKeyAndOrientationForPosition(a,b,c,d)};
AdfDhtmlPanelDashboardPeer.prototype.getDraggedSourceChildIndex=function(a,b){var c=this.__getDataBody(),c=AdfDomUtils.getChildElements(c),d=c.length,e=a.getClientId();if(!b&&this._draggedSourceClientId==e)return this._draggedSourceIndex;else{this._draggedSourceClientId=e;for(var f=null,g=0;g<d;g++){var h=AdfDomUtils.getFirstChildElement(c[g]);if(h&&e==AdfAgent.AGENT.getAttribute(h,"id")){f=g;break}}return this._draggedSourceIndex=f}};
AdfDhtmlPanelDashboardPeer._sortAscending=function(a,b){return a-b};AdfDhtmlPanelDashboardPeer._arrayContains=function(a,b){for(var c,d=a.length,c=0;c<d;c++)if(a[c]==b)return!0;return!1};
AdfDhtmlPanelDashboardPeer.prototype._getDispayDropIndexFromCoordinates=function(a,b,c,d,e){var f=AdfAgent.AGENT;if(f.pointInElementBounds(this.getDomElement(),c,d)){var c=c-document.documentElement.scrollLeft-f.getElementLeft(b)+b.scrollLeft,d=d-f.getElementTop(b)+b.scrollTop,g=this._getChildWidthInPixels(a),f=this._getChildHeightInPixels(a),a=a.getColumns(),c=Math.floor(c/g);AdfPage.PAGE.getLocaleContext().isRightToLeft()&&(c=a-1-c);a=Math.floor(d/f)*a+c;b=AdfDomUtils.getChildElements(b).length;
e||b--;return""+Math.min(b,a)}return null};AdfDhtmlPanelDashboardPeer.prototype._getRowKeyAndOrientationForPosition=function(a,b,c,d){AdfAssert.assertNumber(a);AdfAssert.assertNumber(b);var e=this.__getDataBody(),a=this._getDispayDropIndexFromCoordinates(this.getComponent(),e,a,b,d);c[AdfStampedDropTarget.ROW_KEY]=a!=null?a:null;c[AdfStampedDropTarget.DROP_ORIENTATION]=AdfDropEvent.DROP_ORIENTATION_INSIDE};
AdfDhtmlPanelDashboardPeer.prototype.__getDataBody=function(){var a=this.getDomElement(),a=AdfDomUtils.getFirstChildElement(a);AdfAssert.assertDomElement(a);return a};
AdfDhtmlPanelDashboardPeer.prototype._animateReorderPositionTo=function(a,b,c){this._animator!=null&&this._animator.stop();var d=this.__getDataBody(),e=AdfDomUtils.getChildElements(d),f=e.length;if(f!=0){for(var d=[],g=a.getColumns(),h=this._getChildWidthInPixels(a),k=this._getChildHeightInPixels(a),l=c==null,m=0;m<f;m++){var n=e[m],o={};if(m==b)n.style.display=l?"":"none";if(m!=b){var q=m;l||(b!=null&&q>b&&q--,q>=c&&q++);var p=q%g,q=Math.floor(q/g),s=AdfPage.PAGE.getLocaleContext().isRightToLeft();
s?(n.style.left=n.offsetLeft+"px",n.style.right="auto",o.offsetLeft=(g-1-p)*h):o.offsetLeft=p*h;this._preventDiagonalMovement(n,p,q,g,h,k,s);o.offsetTop=q*k}d[m]={element:n,properties:o}}var t,u,a=a.getClientId();c==null?(t=AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles,u=[this,null]):b==null&&AdfDhtmlPanelDashboardPeer._adjustShim(d,a,g,k,f+1);b=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelDashboard-tr-reorder-animation-duration"));isNaN(b)&&(b=0);c=null;AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren(a)&&
(c=this.getComponent());this._animator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,b,d,null,t,u,c)}};AdfDhtmlPanelDashboardPeer.prototype._preventDiagonalMovement=function(a,b,c,d,e,f,g){f*=c;if(a.offsetTop!=f)c=a.style,c.top=f+"px",b>=Math.floor(d/2)?g?(a.style.right="auto",c.left=-e+"px"):c.left=d*e+"px":g?(a.style.right="auto",c.left=d*e+"px"):c.left=-e+"px"};
AdfDhtmlPanelDashboardPeer.prototype._getChildWidthInPixels=function(a){var b=this.__getDataBody(),c=AdfDomUtils.getChildElements(b).length;if(this._cachedChildWidthInPixels&&c==this._cachedChildCount)return this._cachedChildWidthInPixels;a=a.getColumns();this._cachedChildWidthInPixels=Math.floor(b.offsetWidth/a);this._cachedChildCount=c;return this._cachedChildWidthInPixels};
AdfDhtmlPanelDashboardPeer.prototype._getChildHeightInPixels=function(a){if(this._cachedChildHeightInPixels)return this._cachedChildHeightInPixels;var a=a.getRowHeight(),b=a.replace(/[0-9]/g,"");if(b=="px")a=parseInt(a.substring(0,a.length-b.length));else if(a=this.__getDataBody(),a=AdfDomUtils.getChildElements(a),a.length>0)a=a[0].offsetHeight;else return 20;return this._cachedChildHeightInPixels=a};
AdfDhtmlPanelDashboardPeer.prototype._deleteElements=function(a,b){if(a!=null)for(var c=this.__getDataBody(),d,d=0;d<a.length;d++){var e=a[d];b||(AdfPage.PAGE.removeComponentsInSubtree(e),AdfAgent.AGENT.elementsRemoved(e));c.removeChild(e)}};
AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles=function(a,b,c){var d=a[0];if(d.getDomElement()){d._deleteElements(a[1],!1);var e=d.__getDataBody();if(b!=null&&b!=c)a=AdfDomUtils.getChildElements(e),b=a[b],e.removeChild(b),a=AdfDomUtils.getChildElements(e),c<a.length?e.insertBefore(b,a[c]):e.appendChild(b),b.style.display="";var a=AdfDomUtils.getChildElements(e),c=a.length,d=d.getComponent(),b=d.getColumns(),e=d.getRowHeight(),f=e.replace(/[0-9]/g,""),g=e.substring(0,e.length-f.length),
g=parseFloat(g),h=AdfDhtmlPanelDashboardPeer._formatPercent(1/b);for(i=0;i<c;i++){var k=AdfDhtmlPanelDashboardPeer._formatPercent(i%b/b),l=a[i].style;l.top=g*Math.floor(i/b)+f;AdfPage.PAGE.getLocaleContext().isRightToLeft()?(l.left="auto",l.right=k):l.left=k;l.height=e;l.width=h}a=d.getClientId();AdfDhtmlPanelDashboardPeer._adjustShim(null,a,b,g,c);this._processingOptimizedChanges=!1;AdfPage.PAGE.doResizeNotify(d)}};
AdfDhtmlPanelDashboardPeer._formatPercent=function(a){var a=""+100*a,b=a.length,c=a.indexOf(".");c!=-1&&c<b-2&&(a=a.substring(0,c+3));return a+"%"};
AdfDhtmlPanelDashboardPeer.prototype._workaroundForInternetExplorer=function(a){if(AdfAgent.AGENT.getPlatform()==AdfAgent.IE_PLATFORM){var b=this.getDomElement(),c=b.scrollWidth;if(a==null)a=b.offsetWidth;if(c>a){b=this.__getDataBody();if(!AdfDhtmlPanelDashboardPeer._scrollBarWidth)AdfDhtmlPanelDashboardPeer._scrollBarWidth=c-a+2+"px";if(!AdfPage.PAGE.getLocaleContext().isRightToLeft())b.style.right=AdfDhtmlPanelDashboardPeer._scrollBarWidth}}};
function AdfPanelDashboardBehavior(a,b,c){this.Init(a,b,c)}AdfObject.createSubclass(AdfPanelDashboardBehavior,AdfClientBehavior);AdfPanelDashboardBehavior.prototype.Init=function(a,b,c,d){AdfPanelDashboardBehavior.superclass.Init.call(this);AdfAssert.assertString(a);this._panelDashboardId=a;this._type=b;this._index=c;this._alignId=d};
AdfPanelDashboardBehavior.prototype.initialize=function(a){AdfAssert.assertPrototype(a,AdfUIComponent);a instanceof AdfUICommand&&a.addEventListener(AdfActionEvent.ACTION_EVENT_TYPE,this._actionHandler,this)};
AdfPanelDashboardBehavior.prototype._actionHandler=function(a){if(a.isPartial()){var b=a.getSource(),a=b.findComponent(this._panelDashboardId);AdfAssert.assert(a!=null,'AdfUIComponent.findComponent() found no results; the panelDashboard referenced by the panelDashboardBehavior for="'+this._panelDashboardId+'" could not be found (panelDashboard component = '+a+").");if(a!=null){var c=parseInt(this._index);isNaN(c)&&(c=-1);var d=b;this._alignId!=null&&(d=b.findComponent(this._alignId),AdfAssert.assertPrototype(d,
AdfUIComponent,'The align component referenced by the panelDashboardBehavior for="'+this._panelDashboardId+'" and alignId="'+this._alignId+'" could not be found (behaviorComponent clientId = '+b.getClientId()+")."));b=a.getPeer();AdfAssert.assert(b.insertChildBehavior!=null,'The panelDashboard referenced by the panelDashboardBehavior for="'+this._panelDashboardId+'" is not a panelDashboard (panelDashboard component = '+a+").");b.insertChildBehavior(a,c,d)}}};
AdfUIComponents.createComponentClass("AdfRichDecorativeBox",{componentType:"oracle.adf.RichDecorativeBox",propertyKeys:[{name:"topHeight",type:"String","default":"50px"},{name:"topLandmark",type:"String","default":"none"},{name:"centerLandmark",type:"String","default":"none"},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"theme",type:"String"},{name:"dimensionsFrom",
type:"String","default":"parent"}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlDecorativeBoxPeer",!1);AdfDhtmlDecorativeBoxPeer.prototype.needsChildVisibilityChanges=function(){return!0};AdfDhtmlDecorativeBoxPeer.prototype.needsResizeNotify=function(){return!0};
AdfDhtmlDecorativeBoxPeer.prototype.BindToComponent=function(a,b){AdfDhtmlDecorativeBoxPeer.superclass.BindToComponent.call(this,a,b);var c=a.getClientId(),d=AdfAgent.AGENT;this._topLeftElement=d.getElementById(AdfRichUIPeer.CreateSubId(c,"tl"));this._topElement=d.getElementById(AdfRichUIPeer.CreateSubId(c,"t"));this._topInnerElement=d.getElementById(AdfRichUIPeer.CreateSubId(c,"t-i"));this._topRightElement=d.getElementById(AdfRichUIPeer.CreateSubId(c,"tr"));this._leftElement=d.getElementById(AdfRichUIPeer.CreateSubId(c,
"l"));this._centerElement=d.getElementById(AdfRichUIPeer.CreateSubId(c,"c"));this._rightElement=d.getElementById(AdfRichUIPeer.CreateSubId(c,"r"))};AdfDhtmlDecorativeBoxPeer.prototype.UnbindFromComponent=function(){AdfDhtmlDecorativeBoxPeer.superclass.UnbindFromComponent.call(this);this._rightElement=this._centerElement=this._leftElement=this._topRightElement=this._topInnerElement=this._topElement=this._topLeftElement=null};AdfDhtmlDecorativeBoxPeer.prototype.ResizeNotify=function(){};
AdfDhtmlDecorativeBoxPeer.prototype.DomReplaceNotify=function(a){if(a.parentNode!=this._topInnerElement)return a;var b=AdfAgent.AGENT,c=!1,d=AdfDomUtils.isVisible(this._topInnerElement),e=AdfDomUtils.isVisible(a);e!=d&&(AdfDomUtils.setVisible(this._topInnerElement,e),this._repositionPanes(),c=!0);b.prepareStretchedChild(a,"0px");if(!c)return b.resizeStretchedChild(a,"0px"),a;return this.getDomElement()};
AdfDhtmlDecorativeBoxPeer.prototype.ChildVisibilityChanged=function(a,b,c){if(b.parentNode!=this._topInnerElement)return!1;AdfDomUtils.setVisible(this._topInnerElement,c);this._repositionPanes();AdfDomUtils.setVisible(b,c);AdfPage.PAGE.doResizeNotify(this.getComponent());return!0};
AdfDhtmlDecorativeBoxPeer.prototype._repositionPanes=function(){var a,a=this._topInnerElement&&AdfDomUtils.isVisible(this._topInnerElement)?this.getComponent().getTopHeight():this._getAreaSkinProperty(this._topElement,"height");if(this._topLeftElement)this._topLeftElement.style.height=a;if(this._topElement)this._topElement.style.height=a;if(this._topRightElement)this._topRightElement.style.height=a;if(this._leftElement)this._leftElement.style.top=a;if(this._centerElement)this._centerElement.style.top=
a;if(this._rightElement)this._rightElement.style.top=a};
AdfDhtmlDecorativeBoxPeer.prototype._getAreaSkinProperty=function(a,b){var c=this.getComponent().getTheme(),d=AdfPage.PAGE.getLookAndFeel(),e=AdfPage.PAGE.getLocaleContext().isRightToLeft();switch(a){case this._topLeftElement:area=e?"top-end":"top-start";break;case this._topElement:case this._topInnerElement:area="top";break;case this._topRightElement:area=e?"top-start":"top-end";break;default:return null}e=null;c!=null&&(e=d.getSkinProperty("af|decorativeBox::"+area+"[theme='"+c+"']-tr-"+b));e==
null&&(e=d.getSkinProperty("af|decorativeBox::"+area+"-tr-"+b));return e};AdfDhtmlDecorativeBoxPeer.prototype.getContainerId=function(){return AdfPage.PAGE.getLookAndFeel().getSkinProperty("BORDER_STYLE")=="simple"?AdfRichUIPeer.createSubId(this.getComponent().getClientId(),"c"):this.getComponent().getClientId()};
AdfUIComponents.createComponentClass("AdfRichPanelStretchLayout",{componentType:"oracle.adf.RichPanelStretchLayout",propertyKeys:[{name:"dimensionsFrom",type:"String","default":"parent"},{name:"topHeight",type:"String","default":"50px"},{name:"bottomHeight",type:"String","default":"50px"},{name:"startWidth",type:"String","default":"50px"},{name:"endWidth",type:"String","default":"50px"},{name:"topLandmark",type:"String","default":"none"},{name:"startLandmark",type:"String","default":"none"},{name:"centerLandmark",
type:"String","default":"none"},{name:"endLandmark",type:"String","default":"none"},{name:"bottomLandmark",type:"String","default":"none"},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"theme",type:"String"}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelStretchLayoutPeer",!1);AdfDhtmlPanelStretchLayoutPeer.prototype.needsResizeNotify=function(){return!0};AdfDhtmlPanelStretchLayoutPeer.prototype.needsChildVisibilityChanges=function(){return!0};AdfDhtmlPanelStretchLayoutPeer.prototype.ComponentRemoved=function(a){AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a)};
AdfDhtmlPanelStretchLayoutPeer.prototype.BindToComponent=function(a,b){AdfDhtmlPanelStretchLayoutPeer.superclass.BindToComponent.call(this,a,b);var c=a.getClientId(),d=AdfRichUIPeer.CreateSubId(c,"c"),e=AdfRichUIPeer.CreateSubId(c,"m"),f=AdfRichUIPeer.CreateSubId(c,"t"),g=AdfRichUIPeer.CreateSubId(c,"b"),h=AdfRichUIPeer.CreateSubId(c,"l"),c=AdfRichUIPeer.CreateSubId(c,"r"),k=AdfAgent.AGENT;this._centerPaneElement=k.getElementById(d);this._middleWrapperElement=k.getElementById(e);this._topPaneElement=
k.getElementById(f);this._bottomPaneElement=k.getElementById(g);this._leftPaneElement=k.getElementById(h);this._rightPaneElement=k.getElementById(c)};AdfDhtmlPanelStretchLayoutPeer.prototype.UnbindFromComponent=function(){AdfDhtmlPanelStretchLayoutPeer.superclass.UnbindFromComponent.call(this);this._rightPaneElement=this._leftPaneElement=this._bottomPaneElement=this._topPaneElement=this._middleWrapperElement=this._centerPaneElement=null};
AdfDhtmlPanelStretchLayoutPeer.prototype.ResizeNotify=function(a,b,c,d){a==c&&b==d&&(b=a=void 0);var e=this.getDomElement(),e=AdfDomUtils.getFirstChildElement(e);if(e!=null){var e=e.style&&e.style.position=="absolute",f=this._topPaneElement,g=this._leftPaneElement,h=this._centerPaneElement,k=this._rightPaneElement,l=this._bottomPaneElement,m=this._getSize(f,"height"),n=this._getSize(g,"width"),o=this._getSize(k,"width"),q=this._getSize(l,"height"),p=!1;if(f&&AdfDomUtils.isVisible(f)&&!m)m=f.offsetHeight,
p=!0;g&&AdfDomUtils.isVisible(g)&&!n&&(p=!0);h&&AdfDomUtils.isVisible(h)&&!e&&this._isJsFlowLayout()&&(p=!0);k&&AdfDomUtils.isVisible(k)&&!o&&(p=!0);if(l&&AdfDomUtils.isVisible(l)&&!q)q=l.offsetHeight,p=!0;p&&(this._repositionPanes(),AdfPage.PAGE.__registerDescendantResizeNotifyComponent(this.getComponent()));n=this._getSize(g,"width");o=this._getSize(k,"width");m=d-(m+q);n=c-(n+o);c!=a&&(this._stretchPane(f,c,void 0),this._stretchPane(l,c,void 0));e&&(d!=b&&(this._stretchPane(g,void 0,m),this._stretchPane(k,
void 0,m)),this._stretchPane(h,n,m))}};
AdfDhtmlPanelStretchLayoutPeer.prototype.DomReplaceNotify=function(a){if(this._isChild(a)){var b=!1,c=a.parentNode,d=AdfDomUtils.isVisible(c),e=AdfDomUtils.isVisible(a);e!=d&&(AdfDomUtils.setVisible(c,e),this._repositionPanes(),b=!0);var d=!0,e=!1,f=this.getDomElement(),g=AdfDomUtils.getFirstChildElement(f);if(g==null)return f;var g=g.style&&g.style.position=="absolute",h=c.id;h.indexOf("::t")!=-1||h.indexOf("::b")!=-1?this._getSize(c,"height")||(b=e=!0):h.indexOf("::r")!=-1||h.indexOf("::l")!=-1?
g?this._getSize(c,"width")||(b=e=!0):d=!1:h.indexOf("::c")!=-1&&(g||(d=!1));if(d&&!e){var k="0px",l=AdfAgent.AGENT;l.prepareStretchedChild(a,k)}if(d&&!b)return l.resizeStretchedChild(a,k),a;return f}return a};AdfDhtmlPanelStretchLayoutPeer.prototype.ChildVisibilityChanged=function(a,b,c){if(this._isChild(b))return AdfDomUtils.setVisible(b.parentNode,c),this._repositionPanes(),AdfDomUtils.setVisible(b,c),AdfPage.PAGE.doResizeNotify(this.getComponent()),!0;return!1};
AdfDhtmlPanelStretchLayoutPeer.prototype._isJsFlowLayout=function(){var a=this._middleWrapperElement;return a!=null&&AdfAgent.AGENT.getAttribute(a,"_afrFlowJs")=="true"};AdfDhtmlPanelStretchLayoutPeer.prototype._getSize=function(a,b){return a&&AdfDomUtils.isVisible(a)?AdfAgent.getCSSLengthAsInt(a.style[b]):0};
AdfDhtmlPanelStretchLayoutPeer.prototype._getSizeLength=function(a,b){if(a&&AdfDomUtils.isVisible(a)){var c=a.style[b];if(c)return c;c="offset"+b.charAt(0).toUpperCase()+b.substring(1);return a[c]+"px"}return"0px"};AdfDhtmlPanelStretchLayoutPeer.prototype._isChild=function(a){return a.parentNode.parentNode==this.getDomElement()};
AdfDhtmlPanelStretchLayoutPeer.prototype._repositionPanes=function(){var a=AdfAgent.AGENT,b=this._leftPaneElement,c=this._bottomPaneElement,d=this._rightPaneElement,e=this._centerPaneElement,f=this._getSizeLength(this._topPaneElement,"height"),g=this._getSizeLength(c,"height"),c=this._getSizeLength(b,"width"),h=this._getSizeLength(d,"width"),k=this.getDomElement(),k=AdfDomUtils.getFirstChildElement(k);if(k!=null)if(k.style&&k.style.position=="absolute")a.repositionStretchedElement(b,f,g),a.repositionStretchedElement(d,
f,g),a.repositionStretchedElement(e,f,g,c,h);else if(this._isJsFlowLayout()){a=0;if(e!=null)e.style.left=c,e.style.right=h,a=Math.max(a,e.offsetHeight);b!=null&&(a=Math.max(a,b.offsetHeight));d!=null&&(a=Math.max(a,d.offsetHeight));this._middleWrapperElement.style.height=a+"px"}};AdfDhtmlPanelStretchLayoutPeer.prototype._stretchPane=function(a,b,c){if(a){var d=AdfAgent.AGENT;d.resizeStretchedElement(a,b,c);a=AdfDomUtils.getFirstChildElement(a);d.resizeStretchedChild(a,"0px")}};