AdfUIComponents.createComponentClass("AdfRichCommandToolbarButton",{componentType:"oracle.adf.RichCommandToolbarButton",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"useWindow",type:"Boolean","default":!1},{name:"windowModalityType",type:"String","default":"modeless"},{name:"windowEmbedStyle",type:"String","default":"window"},{name:"windowHeight",
type:"Number"},{name:"windowWidth",type:"Number"},{name:"accessKey",type:"String"},{name:"actionDelivery",type:"String","default":"clientServer",secured:!0},{name:"partialSubmit",type:"Boolean","default":!0},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"depressedIcon",type:"String"},{name:"hoverIcon",type:"String"},{name:"disabledIcon",type:"String"},{name:"icon",type:"String"},{name:"text",type:"String"},{name:"type",type:"String","default":"default"},{name:"selected",type:"Boolean",
"default":!1}],superclass:AdfUICommand});
AdfRichCommandToolbarButton.prototype.getAccessibleName=function(){return this.getShortDesc()};
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlCommandToolbarButtonPeer");
AdfDhtmlCommandToolbarButtonPeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.MOUSE_UP_EVENT_TYPE);AdfAgent.AGENT.getCapabilities()[AdfAgent.CAP_TOUCH_SCREEN]==AdfAgent.CAP_TOUCH_SCREEN_NONE&&AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE,AdfUIInputEvent.MOUSE_OUT_EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,
AdfRichCommandToolbarButton.DISABLED,AdfRichCommandToolbarButton.SELECTED,AdfRichCommandToolbarButton.SHORT_DESC,AdfRichCommandToolbarButton.TEXT);this._POPUP_ELEMENT="popEl";this._POPUP_CONTAINER="popCtr";this._POPUP_CONTEXT_AREA="popArea";this._POPUP_ID="_afrPopId";this._POPUP_SELECTOR_ID="_afrPopSlr";this._AFR_GROUPID="_afrGrp";this._DEPRESSED_STYLE_CLASS="p_AFDepressed";this._SELECTED_STYLE_CLASS="p_AFSelected";this._BUSY="_busy"};
AdfDhtmlCommandToolbarButtonPeer.prototype.BindToComponent=function(a,b){AdfDhtmlCommandToolbarButtonPeer.superclass.BindToComponent.call(this,a,b);this._actionDisabled=AdfDomUtils.containsCSSClassName(b,"p_AFActionDisabled")};
AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentKeyDown=function(a){if(!a.isCanceled()){var b=a.getKeyCode(),a=this._isInPopupSelector(a)&&b==AdfKeyStroke.ENTER_KEY,c=this._actionDisabled&&(b==AdfKeyStroke.ENTER_KEY||b==AdfKeyStroke.SPACE_KEY);if(b==AdfKeyStroke.ARROWDOWN_KEY||a||c)b=this._getPopupId(),this._openPopupMenu(b,!0);else if(b==AdfKeyStroke.ESC_KEY){a=this.getComponent();b=this._getPopupId();if(!b)b=AdfDhtmlCommandToolbarButtonPeer._POPUP_SELECTOR_ID;this.hidePopup(a,b)}}};
AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentClick=function(a){if(a.isLeftButtonPressed()&&!this._actionDisabled&&!this._isInPopupSelector(a)&&this._isValidAction(a)){var a=this.getComponent(),b=a.getProperty(AdfDhtmlCommandToolbarButtonPeer._BUSY);!a.getDisabled()&&!b&&this._execute()}};AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentMouseOver=function(){this.getComponent().getDisabled()||this._displayMouseOverIcon(this.getComponent())};
AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentMouseOut=function(){var a=this.getComponent();a.getDisabled()||(a.getSelected()?(this._setDepressedStyle(a,!0),this._displayMouseDownIcon(a)):(this._setDepressedStyle(a,!1),this._displayDefaultIcon(a)))};AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentMouseUp=function(a){var b=this.getComponent();!b.getDisabled()&&a.isLeftButtonPressed()&&(this._setDepressedStyle(b,!1),this._displayMouseOverIcon(b))};
AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentMouseDown=function(a){var b=this.getComponent(),c=a.isLeftButtonPressed();!b.getDisabled()&&c&&(this._setDepressedStyle(b,!0),this._displayMouseDownIcon(b),this._actionDisabled||this._isInPopupSelector(a)?(this._openPopupMenu(this._getPopupId(),!1),a.cancel()):this._isValidAction(a))};
AdfDhtmlCommandToolbarButtonPeer.prototype.ComponentDisabledChanged=function(a,b,c){c==!0?(AdfDomUtils.addCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),this._displayDisabledIcon(a)):(AdfDomUtils.removeCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),this._displayDefaultIcon(a));page.isScreenReaderMode()&&(b=AdfDomUtils.getFirstChildElement(b),c==!0?(b.removeAttribute("href"),c=AdfPage.PAGE.getLookAndFeel().getTranslatedString("af_commandToolbarButton.STATE_DISABLED"),AdfDomUtils.setAccessibleState(a,
c)):(b.setAttribute("href","#"),AdfDomUtils.setAccessibleState(a,null)))};
AdfDhtmlCommandToolbarButtonPeer.prototype.ComponentSelectedChanged=function(a,b,c){var d=AdfPage.PAGE,e=null;c?(AdfDomUtils.addCSSClassName(b,AdfDhtmlCommandToolbarButtonPeer._SELECTED_STYLE_CLASS),this._displayMouseDownIcon(a),b=a.getType(),c=d.getLookAndFeel(),b=="check"?e=c.getTranslatedString("af_commandToolbarButton.STATE_CHECKBOX_SELECTED"):b=="radio"&&(e=c.getTranslatedString("af_commandToolbarButton.STATE_RADIO_SELECTED"))):(AdfDomUtils.removeCSSClassName(b,AdfDhtmlCommandToolbarButtonPeer._SELECTED_STYLE_CLASS),
this._displayDefaultIcon(a));d.isScreenReaderMode()&&AdfDomUtils.setAccessibleState(a,e)};AdfDhtmlCommandToolbarButtonPeer.prototype.ComponentShortDescChanged=function(){return!0};AdfDhtmlCommandToolbarButtonPeer.prototype.ComponentTextChanged=AdfDomUtils.__componentTextChanged;AdfDhtmlCommandToolbarButtonPeer.prototype.GetInlineEditor=function(){return AdfDhtmlSimpleTextEditor.getInlineEditor()};
AdfDhtmlCommandToolbarButtonPeer.prototype.SetBusy=function(a){var b=this.getComponent(),c=this.getDomElement(),d=AdfDomUtils.getFormElement(c),d=AdfDomUtils.getMultiPartForm(d)!=null;!b.getDisabled()&&!d&&(AdfDomUtils.addOrRemoveCSSClassName(a,c,AdfRichUIPeer.DISABLED_STYLECLASS),b.setProperty(AdfDhtmlCommandToolbarButtonPeer._BUSY,a,!1,AdfUIComponent.PROPAGATE_NEVER))};
AdfDhtmlCommandToolbarButtonPeer.prototype.PopupClosed=function(a,b,c){AdfDhtmlCommandToolbarButtonPeer.superclass.PopupClosed.call(this,a,b);c==AdfDhtmlCommandToolbarButtonPeer._POPUP_SELECTOR_ID&&(a=a.getClientId(),a=AdfRichUIPeer.createSubId(a,AdfDhtmlCommandToolbarButtonPeer._POPUP_CONTAINER),(a=AdfAgent.AGENT.getElementById(a))&&a.appendChild(b))};
AdfDhtmlCommandToolbarButtonPeer.prototype.__preferredSizeChangeNotify=function(a){this.bind(a);var a=this.getComponentParent(a),b=a!=null?a.getPeer():null;b&&b.__preferredSizeChangeNotify&&b.__preferredSizeChangeNotify(a)};AdfDhtmlCommandToolbarButtonPeer.prototype._execute=function(){var a=this.getComponent(),b=a.getType();b=="check"?a.setSelected(!a.getSelected()):b=="radio"&&this._toggleRadioGroupItems();AdfActionEvent.queue(a,a.getPartialSubmit())};
AdfDhtmlCommandToolbarButtonPeer.prototype._openPopupMenu=function(a,b){var c=this.getComponent(),d=AdfRichUIPeer.createSubId(c.getClientId(),AdfDhtmlCommandToolbarButtonPeer._POPUP_ELEMENT);if(AdfAgent.AGENT.getElementById(d))if(d=this.getDomElement(),a!=null){var c=AdfPage.PAGE.findComponent(a).getPeer(),e={};e[AdfDhtmlPopupWindow.HINT_ALIGN_ELEMENT]=d;e[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_START;e[AdfDhtmlPopupWindow.HINT_FOCUS]=b;c.show(e)}else{var e=AdfRichUIPeer.createSubId(c.getClientId(),
AdfDhtmlCommandToolbarButtonPeer._POPUP_CONTAINER),f=AdfAgent.AGENT.getElementById(e);if(f!=null){for(var g=f.firstChild;g&&g.nodeType==8;)g=g.nextSibling;if(g!=null)e={},g.nodeType==3&&(f=f.ownerDocument.createElement("span"),f.appendChild(g),g=f),e[AdfDhtmlPopupWindow.HINT_AUTODISMISS]=AdfDhtmlPopupWindow.HINT_AUTODISMISS_ALWAYS,e[AdfDhtmlPopupWindow.HINT_ALIGN_ELEMENT]=d,e[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_START,e[AdfDhtmlPopupWindow.HINT_FOCUS]=b,this.showPopup(c,g,e,AdfDhtmlCommandToolbarButtonPeer._POPUP_SELECTOR_ID)}}};
AdfDhtmlCommandToolbarButtonPeer.prototype._toggleRadioGroupItems=function(){for(var a=this.getComponent(),b=this._getGroupId(this.getDomElement()),c=a.getParent(),c=c.getPeer().getDescendantComponents(c),d=0;d<c.length;d++){var e=c[d],f=this._getGroupId(AdfRichUIPeer.getDomElementForComponent(e));b==f&&e!=a&&e.getType&&e.getType()=="radio"&&this._toggleComponentUnselected(e)}a.setSelected(!0)};AdfDhtmlCommandToolbarButtonPeer.prototype._getGroupId=function(a){return a.getAttribute(AdfDhtmlCommandToolbarButtonPeer._AFR_GROUPID)};
AdfDhtmlCommandToolbarButtonPeer.prototype._toggleComponentUnselected=function(a){a.setSelected(!1);this._setDepressedStyle(a,!1);this._displayDefaultIcon(a)};AdfDhtmlCommandToolbarButtonPeer.prototype._getIconElement=function(a){a=a.getClientId();a=AdfRichUIPeer.createSubId(a,"icon");return AdfAgent.AGENT.getElementById(a)};AdfDhtmlCommandToolbarButtonPeer.prototype._displayDefaultIcon=function(a){var b=a.getIcon();if(b)this._getIconElement(a).src=b};
AdfDhtmlCommandToolbarButtonPeer.prototype._displayMouseDownIcon=function(a){this._displayIcon(a,a.getDepressedIcon())};AdfDhtmlCommandToolbarButtonPeer.prototype._displayMouseOverIcon=function(a){this._displayIcon(a,a.getHoverIcon())};AdfDhtmlCommandToolbarButtonPeer.prototype._displayDisabledIcon=function(a){this._displayIcon(a,a.getDisabledIcon())};AdfDhtmlCommandToolbarButtonPeer.prototype._displayIcon=function(a,b){var c=a.getIcon();if(c)this._getIconElement(a).src=b||c};
AdfDhtmlCommandToolbarButtonPeer.prototype._setDepressedStyle=function(a,b){var c=AdfRichUIPeer.getDomElementForComponent(a),d=AdfDhtmlCommandToolbarButtonPeer._DEPRESSED_STYLE_CLASS;b?AdfDomUtils.addCSSClassName(c,d):AdfDomUtils.removeCSSClassName(c,d)};
AdfDhtmlCommandToolbarButtonPeer.prototype._isInPopupSelector=function(a){for(var b=this.getComponent().getClientId(),c=AdfRichUIPeer.createSubId(b,AdfDhtmlCommandToolbarButtonPeer._POPUP_CONTEXT_AREA),a=a.getNativeEventTarget();a!=null&&a.id!=b;){if(a.id==c)return!0;a=a.parentNode}return!1};
AdfDhtmlCommandToolbarButtonPeer.prototype._getPopupId=function(){var a=this.getComponent(),a=AdfRichUIPeer.createSubId(a.getClientId(),AdfDhtmlCommandToolbarButtonPeer._POPUP_ELEMENT),a=AdfAgent.AGENT.getElementById(a);if(!a)return null;var a=a.parentNode,b=a.getAttribute(AdfDhtmlCommandToolbarButtonPeer._POPUP_ID);b==null&&(b=a.parentNode.getAttribute(AdfDhtmlCommandToolbarButtonPeer._POPUP_ID));return b};
AdfDhtmlCommandToolbarButtonPeer.prototype._isValidAction=function(a){for(var b=a.getNativeEventTarget(),a=this._getPopupId(),c=a!=null,d=this.getDomElement();b.parentNode;b=b.parentNode){if(c&&a==b.id)break;if(b==d)return!0}return!1};
AdfUIComponents.createComponentClass("AdfRichToolbar",{componentType:"oracle.adf.RichToolbar",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"flex",type:"Number","default":0},{name:"stretchId",type:"String"}],superclass:AdfUIPanel});
AdfRichToolbar.HORIZONTAL="horizontal";AdfRichToolbar.VERTICAL="vertical";
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlToolbarPeer",!1);AdfDhtmlToolbarPeer.InitSubclass=function(){this._OVERFLOW_ELEMENT_STYLE_CLASS="AFToolbarOverflowElement"};
AdfDhtmlToolbarPeer.prototype.InitDomElement=function(a,b){AdfDhtmlToolbarPeer.superclass.InitDomElement.call(this,a,b);var c=a.getClientId(),d=AdfRichUIPeer.CreateSubId(c,"eoc"),e=AdfAgent.AGENT;this._isOverflowSupported=(this._overflowContainer=e.getElementById(d))?!0:!1;if(this._isOverflowSupported==!0)d=AdfRichUIPeer.CreateSubId(c,"eoi"),this._overflowIndicator=e.getElementById(d);AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a);c=b.getElementsByTagName("table")[0];this._childContainers=
e.getTableRowCells(e.getTableRow(c,0))};AdfDhtmlToolbarPeer.prototype.needsChildVisibilityChanges=function(){return!0};AdfDhtmlToolbarPeer.prototype.needsResizeNotify=function(){return!0};AdfDhtmlToolbarPeer.prototype.getDescendantComponents=function(a,b){b||(b=[]);AdfDhtmlToolbarPeer.superclass.getDescendantComponents.call(this,a,b);this._isOverflowSupported==!0&&AdfOverflowSupport.getOverflowChildComponents(a,b);return b};
AdfDhtmlToolbarPeer.prototype.ResizeNotify=function(){var a=this.getDomElement(),b=this.getComponent(),c=b.getClientId();if(this._isOverflowSupported!=!1||b.getStretchId()){this._unStretch();if(this._isOverflowSupported==!0){if(!this._overflowSupport){this._overflowSupport=new AdfOverflowSupport(c,this,"end");a=a.getElementsByTagName("table")[0];b=AdfAgent.AGENT;a=b.getTableRowCells(b.getTableRow(a,0));b=0;for(c=a[0];c;){this._overflowSupport.createStep();this._overflowSupport.addElement(c);if(c=
AdfDomUtils.getFirstChildElement(c)){var d=AdfPage.PAGE.findComponent(c.id);(window.AdfRichSpacer==void 0||!(d instanceof AdfRichSpacer))&&this._overflowSupport.addOverflowElement(this._createOverflowElement(c))}b++;c=a[b]}}this._overflowSupport.handleResize()}this._reStretch()}};AdfDhtmlToolbarPeer.prototype.ChildVisibilityChanged=function(){AdfPage.PAGE.addPartialTargets(this.getComponent());return!1};
AdfDhtmlToolbarPeer.prototype.GetPreferredWidth=function(){if(!this._preferredWidth){var a=this.getDomElement().firstChild;this._unStretch();this._overflowSupport&&this._overflowSupport.removeAllItemsFromOverflow();this._preferredWidth=a.offsetWidth;this._reStretch()}return this._preferredWidth};
AdfDhtmlToolbarPeer.prototype.GetMinimumWidth=function(){if(!this._minimumWidth)if(this._isOverflowSupported==!1)this._minimumWidth=this.GetPreferredWidth();else if(this._childContainers&&this._childContainers.length>0){var a=this._overflowIndicator.style.display;this._overflowIndicator.style.display="block";this._minimumWidth=this._overflowIndicator.offsetWidth;this._overflowIndicator.style.display=a;a=this.GetPreferredWidth();if(this._minimumWidth>a)this._minimumWidth=a}else this._minimumWidth=
0;return this._minimumWidth};AdfDhtmlToolbarPeer.prototype.ComponentRemoved=function(a){delete this._overflowContainer;delete this._overflowIndicator;delete this._childContainers;this._overflowSupport&&(this._overflowSupport.removeOverflowSupport(),delete this._overflowSupport);AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a);AdfDhtmlToolbarPeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlToolbarPeer.prototype.__preferredSizeChangeNotify=function(a){this.bind(a);this._minimumWidth=this._preferredWidth=null;var a=this.getComponentParent(a),b=a!=null?a.getPeer():null;b&&b.__preferredSizeChangeNotify&&b.__preferredSizeChangeNotify(a)};AdfDhtmlToolbarPeer.prototype._unStretch=function(){var a=this._getStretchElement();if(a)a.parentNode.style.width=""};
AdfDhtmlToolbarPeer.prototype._reStretch=function(){var a=this._getStretchElement();if(a){var b=AdfAgent.AGENT.getWindowWidth()+"px";a.parentNode.style.width=b}};AdfDhtmlToolbarPeer.prototype._createOverflowElement=function(a){var b=a.ownerDocument.createElement("table");b.cellPadding=0;b.cellSpacing=0;b.style.width="100%";var c=b.insertRow(-1),d=c.insertCell(-1),a=this._overflowSupport.createSwapPosition(a);d.appendChild(a);d=c.insertCell(-1);d.style.width="100%";return b};
AdfDhtmlToolbarPeer.prototype._getStretchElement=function(){var a=this.getComponent(),b=a.getStretchId();if(b)if(a=a.findComponent(b))return b=a.getClientId(),AdfAgent.AGENT.getElementById(b);else AdfLogger.LOGGER.warning("Unable to find client component for stretch id "+b);return null};