AdfUIComponents.createComponentClass("AdfRichInputText",{componentType:"oracle.adf.RichInputText",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"readOnly",type:"Boolean","default":!1,secured:!0},{name:"showRequired",
type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"editable",type:"String","default":"inherit"},{name:"placeholder",type:"String"},{name:"autoTab",type:"Boolean","default":!1},{name:"columns",type:"Number"},{name:"dimensionsFrom",type:"String","default":"content"},{name:"inlineStyle",type:"String"},{name:"maximumLength",type:"Number"},{name:"autoComplete",
type:"String"},{name:"rows",type:"Number","default":1},{name:"secret",type:"Boolean","default":!1,secured:!0},{name:"styleClass",type:"String"},{name:"usage",type:"String","default":"auto"},{name:"wrap",type:"String"}],superclass:AdfUIInput});
AdfRichUIPeer.createPeerClass(AdfDhtmlInputBasePeer,"AdfDhtmlInputTextPeer");AdfDhtmlInputTextPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfRichInputText);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichInputText.LABEL);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_PRESS_EVENT_TYPE,AdfUIInputEvent.KEY_UP_EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichInputText.LABEL)};
AdfDhtmlInputTextPeer.prototype.replaceTextSelection=function(a){var b=this.getComponent();if(this.WasSubmitted(b)){var c=AdfDhtmlEditableValuePeer.GetContentNode(b);AdfEditingAgent.getInstance().insertHtmlAtSelection(c,a);this.RunValidation(b,c)}};AdfDhtmlInputTextPeer.prototype.needsResizeNotify=function(a){var b=AdfAgent.AGENT,c=b.getPlatform()==AdfAgent.IE_PLATFORM,b=b.getVersion();return c&&b<8&&AdfDomUtils.containsCSSClassName(AdfRichUIPeer.getDomNodeForComponent(a),"p_AFStretched")};
AdfDhtmlInputTextPeer.prototype.resizeNotify=function(a,b,c,d,e){b=AdfAgent.AGENT;a=AdfDhtmlEditableValuePeer.GetContentNode(a);b.setOuterWidth(a,d);b.setOuterHeight(a,e)};AdfDhtmlInputTextPeer.prototype.SetDisplayValue=function(a,b,c){AdfAssert.assertString(c);b=AdfDhtmlEditableValuePeer.GetContentNode(a);if(a.getReadOnly())(a.getRows()>1||this.IsSecret(a)!=!0)&&AdfAgent.AGENT.setTextContent(b,c);else{if(!this.IsSecret(a))b.title=c;CSCOPut_value(b,c)}};
AdfDhtmlInputTextPeer.prototype.IsSecret=function(a){return AdfDhtmlEditableValuePeer.GetContentNode(a).type=="password"?!0:!1};
AdfDhtmlInputTextPeer.prototype.HandleComponentKeyPress=function(a){if(a.getEventPhase()==AdfBaseEvent.AT_TARGET_PHASE){var b=this.getComponent(),c=a.getNativeEventTarget(),d=a.getNativeEvent(),e=AdfAgent.AGENT.getKeyCode(d);if(c.tagName=="TEXTAREA"){if(this._checkLength(b,c)&&(b=d.keyCode,e=d.charCode,(b==0||b==13||e==void 0||b==e)&&!d.ctrlKey))d=!0,c.selectionStart!=null?d=c.selectionStart==c.selectionEnd:document.selection&&(d=CSCOGet_text(document.selection.createRange())==""),d&&a.cancel()}else e==AdfKeyStroke.ENTER_KEY&&
this.RunValidation(b,c);this._nodeLength=CSCOGet_value(c)?CSCOGet_value(c).length:0}};AdfDhtmlInputTextPeer.prototype.HandleComponentKeyUp=function(a){if(a.getEventPhase()==AdfBaseEvent.AT_TARGET_PHASE){AdfAgent.AGENT.getKeyCode(a.getNativeEvent())!=9&&this.AutoTab(this.getComponent(),a.getNativeEventTarget());delete this._nodeLength;var b=this.getComponent(),c=a.getNativeEventTarget();this._checkLength(b,c)}AdfDhtmlInputTextPeer.superclass.HandleComponentKeyUp.call(this,a)};
AdfDhtmlInputTextPeer.prototype.AutoTab=function(a,b){if(a.getAutoTab&&a.getAutoTab()&&(AdfAgent.AGENT.getCapabilities()[AdfAgent.CAP_TOUCH_SCREEN]==AdfAgent.CAP_TOUCH_SCREEN_NONE||AdfAgent.guessOS()==AdfAgent.ANDROID_OS)){var c=a.getMaximumLength();if(!(c<1)){var d=CSCOGet_value(b)?CSCOGet_value(b).length:0;d>=c&&d>this._nodeLength&&AdfFocusUtils.focusNextTabStop(b)}}};AdfDhtmlInputTextPeer.prototype.GetInlineEditor=function(){return AdfDhtmlSimpleLabelEditor.getInlineEditor()};
AdfDhtmlInputTextPeer.prototype._checkLength=function(a,b){if(a&&a.getMaximumLength){var c=a.getMaximumLength();if(c<1)return!1;var d=CSCOGet_value(b)?CSCOGet_value(b).length:0;if(d>=c){if(d>c) CSCOPut_value(b,CSCOGet_value(b).substr(0,c));return!0}}return!1};
function AdfInsertTextBehavior(a,b,c){this.Init(a,b,c)}AdfInsertTextBehavior.InitClass=function(){};AdfObject.createSubclass(AdfInsertTextBehavior,AdfClientBehavior);AdfInsertTextBehavior.prototype.Init=function(a,b,c){AdfInsertTextBehavior.superclass.Init.call(this);AdfAssert.assertString(a);this._componentId=a;this._value=b;this._triggerType=c};AdfInsertTextBehavior.prototype.initialize=function(a){var b=this._triggerType;if(!b)b=AdfActionEvent.ACTION_EVENT_TYPE;a.addEventListener(b,this.fire,this)};
AdfInsertTextBehavior.prototype.fire=function(a){a.cancel();var b=this._componentId,a=a.getSource().findComponent(b),c=AdfLogger.LOGGER;a?(b=a.getPeer(),b.bind(a),b.replaceTextSelection&&b.replaceTextSelection(this._value)):c.severe("Could not find component with Id: "+b)};
function AdfEditingAgent(){this.Init()}AdfObject.createSubclass(AdfEditingAgent);
AdfEditingAgent.getInstance=function(){if(AdfEditingAgent._instance==void 0)if(AdfPage.PAGE.isAttachmentMode())AdfEditingAgent._instance=new AdfGeckoEditingAgent;else switch(AdfAgent.AGENT.getPlatform()){case AdfAgent.GECKO_PLATFORM:AdfEditingAgent._instance=new AdfGeckoEditingAgent;break;case AdfAgent.IE_PLATFORM:AdfEditingAgent._instance=new AdfIEEditingAgent;break;case AdfAgent.WEBKIT_PLATFORM:AdfEditingAgent._instance=new AdfSafariEditingAgent;break;default:AdfLogger.LOGGER.severe("Rich Text Editing is not supported on this platform")}return AdfEditingAgent._instance};
AdfEditingAgent.prototype.toBrowserSpecificCommand=function(a){return a};AdfEditingAgent.prototype.getContentWindow=function(a){AdfAssert.assertDomElement(a,"IFRAME");AdfAssert.assert(a.contentWindow,"Unexpected null contentWindow.");return a.contentWindow};AdfEditingAgent.prototype.getColor=function(a){var b=new TrColorConverter(["'rgb'(r, g, b)","'rgb'(r,g,b)"],!1);try{a=b.getAsObject(a)}catch(c){a=null}return a};
AdfEditingAgent.prototype.getInlineFrameDocument=function(a){AdfAssert.assertDomElement(a,"IFRAME");a=this.getContentWindow(a);AdfAssert.assert(a,"Unexpected null contentWindow.");AdfAssert.assert(a.document,"Unexpected null contentWindow document.");return a.document};
AdfEditingAgent.prototype.execCommand=function(a,b,c,d){var e;c!="insert"&&(AdfAssert.assertDomElement(b,"IFRAME"),e=AdfEditingAgent.getInstance().getInlineFrameDocument(b));if(d==null)switch(c){case "createlink":var d=AdfPage.PAGE.getLookAndFeel().getTranslatedString("af_richTextEditor.LABEL_SPECIFY_THE_URL"),f=this._getLinkURLForSelection(a,b),d=prompt(d,f);if(d==null||d=="")return}switch(c){case "insert":a=d;a==null&&(a="");this.insertHtmlAtSelection(b,a);break;case "moderichtext":a.getPeer().setCodeEditingMode(!1);
break;case "modecode":a.getPeer().setCodeEditingMode(!0);break;case "undo":this.ExecuteUndo(a,b,e);break;case "redo":this.ExecuteRedo(a,b,e);break;case "createlink":this.CreateLink(a,e,d);break;default:this._executeCommand(a,e,c,d)}};
AdfEditingAgent.prototype.queryCommandEnabled=function(a,b,c){AdfAssert.assertString(c);var d=!1;switch(c){case "insert":case "moderichtext":case "modecode":d=!0;break;case "undo":d=this.QueryUndoEnabled(a,b);break;case "redo":d=this.QueryRedoEnabled(a,b);break;default:d=this._queryCommandEnabled(a,b,c)}return d};AdfEditingAgent.prototype.setInlineFrameContentEditable=function(a){AdfAssert.assertDomElement(a,"IFRAME");this.getInlineFrameDocument(a).designMode="on";return!0};
AdfEditingAgent.prototype.isDesignMode=function(a){(a=this.getInlineFrameDocument(a).designMode)&&(a=a.toLowerCase());return a=="on"};AdfEditingAgent.prototype.isDesignModeReloadingFrame=function(){return!1};AdfEditingAgent.prototype.queryCommandValue=function(a,b){var b=this.toBrowserSpecificCommand(b),c=!1;try{c=this.getInlineFrameDocument(a).queryCommandValue(b)}catch(d){AdfLogger.LOGGER.severe("queryCommandValue: command not supported (",b,").",d)}return c};
AdfEditingAgent.prototype.queryCommandState=function(a,b){AdfAssert.assertString(b);if(!(b=="indent"||b=="outdent")){if(b=="forecolor"||b=="backcolor"||b=="fontsize"||b=="fontname")return this.queryCommandValue(a,b);var c=!1,b=this.toBrowserSpecificCommand(b);try{c=this.getInlineFrameDocument(a).queryCommandState(b)}catch(d){AdfLogger.LOGGER.severe("queryCommandState: command not supported (",b,").",d)}return c}};
AdfEditingAgent.prototype.setRTL=function(a){AdfAssert.assert(a);a=a.body;AdfAssert.assertDomElement(a,"BODY");CSCOCall_setAttribute(a,"setAttribute","dir",AdfPage.PAGE.getLocaleContext().isRightToLeft()?"rtl":"ltr")};AdfEditingAgent.prototype.queryCommandIndeterminate=function(a,b){var b=this.toBrowserSpecificCommand(b),c=!1;try{c=this.getInlineFrameDocument(a).queryCommandIndeterm(b)}catch(d){AdfLogger.LOGGER.severe("queryCommandIndeterminate: command not supported (",b,").",d)}return c};
AdfEditingAgent.prototype.getFocusBlurElement=function(a){return a};AdfEditingAgent.prototype.getSelectionRange=function(a){return this.getInlineFrameDocument(a).selection.createRange()};AdfEditingAgent.prototype.getInlineFrameContent=function(a){return CSCOGet_innerHTML(this.getInlineFrameDocument(a).body)};AdfEditingAgent.prototype.setInlineFrameContent=function(a,b){CSCOPut_innerHTML(this.getInlineFrameDocument(a).body,b)};AdfEditingAgent.prototype.getDefaultContent=function(){return""};
AdfEditingAgent.prototype.setSelectionRange=function(a,b){b.select()};
AdfEditingAgent.prototype.insertHtmlAtSelection=function(a,b){if(a.nodeName=="TEXTAREA"||a.nodeName=="INPUT"){var c=a.selectionStart+b.length;CSCOPut_value(a,CSCOGet_value(a).substr(0,a.selectionStart)+b+CSCOGet_value(a).substr(a.selectionEnd));a.selectionStart=c;a.selectionEnd=c}else if(c=this.getSelectionRange(a),c==null)AdfLogger.LOGGER.severe("Unexpected null selection for insert command.");else{CSCOCall_toString(c,"toString").length>0&&c.deleteContents();c.cloneRange();var d=CSCOCall_createElement(document,"createElement","div");CSCOPut_innerHTML(d,b);for(var d=d.childNodes,
e=null,f=d.length-1;f>=0;f--){var g=d[f];e==null&&(e=g);c.insertNode(g)}e!=null&&(c.selectNode(e),c.setStartAfter(e))}};AdfEditingAgent.prototype.handleTab=function(){};AdfEditingAgent.prototype.updateValueHistory=function(){};AdfEditingAgent.prototype.ExecuteUndo=function(a,b,c){this._executeCommand(a,c,"undo",null)};AdfEditingAgent.prototype.ExecuteRedo=function(a,b,c){this._executeCommand(a,c,"redo",null)};
AdfEditingAgent.prototype.CreateLink=function(a,b,c){this._executeCommand(a,b,"createlink",c)};AdfEditingAgent.prototype.QueryUndoEnabled=function(a,b){return this._queryCommandEnabled(a,b,"undo")};AdfEditingAgent.prototype.QueryRedoEnabled=function(a,b){return this._queryCommandEnabled(a,b,"redo")};
AdfEditingAgent.prototype.IsNodeWrappingRange=function(a,b){var c=b.ownerDocument.createRange();try{c.selectNode(b)}catch(d){return AdfLogger.LOGGER.logErrorAsInfo(d,"Unable to select node in range"),!1}var e=a.compareBoundaryPoints(Range.START_TO_START,c)!=-1,c=a.compareBoundaryPoints(Range.END_TO_END,c)!=1;return e&&c};
AdfEditingAgent.prototype._executeCommand=function(a,b,c,d){a=this.toBrowserSpecificCommand(c);try{CSCOCall_execCommand(b,"execCommand",a,null,d)}catch(e){AdfLogger.LOGGER.severe("execCommand[",c,",",d,"] failed with the following exception: ",e)}};AdfEditingAgent.prototype._queryCommandEnabled=function(a,b,c){a=!1;b=this.getInlineFrameDocument(b);c=this.toBrowserSpecificCommand(c);try{a=b.queryCommandEnabled(c)}catch(d){AdfLogger.LOGGER.severe("queryCommandEnabled failed with the following exception: [",c,"]: ",d)}return a};
AdfEditingAgent.prototype._getLinkURLForSelection=function(a,b){AdfAssert.assertDomElement(b,"IFRAME");for(var c=this.getInlineFrameDocument(b).getElementsByTagName("a"),d=a.getPeer().getSelectionRange(a),e="about:blank",f=0;f<c.length;f++)if(this.IsNodeWrappingRange(d,c[f])){e=CSCOGet_href(c[f]);break}return e};
function AdfGeckoEditingAgent(){this.Init()}AdfObject.createSubclass(AdfGeckoEditingAgent,AdfEditingAgent);AdfGeckoEditingAgent.InitClass=function(){this._cmdBackColor="backcolor";this._cmdHiliteColor="hilitecolor"};
AdfGeckoEditingAgent.prototype.getInlineFrameContent=function(a,b){var c=this.getInlineFrameDocument(a),d=c.body;if(!b){var e=d.childNodes;if(e){var f=d.getElementsByTagName("BR");if(f&&f.length<=1){for(f=e.length;f>0;){var g=e[0];g.nodeType==1&&g.offsetWidth==0?(CSCOCall_removeChild(d,"removeChild",g),f--):f=0}d.childNodes.length==0&&(c=CSCOCall_createElement(c,"createElement","br"), CSCOCall_appendChild(d,"appendChild",c))}if(e.length==1&&e[0].nodeName=="BR")return""}}return CSCOGet_innerHTML(d)};AdfGeckoEditingAgent.prototype.getDefaultContent=function(){return"<br>"};
AdfGeckoEditingAgent.prototype.toBrowserSpecificCommand=function(a){var b=a;if(a==AdfGeckoEditingAgent._cmdBackColor)b=AdfGeckoEditingAgent._cmdHiliteColor;return b};
AdfGeckoEditingAgent.prototype.setInlineFrameContentEditable=function(a){if(this.isDesignMode(a))return!1;for(var b=!1,c=a;c.parentNode&&!b;c=c.parentNode)if(c.style.display=="none"||c.style.visibility=="hidden")b=!0;if(b)return!1;b=AdfGeckoEditingAgent.superclass.setInlineFrameContentEditable.call(this,a);this.isDesignMode(a)&& CSCOCall_execCommand(this,"execCommand",null,a,"styleWithCSS",!0);return b};AdfGeckoEditingAgent.prototype.getFocusBlurElement=function(a){AdfAssert.assertDomElement(a,"IFRAME");return this.getInlineFrameDocument(a)};
AdfGeckoEditingAgent.prototype.getSelectionRange=function(a){AdfAssert.assertDomElement(a,"IFRAME");if((a=this._getWindowSelection(a))&&a.rangeCount>0)return a.getRangeAt(0)};AdfGeckoEditingAgent.prototype.setSelectionRange=function(a,b){AdfAssert.assertDomElement(a,"IFRAME");var c=this._getWindowSelection(a);c&&(c.removeAllRanges(),c.addRange(b))};AdfGeckoEditingAgent.prototype._getWindowSelection=function(a){AdfAssert.assertDomElement(a,"IFRAME");return this.getInlineFrameDocument(a).defaultView.getSelection()};
AdfGeckoEditingAgent.prototype.handleTab=function(a,b){b.shiftKey||(AdfAgent.AGENT.preventDefault(b),AdfFocusUtils.focusNextTabStop(a,null,!0))};AdfGeckoEditingAgent.prototype.queryCommandValue=function(a,b){if(this.isDesignMode(a))return AdfGeckoEditingAgent.superclass.queryCommandValue.call(this,a,b)};AdfGeckoEditingAgent.prototype.queryCommandState=function(a,b){if(this.isDesignMode(a))return AdfGeckoEditingAgent.superclass.queryCommandState.call(this,a,b)};
AdfGeckoEditingAgent.prototype.queryCommandIndeterminate=function(a,b){if(!this.isDesignMode(a))return!1;return AdfGeckoEditingAgent.superclass.queryCommandIndeterminate.call(this,a,b)};AdfGeckoEditingAgent.prototype.queryCommandEnabled=function(a,b,c){if(!this.isDesignMode(b))return!1;return AdfGeckoEditingAgent.superclass.queryCommandEnabled.call(this,a,b,c)};
AdfGeckoEditingAgent.prototype.CreateLink=function(a,b,c){for(var d="",e="",f=0;f<c.length;f++)e=c.charAt(f),d+=this._asciiValue(e)==256?encodeURI(e):e;return AdfGeckoEditingAgent.superclass.CreateLink(a,b,d)};AdfGeckoEditingAgent.prototype._asciiValue=function(a){for(var b,b=0;b<256;++b){var c=CSCOCall_toString(b,"toString",16);c.length==1&&(c="0"+c);c="%"+c;c=unescape(c);if(c==a)break}return b};